### PR TITLE
NEW: Validate the Title on Group is not empty

### PR DESCRIPTION
**Pull request by textagroup**
You can currently create a new Group in the Security section of the CMS and leave the Title blank or fill it with only whitespace.

This pull requests adds some more validation on the Group DataObject as well as updating the GroupTest unit test.

### CODE REVIEW

**Comment by michalkleiner** [comment]
Yeah, I think I view it the same, more concerned about existing project code that works with the `Code` field and doesn't bother about the `Title`.

I guess we could keep the validation and check `if (!trim(Title) || !trim(Code)) .. raise the error`, and also update the Title from the Code field as you suggested either in `onBeforeWrite` if it kept the validation on both fields functional, or in `onAfterWrite` using an extra write (which won't matter much since groups are not versioned).

**Comment by michalkleiner** [comment]
Nice one @kinglozzer!

If there's no field for code to manage via the CMS UI, should it act like `URLSegment` and automatically check if it's unique and append the `-2`, `-3` to keep it unique?

**Review by michalkleiner — APPROVED** [review]
Looks ok to me, thanks @textagroup.

@kinglozzer or @emteknetnz — can you give it another tick, too? Thanks!

**Review by emteknetnz — APPROVED** [review]

**Comment by kinglozzer** [comment]
Looks like this has caused some build failures 😞 not sure why the PR build passed https://github.com/silverstripe/silverstripe-framework/runs/4087515550

**Comment by kinglozzer** [comment]
I guess it’s because we now have to make the change in two places as a result of the PHPUnit 9 changes?

**Comment by kinglozzer** [comment]
Fix: https://github.com/silverstripe/silverstripe-framework/pull/10136

**Pull request merged**
