### PR TITLE
Minor: removed box shadows

### PR DESCRIPTION
**Pull request by Meeeeeeow**
image

### CODE REVIEW

**Comment by tractorcow** [comment]
Please approve @flashbackzoo :P

**Comment by clarkepaul** [comment]
Looks good, cheers

**Comment by tractorcow** [comment]
I don't get this PR... only scss files were changed, but compiling it doesn't affect any css?

**Comment by tractorcow** [comment]
Right, was running compass in framework not framework/admin. :) haha.

**Comment by tractorcow** [comment]
Merged with https://github.com/silverstripe/silverstripe-framework/commit/d8ee25c39c1156fab707cafeaf9271a066f7a0d7

**Pull request closed without merging**
