### PR TITLE
ENH: RemoveAll() memory performance enhancement.

### PR DESCRIPTION
**Pull request by mfendeksilverstripe**
# ENH: RemoveAll() memory performance enhancement.

Load a single model into memory at a time instead of loading all models at once.

### CODE REVIEW

**Comment by GuySartorelli** [comment]
Thanks @mfendeksilverstripe - can you please change the prefix of the commit from `NEW` to `ENH`?

**Comment by mfendeksilverstripe** [comment]
@GuySartorelli Done, please review.

**Comment by GuySartorelli** [comment]
Looks good and works well locally.
I just checked test coverage and have noticed there aren't any unit tests for `removeAll()` at the moment. Do you have time to add some unit tests to cover this?

**Comment by mfendeksilverstripe** [comment]
@GuySartorelli Added test as requested ;-)

**Review by GuySartorelli — APPROVED** [review]

**Pull request merged**
