### PR TITLE
PHP 8.0.0 support for 3.x

### PR DESCRIPTION
**Pull request by odraska**
the most important changes for support of new PHP 8.0.0.

### CODE REVIEW

**Comment by michalkleiner** [comment]
Thanks for the contribution / Díky za příspěvěk 👍

**Comment by chillu** [comment]
Thanks for your contribution! CMS 3.x is in "Limited Support", which is defined as "Critical bugfixes and critical security fixes" (https://www.silverstripe.org/software/roadmap/). Talking to some other maintainers, we don't see PHP 8 support as fitting this description, especially since CMS 3.x will be EOL before PHP 7.x runs out of support - so you can still run sites securely on a compatible version of PHP.

That being said, we do acknowledge that some community members might be interested in maintaining PHP 8 support for CMS 3.x. The easiest option for this would be a fork (with some clear caveats about its usage). Keep in mind that you would have to keep this fork up to date with security releases in the CMS 3.7 release line.

The maintainers and some core committers discussed the option to create a `3.8.x-dev` release line for PHP 8 compatibility purposes, and not perform any stable releases on there (to avoid setting expectations around support we can't meet with our current resources). Most people weren't keen on this, since it increases our support commitments: We would need to forward port any security and critical bugfixes to this branch, and would become the default owners of any follow up work and regressions introduced by these changes.

Do you think a fork would be feasible for you to maintain? Do you have plans to also check and fix other common modules such as `silverstripe/cms` to work with PHP 8, and test this in continuous integration? If there was a well maintained fork, we'd be happy to direct community members into this direction.

/cc @silverstripe/core-team

**Comment by ScopeyNZ** [comment]
FWIW I'm fine with merging this, but I don't think we'll ever do another release of SS3. If you want to use this PHP8 support, you use the dev branch, and deal with all the connotations around using a dev branch. I don't really think we even need to create a 3.8.x-dev branch. Just hit the merge button as is - the change is unbreaking from the looks of things anyway.

I think it's pretty clear now that we don't support SS3. And it's pretty easy to hit the "saved replies > SS3" button when people raise issues/requests.

Forking framework is a good option if you want to create and manage stable releases yourself for proper Composer constraints.

**Comment by odraska** [comment]
Hello, 
thank you for the swift reply. 

I maintain many quite big projects (www.typotheque.com, fontstand.com, elefont.info, ...) created on SilverStripe framework 3.x and is very complicated to change it to 4.x version.
My oldest project on SilverStripe 3 framework is about 8 years old and it is still in active development.

Therefore I will create my own fork for SilverStripe 3.8 with PHP8 support, of course I will try to support it and maintain. 
But for now I don't have any experiences with supporting/managing community projects, but I am open for this new oportunity.

I think there is lot of developers which need to use SilverStripe 3 on their old projects.

**Comment by wilr** [comment]
> I maintain many quite big projects ([www.typotheque.com](http://www.typotheque.com), fontstand.com, elefont.info, ...) created on SilverStripe framework 3.x and is very complicated to change it to 4.x version.

Happy to help volunteer some my time and expertise to get your upgrades finished if this is the main reason you're not on the supported version rather than seeing people resurrect older release lines and the implications that brings. So far haven't found a project that *couldn't* be upgraded! Drop me any details will@fullscreen.io

**Comment by chillu** [comment]
Thanks for understanding @odraska! I'm going to close this PR since we're not intending to merge it. Once you've got a fork up and running (with some clear expectation setting in the README), you're welcome to post it here. We could add a note to https://docs.silverstripe.org/en/4/getting_started/server_requirements/ about this option.

**Pull request closed without merging**
