### PR TITLE
Feature: Convert::raw2filename

### PR DESCRIPTION
**Pull request by wernerkrauss**
This might be a handy shortcut for sanitising a filename.

See https://github.com/silverstripe/silverstripe-errorpage/issues/8
See https://github.com/silverstripe/silverstripe-subsites/issues/299

### CODE REVIEW

**Comment by dhensby** [comment]
So we are replacing `FileNameFilter::create()->filter($f)` with `Convert::raw2filename($f)`?

I'm not sure there's a big incentive for this

**Comment by tractorcow** [comment]
Thanks for the suggestion, but I don't think the additional reference is necessary for this functionality.

**Comment by wernerkrauss** [comment]
@dhensby it's a similar shortcut like `Convert::raw2url()`, which ishandy and easier to find for new developers.

**Comment by tractorcow** [comment]
Sorry it looks like there isn't enough core member support for this feature.

**Pull request closed without merging**
