### PR TITLE
Apply email defaults to SS_LogEmailWriter

### PR DESCRIPTION
**Pull request by andrewandante**
After #5626 there will be no fallback for the "from" address on SS_LogEmailWriter. This PR will try to use SS_SEND_ALL_EMAILS_FROM as the "from" address in the first case, before falling back on the `send_from` address, then the `admin_email` address.

This means that the expected behaviour of SS_SEND_ALL_EMAILS_FROM is kept intact.

### CODE REVIEW

**Comment by tractorcow** [comment]
@dhensby you'll need to manually merge this into rc4 :)

**Comment by andrewandante** [comment]
I've updated the PR to also use the -f option as a first attempt, replicating the behaviour [in Mailer](https://github.com/silverstripe/silverstripe-framework/blob/3.5.0/email/Mailer.php#L225-L230). This was the actual cause of the problem I experienced on our AWS infrastructure.

**Comment by dhensby** [comment]
OK - I'll handle manually merging this into the release

**Comment by tractorcow** [comment]
ta!

**Pull request merged**
