### PR TITLE
Upload_Validator fixing getAllowedMaxFileSize

### PR DESCRIPTION
**Pull request by timkung**
Fixing this issue: https://github.com/silverstripe/silverstripe-framework/issues/5222

### CODE REVIEW

**Comment by dhensby** [comment]
Any chance of a test to prove this?

**Comment by tractorcow** [comment]
Yes please. :D

**Comment by christopherdarling** [comment]
Just experienced this with a wildcard max file size limit not being respected (getAllowedMaxFileSize returns false).

I've just done a test that hopefully proves this and raised a PR here -  https://github.com/silverstripe/silverstripe-framework/pull/5396

**Comment by tractorcow** [comment]
No test added so I've re-opened with a test at https://github.com/silverstripe/silverstripe-framework/pull/5444

**Pull request closed without merging**
