### PR TITLE
BUG Fix issue with SS_List as datasource for dropdown field

### LINKED ISSUE #6166: CheckboxSetField no longer accepts DataLists as a source argument
Upgrading from 3.1 -> 3.4 I found that adding a `CheckboxSetField` to the CMS to represent a relationship no longer validates when passing a datalist and instead an array is needed.

eg:

```php
CheckboxSetField::create('HasManyRelationName', 'Field Label', RelatedObject::get());
```

In the CMS this will return a validation error of "Please select a value from the list provided. 'RelatedObject and RelatedObject [repeats]' is not a valid option"

### PR DESCRIPTION
**Pull request by tractorcow**
BUG Fix validation issue with CheckboxSetField
Fixes #6166

@dhensby hope this solves all the issues. :)

### CODE REVIEW

**Comment by tractorcow** [comment]
Also removes rule that values need to be a map where keys === values. Now it just checks values (so you can have a non-associative array of valid values).

**Comment by dhensby** [comment]
Looks nice. I'll test it out and merge if it works (And if tests pass)

**Comment by dhensby** [comment]
I've tested locally and it's all good.

You've used short array syntax, which has broken the build - I'm merging by hand - just running tests then will merge

**Comment by tractorcow** [comment]
Darn it, I've been doing too much 4.0!

**Pull request merged**
