### PR TITLE
Fixed breadcrumb icon spacing

### PR DESCRIPTION
**Pull request by chillu**
Regression from https://github.com/silverstripe/silverstripe-framework/issues/5917

### CODE REVIEW

**Comment by dhensby** [comment]
Code climate / npm checks failing...

**Comment by chillu** [comment]
@dhensby Tests are passing, happy to merge?

**Comment by dhensby** [comment]
done

**Comment by chillu** [comment]
Chur bro! Had enough exposure to Kiwis now to take on their phrases? ;)

**Comment by dhensby** [comment]
I'm resisting... trying to resist. must resist

**Pull request merged**
