### PR TITLE
API Duplication of many_many relationships is now opt in

### PR DESCRIPTION
**Pull request by tractorcow**
Fixes https://github.com/silverstripe/silverstripe-cms/issues/1453

It also works properly on unsaved records.

### CODE REVIEW

**Comment by tractorcow** [comment]
I've rebased this. Anyone care to review? @dhensby ? :P

**Comment by tractorcow** [comment]
I'm going to revert default to true, to keep from breaking duplication of nested objects in CMS.

**Comment by tractorcow** [comment]
I need to update this PR, block this for now. Don't merge yet!

**Comment by kinglozzer** [comment]
Welp, Github doesn’t let you remove reviews. What needs fixing @tractorcow? I still can’t spot it 😳

**Comment by tractorcow** [comment]
I've changed the behaviour in a way that fixes the original issue, but doesn't completely disable many_many duplication by default.

The issue was with belongs_many_many being duplicated; I've changed it so that it duplicates only many_many by default (but this can be changed).

@dhensby how is this as an alternative? I'll write some unit tests if you like this.

**Comment by tractorcow** [comment]
Ok, tests added. Now I'm happy this can be merged. :)

It does need re-approval of the general logic, however.

**Comment by tractorcow** [comment]
@kinglozzer the use case @dhensby raised earlier was a page having many_many images, and a duplicate suddenly losing all those images. :D

**Comment by dhensby** [comment]
OK - I this makes sense to me

**Comment by tractorcow** [comment]
Fixed linting issue

**Comment by tractorcow** [comment]
Green and can merge. :)

**Pull request merged**
