### PR TITLE
BUG: DB connection encoding / collation fix.

### PR DESCRIPTION
**Pull request by mfendeksilverstripe**
Fix for https://github.com/silverstripe/silverstripe-framework/issues/9160

### CODE REVIEW

**Comment by mfendeksilverstripe** [comment]
Didn't check yet, I only tested it with my test case (Fluent + History tab).

**Comment by mfendeksilverstripe** [comment]
@dnsl48 Added the unit test and one suit is passing, the others are failing.

**Comment by dnsl48** [comment]
Looks like the passing test just does not run the framework (failing) tests, that's why it's passing.

**Comment by dnsl48** [comment]
I think I may have tried this fix too initially. My guess it's not working because it may require some extra server-side configuration changes (as per the [comment](https://www.php.net/manual/en/mysqli.set-charset.php#121647))

**Comment by mfendeksilverstripe** [comment]
Ok, will investigate this further.

**Comment by mfendeksilverstripe** [comment]
@dnsl48 Pushed up updated unit tests which are now all green. I changed the unit tests to check for the case which was causing the issue as opposed to checking DB connection settings. This is more end-to-end test approach.

**Comment by dnsl48** [comment]
>  I changed the unit tests to check for the case which was causing the issue as opposed to checking DB connection settings

Haha, that's good, but I'm not sure that's fair :D
If the bug is not with the actual collation, but rather with the settings, we should at least add the test that verifies it.
 For example, we could add a test for ordering that behaves differently between `utf8mb4_general_ci` and `utfmb4_unicode_ci` and validate that regardless of what collation is returned by connection settings, the ordering is still correct.

**Comment by mfendeksilverstripe** [comment]
@dnsl48  That's what this test already covers. The query contains `=` condition which will throw if values on both sides have different collations (the default collation being `utf8_general_ci`). Try running my unit test without the fix and you will see that it will throw.

Isn't this the recommended way how to fix bugs? Write a unit test which reproduces the observed issue which fails and then provide a fix for it? My unit test is a simplified version of an actual query which is used to populate history tab. This was the place where we observed the issue.

**Comment by dnsl48** [comment]
Fair enough. I'll play with the fix some time this week.

**Comment by dnsl48** [comment]
Sorry for the delay. Yes, I've had a dig into it and I can confirm that it's true that `mysqli->get_charset()->collation` has a bug there.
The patch for `MySQLiConnector` in this PR is unnecessary, everything already works fine. I'm going to amend the tests so that we account for the bug with `mysqli->get_charset()->collation`, document it and then I think we can unblock the original issue.

Thank you for looking into it! I'll be working with the original PR and rewrite the tests to cover the actual collation behaviour rather than what's returned by `mysqli->get_charset()->collation`.

**Pull request closed without merging**
