### PR TITLE
API use injector for DataObject::newClassInstance()

### PR DESCRIPTION
**Pull request by tractorcow**
API Fail on invalid class type change

Partial fix for https://github.com/silverstripe/silverstripe-cms/issues/1210. Second PR will be needed on CMS module (will do later).

### CODE REVIEW

**Comment by kinglozzer** [comment]
Looks good, test failures related?

**Comment by tractorcow** [comment]
Wow that's a weird error... er... i'll look into it tomorrow. :D

**Comment by tractorcow** [comment]
Other PR is at https://github.com/silverstripe/silverstripe-cms/pull/1599, but I better fix this one first.

**Comment by tractorcow** [comment]
Ok, new change with slightly more forgiving behaviour for DataObject::setClassName() to prevent regressions.

**Comment by tractorcow** [comment]
ok it's green. :D

**Pull request merged**
