### PR TITLE
Update MigrationTask class to be an abstract class

### PR DESCRIPTION
**Pull request by michalkleiner**
Following on from #9426, making `MigrationTask` class `abstract`.

### CODE REVIEW

**Comment by dhensby** [comment]
Well, it's green (in travis)

**Comment by dhensby** [comment]
I suspect this needs rebasing - I've tried, but I can't push to the chrometoaster repo :(

**Comment by michalkleiner** [comment]
Rebased.

**Comment by emteknetnz** [comment]
Thank you :-)

**Pull request merged**
