### PR TITLE
DOCS 3.1 - fixes broken internal links

### PR DESCRIPTION
**Pull request by SpiritLevel**
Following up on rewrite rules (see silverstripe/doc.silverstripe.org#91) :)

### CODE REVIEW

**Comment by SpiritLevel** [comment]
Hey @tractorcow ! Can this be merged into 3.2,3.3,and 4.0 as well as into 3.1 ? The broken internal links appear to be identical for 3.1 and higher. After you merge up, I'll double check and fix anything that isn't covered by merging this up. What do you think ? :)

**Comment by camfindlay** [comment]
much kudos for this @SpiritLevel !

**Comment by tractorcow** [comment]
Yeah we can merge up.

**Comment by SpiritLevel** [comment]
@camfindlay This will make .htaccess in docs much simpler! :) Thanks @tractorcow...

**Pull request merged**
