### PR TITLE
[WIP] Add phpstan to travis testing, via Symbiote module.

### PR DESCRIPTION
**Pull request by sminnee**
This has been kicked about a few times before:

 * #7899
 * #9039

Notably, I'm relying on the Symbiote module to get PHPStan to provide some knowledge about SilverStripe; given on our reliance on custom dynamic mechanisms such as Injector, anything else would seem a bit limited. If we've got ideas for how to do things better than the current Symbiote module I think we can push requirements there.

Marking as WIP, was keen to confirm that we can get travis running this before addressing the issues.

cc @szepeviktor

### CODE REVIEW

**Comment by sminnee** [comment]
I'd recommend that we try and get this reviewed and merged before including this: https://github.com/symbiote/silverstripe-phpstan/pull/21

**Comment by szepeviktor** [comment]
We have a lot of very easy problems reported.

**Comment by sminnee** [comment]
A notable impact of this is that phpstan expects composite type signatures to be, .e.g. `array<int,string>`. Is this compatible with other tools in our toolchain?

**Comment by szepeviktor** [comment]
You can simply use "array". PHPStan will figure it out.

**Comment by sminnee** [comment]
That's not true in some cases, which came out of my testing. `array<int,mixed>` is more specific than `array` because it excludes maps. Therefore in cases that expect `array<int,mixed>`, using `array` as the type hint throws an error.

Also - the specificity is a good thing! :)

**Comment by ScopeyNZ** [comment]
So `string[]` doesn't work? 🙁

**Comment by szepeviktor** [comment]
It should.

**Comment by ScopeyNZ** [comment]
I would prefer we use `string[]|int[]` if possible - it's used elsewhere. Hopefully phpstan supports using `|` and `&` for return types (& is for things like `DataObject[]&DataList`).

**Comment by szepeviktor** [comment]
Tell me about `&`. What does it mean?

**Comment by ScopeyNZ** [comment]
The best example is the one I gave. `DataList` is the collection object that implements `ArrayAccess`. The collection only contains `DataObject`s so the `&` implies that both types are returned. Another example would be returning an object that definitely implements two interfaces. `@return InterfaceA&InterfaceB` means you can be certain you can use methods from both interfaces after getting the result.

**Comment by dnsl48** [comment]
Regarding `[]` vs `<>` notation, phpstan [supports both](https://phpstan.org/r/a37f3d28-83a9-42e6-9dca-fcb3df0b7a62). Many other tools do so too (e.g. phan and phpstorm).
However, `[]` notation is less specific than `<>`. `[]` does not imply arrays with integer keys (as it would be in Java, for example), but rather php array with any key types.

As such, `type[]` === `array<mixed, type>`

[Here are some examples](https://phpstan.org/r/7261ed3e-6aee-4978-9699-59fd7eaa2192):

Example 1:
```php
        /**
	 * @return string[]
	 */
	public function test1(): array
	{
		return ['a' => 'b', 'b'];
	}
```
`[OK] No errors`

```php
        /**
	 * @return array<int, string>
	 */
	public function test2(): array
	{
		return ['a' => 'b', 'b'];
	}
```
`Method HelloWorld::test2() should return array<int, string> but returns array<int|string, string>.`

```php
        /**
	 * @return array<string, string>
	 */
	public function test3(): array
	{
		return ['a' => 'b', 'b'];
	}
```
`Method HelloWorld::test3() should return array<string, string> but returns array<int|string, string>.`

As such, ideally `<>` notation should have the precedence whenever possible. When array keys may have mixed type though, we could use `[]` I guess.

**Comment by sminnee** [comment]
Oh, right, I thought phpstan didn't support `type[]` syntax, which was my motivation for change. I'll fix in my patches.

I agree with @dnsl48 on the following precedence, but happy to go with consensus one that.

 * `array<int,string>` or `array<string,string>` - must be an array or must be a map
 * `string[]` - could be either (which will be much or the framework tbh)
 * `array<string>` - don't use.

**Comment by sminnee** [comment]
It looks like phpstan supports `&` :) https://phpstan.org/r/615518a5-ada3-4898-bede-f5fa34d8edd5

However, it looks like your `DataObject[]&DataList` example won't work: https://phpstan.org/r/ef0d2c6a-99a6-49b4-a426-7591063d767a

To be honest phpstan is probably doing the right thing here. `DataList<Member>` would most likely be a better way of expressing this, and the silverstripe-phpstan module should be able to be amended to support that

You can already do this with iterators: https://phpstan.org/r/ecf11129-792c-4892-b7d6-1b26adc9edc6

...so `iterable<string>&DataList` probably works out of the box.

**Comment by ScopeyNZ** [comment]
> However, it looks like your `DataObject[]&DataList` example won't work: [phpstan.org/r/ef0d2c6a-99a6-49b4-a426-7591063d767a](https://phpstan.org/r/ef0d2c6a-99a6-49b4-a426-7591063d767a)

It looks like this was an incorrect link? Here's one I prepped though:

https://phpstan.org/r/ac383808-82fc-49fa-8297-304f07fab228

I wonder about this - it's a pity it doesn't work. Could be a feature that's just missing implementation right now. `DataList<Member>` definitely would be nicer though 😅 .

Our team has started to use `&` where it makes sense but I'll mention in my peer reviews going forward that we can't use it for those cases.

**Comment by sminnee** [comment]
> I wonder about this - it's a pity it doesn't work

No, it’s not a pity - it’s not a real type spec; it’s an almost-a-type-spec. dataList isn’t an array.

**Comment by ScopeyNZ** [comment]
> > I wonder about this - it's a pity it doesn't work
> 
> No, it’s not a pity - it’s not a real type spec; it’s an almost-a-type-spec. dataList isn’t an array.

Ok sure. But it would be nice if we could hint `iterator<Member>&DataList` at least.

**Comment by sminnee** [comment]
You can do the latter afaik. Might be iterable rather than iterator

**Comment by ScopeyNZ** [comment]
Na I've been playing with this. Found an issue to this effect too:

https://github.com/phpstan/phpstan/issues/1727

**Comment by sminnee** [comment]
OK I've fixed _hopefully_ all of the level 2 issues now, and I've broken the fixes out into a bunch of different commits to support the review.

**Comment by szepeviktor** [comment]
Very nice work.
I think you recognized the huge benefit of phpstan.

**Comment by michalkleiner** [comment]
This might not be the best convo for this, but....

Thanks @szepeviktor for actually taking on the huge task/effort of trying to push static code analysis through on a framework like SilverStripe.

At Chrometoaster, we use PHPStan and other code quality tools for the actual project-scope code, but having it consistently applied throughout the framework and the CMS is a next level effort, but worth pursuing 

I'm pretty sure Sam and other folks at SilverStripe Ltd. see the benefits it can bring, they're a pretty smart bunch (speaking as an outsider and a user of the fw), it's just not always as simple as "let's just do it" for any number of  business/historical/backwards-compatibility reasons.

Keep the pressure up, @szepeviktor, I'd be happy to see the fruits of this effort ;-)

**Comment by szepeviktor** [comment]
Until #9033 is fixed you could add this to ignores:

`#SilverStripe\\CMS\\#`

**Comment by sminnee** [comment]
If 87ecbb380fa286507735058c8363938c2bf287fb fixes it that's probably better - we can include the CMS recipe when performing static analysis, so we get to perform the tests rather than ignore them.

**Comment by szepeviktor** [comment]
What a 🍏 green success!

**Comment by szepeviktor** [comment]
@sminnee Try executing

```bash
grep -rFl '@return $this' | xargs -L1 sed -e 's#@return \$this#@return self#' -i
```

**Comment by sminnee** [comment]
@silverstripe/core-team this will require a bit of love to get over the line but it's probably worth fielding more opinions on whether we're on board with adding phpstan as a part of our CI loop? Once it's in, we don't be able to ignore it ;-)

**Comment by robbieaverill** [comment]
+1 from me for adding it across the board.

---

@sminnee FYI we just discussed the `@return` type issue in our retro, and decided that "we aim to comply with PSR-5. Given that `@return $this` is valid in PSR-5, we won't be actively changing it to `@return self`" but I don't think we'd request a change from the latter to the former in a pull request

**Comment by sminnee** [comment]
Righto I'll just leave it at `$this` then. If it causes problems we'll loop back and see if we're up for a project-wide change of standard.

PS: As a general rule I'm skeptical about "we comply with PSR-5" rather than "we comply with the results of this automated checker". Automated checkers that are part of the CI loop are the only thing that I've seen actually lead to a consistent adoption of any given standard.

**Comment by robbieaverill** [comment]
PHPStan has no problem with it, not does PSR-5, so I see no need to change it :-)

**Comment by chillu** [comment]
I'm generally happy with stricter linting, provided that any changes to compy with this new linting are backwards compatible (on the `4` branch target). Are we implicitly deciding about some grey areas by merging this pull request? There's a lot of discussion, I've lost track. @sminnee Maybe you can summarise what is being decided by merging?

It's yet another thing that'll break builds in unexpected ways for most core developers and contributors though - late stage feedback after PR has been submitted, and many hours before the submitter gets feedback from a broken build (hard context switch). Can we a) roll this into a `composer run lint` command, and b) document that for contributors on docs.silverstripe.org? We should also aim to get every committer set up with pre-commit hooks, and/or editor integrations.

I'm OK merging this to `framework` *before* applying the same rigour to other core modules, but we need a follow up ticket.

**Comment by sminnee** [comment]
> Are we implicitly deciding about some grey areas by merging this pull request? There's a lot of discussion, I've lost track. @sminnee Maybe you can summarise what is being decided by merging?

I'm going to roll back some of the inappropriately disruptive changes (notably moving from func_get_args to variadic signatures in some SS_List methods) and work out a hackier-but-less-disruptive fix for those (putting some hardcoded info into the symbiote/silverstripe-phpstan module so that it knows what the types should be).

Once I've actually got something that's not WIP I'll summarise the impact of the change.

> Can we a) roll this into a composer run lint command, and b) document that for contributors on docs.silverstripe.org? We should also aim to get every committer set up with pre-commit hooks, and/or editor integrations.

Makes sense.

> I'm OK merging this to framework before applying the same rigour to other core modules, but we need a follow up ticket.

Sure thing. By that stage I'd probably want others to help out, though ;-) Perhaps our own docs should have some "how to deal with common phpstan failures" guidance.

> It's yet another thing that'll break builds in unexpected ways for most core developers and contributors though

One idea is that we could put the phpstan and phpcs checks as the first build, which combined with fast-fail should mean that linting failures are reported a little more quickly? Although not 100% reliable I believe the first build in the list is most likely to be started first.

**Comment by sminnee** [comment]
I would note that I'd prefer to get #9661 merged and then rebase the remaining 5 commits on this branch on that.

**Comment by szepeviktor** [comment]
Mayb that PR turned out to be bigger than big :) takes 3 lightyears to review...

**Comment by GuySartorelli** [comment]
While a phpstan config would be good, too much has changed since this PR was last touched, it would effectively need to be done from scratch. I'm going to close it on that basis.

**Pull request closed without merging**
