### PR TITLE
fix invalid cache key

### LINKED ISSUE #10889: VersionProvider always write to cache
## Affected Version

4/5

## Description

Thanks to the new Cache tab I added to debugbar, i've realised that VersionProvider is always setting the cache due to an invalid cache key (somehow it's not throwing an exception i guess the adapter silently rewrites the key and therefore it's never found when using get)

as per psr 6

According to PSR-6 the following characters could be used in a valid cache key; A-Z, a-z, 0-9, _, and .. Some characters are forbidden like: {}()/\@:. If you use any of the forbidden characters you will get an exception. Other characters (like -) are not forbidden nor valid. It is up to the implementation if they support that character or not.

current key includes / and \ due to the path being used

## Steps to Reproduce

- open a page
- set method is called each time
- visible in debugbar

## PRs
- https://github.com/silverstripe/silverstripe-framework/pull/10890
- https://github.com/silverstripe/silverstripe-framework/pull/10894

### PR DESCRIPTION
**Pull request by lekoala**
fixes https://github.com/silverstripe/silverstripe-framework/issues/10889

### CODE REVIEW

**Comment by michalkleiner** [comment]
Thanks for the contribution, @lekoala! Can you please rebase it on `5.0` and then retarget the PR? I think this can be released as a patch.

**Comment by lekoala** [comment]
not super familiar with rebasing pr on github, but this seems like it should do it :)
EDIT: nope, it's not working^^

**Comment by lekoala** [comment]
well, might as well recreate it
https://github.com/silverstripe/silverstripe-framework/pull/10894

**Comment by michalkleiner** [comment]
You wouldn't rebase on Github, but locally either using git cli or git gui and then force-push the branch.

**Comment by lekoala** [comment]
:) that's actually more effort than create another one

**Pull request closed without merging**
