### PR TITLE
Allow PHPParser v4

### PR DESCRIPTION
**Pull request by dhensby**
Tested locally and still works a treat :)

### CODE REVIEW

**Comment by kinglozzer** [comment]
I can’t spot anything breaking in the [changelog](https://github.com/nikic/PHP-Parser/blob/master/CHANGELOG.md), but should we wait for a stable release before merging just in case anything else changes?

**Comment by dhensby** [comment]
@kinglozzer it's been released as beta and they've said the next release will be stable - I don't expect any changes so radical from the beta that would cause our fairly basic use of the parser to break...

Though I suppose it doesn't hurt to wait

**Comment by tractorcow** [comment]
How about disallowing the older ^2 while we're at it?

**Comment by dhensby** [comment]
OK, 4.0.0 is stable now and I've restarted the test suites so they'll pull in 4.x

> How about disallowing the older ^2 while we're at it?

Personally, my view is that if it works, we should keep it. As a library we should be as loose as possible with constraints and leave it to the projects to be as strict as possible so that we aren't the cause of unresolvable dependency definitions. If we do work with v2 then we shouldn't be blocking it

**Pull request merged**
