### PR TITLE
Allow re-rendering Email on data update (fixes #9289)

### LINKED ISSUE #9289: Email not re-rendering HTML template
## Affected Version
Latest (4.4.4)

## Description
Using `setHTMLTemplate` and `setData` on an `Email` will correctly render the data. However when running a second time, the `Email` class will not re-render.

## Cause
I've narrowed this problem down to this line:
https://github.com/silverstripe/silverstripe-framework/blob/d1c927ff2372a422ca8d5145aee6ba5192355f80/src/Control/Email/Email.php#L803

I believe there is no need for the `!$htmlPart` check other than maybe performance reasons? I have attached a PR.

Thanks!

#### PRs

- [x] #9876

### PR DESCRIPTION
**Pull request by NikxDa**
Please refer to the corresponding issue #9289.

### CODE REVIEW

**Comment by NikxDa** [comment]
@maxime-rainville I don't see how this would be affected - could you shed some light on why `setBody` would stop working?

**Comment by maxime-rainville** [comment]
My main point is that I think this behaviour should be an opt-in or something the developers explicitly request somehow.

I do think your PR is trying to address a real issue, in that there's no way to force a re-render of your email message. People can do that implicitly by calling `setBody(null)`, but that's not super intuitive.

Whichever way you approach this, you'll probably to add some extra unit tests using the `makeEmailMock` method to confirm your email messages gets re-rendered the second time around.

https://github.com/silverstripe/silverstripe-framework/blob/d1f30a20c20aec63a04e487cee801368409d3b38/tests/php/Control/Email/EmailTest.php#L631-L646

> I don't see how this would be affected - could you shed some light on why setBody would stop working?

I haven't tried this, but if you did something like this, I think your PR would alter the results.
```php
$message = new Email(
    'bob@example.com',
    'bob@example.net',
    'test subject',
    'The quick brown fox jumps over the lazy dog'
);
$message->render();
```

This line gets the current body in the render method. https://github.com/silverstripe/silverstripe-framework/blob/2016f98a86dd3abc39806007efaf6753801878d8/src/Control/Email/Email.php#L784

Your change alters line 803 to no longer check for `$htmlPart`. So the `if` statement would be run overriding the body of the message as defined in the constructor.

Another thing, I'm not sure about is that the `send` will only call `render` if body is unset. https://github.com/silverstripe/silverstripe-framework/blob/2016f98a86dd3abc39806007efaf6753801878d8/src/Control/Email/Email.php#L749-L758

So if you did something like this, your message wouldn't be rendered the second time even with your chance applied.
```php
$message = new Email(
    'bob@example.com',
    'bob@example.net',
    'test subject',
    'The quick brown fox jumps over the lazy dog'
);
$message->send();
$message->setTo('bob@example.org');
$message->send();
```

**Comment by NikxDa** [comment]
@maxime-rainville Thanks for elaborating! I'll see if I can get some of those changes added this week :)

**Comment by emteknetnz** [comment]
This pull request hasn't had any activity for a while. Are you going to be doing further work on it, or would you prefer to close it now?

**Comment by emteknetnz** [comment]
It seems like there's going to be no further activity on this pull request, so we've closed it for now. Please open a new pull-request if you want to re-approach this work, or for anything else you think could be fixed or improved.

**Pull request closed without merging**
