### PR TITLE
FIX Invoke method addHeader on NULL

### PR DESCRIPTION
**Pull request by sabina-talipova**
## Description
Check that `$controller->getResponse()` is not `NULL` before invoke `addHeader` on it.

## Parent issue
- https://github.com/silverstripe/.github/issues/162

### CODE REVIEW

**Review by emteknetnz — CHANGES_REQUESTED** [review]
Can you point to where this is an error? Does it only happen in CI or locally? Any idea what this mysterious Controller without a response is?

**Comment by sabina-talipova** [comment]
This issue happens now only in CI and related to this [PR](https://github.com/silverstripe/silverstripe-framework/pull/11037).
I just might assume that something happens in mock controller. I think, if we add `$controllerMock->method('getResponse')->willReturn('test');` probably also solve the problem, but I think just in case would be better to check that we have response before.
I'll open PR for `ckan-registry` as well.

**Comment by emteknetnz** [comment]
Sorry I mean can you link to the broken build in CI?

**Comment by sabina-talipova** [comment]
Oh, sorry.
Here it is https://github.com/silverstripe/silverstripe-ckan-registry/actions/runs/7019350079/job/19122212114

**Comment by emteknetnz** [comment]
Better to fix on ckan registry directly.  Closing this PR in favor of https://github.com/silverstripe/silverstripe-ckan-registry/pull/305

**Pull request closed without merging**
