### PR TITLE
FIX: avoid Aggregate clearing entire cache on DataObject::write

### PR DESCRIPTION
**Pull request by sunnysideup**
See https://github.com/silverstripe/silverstripe-framework/issues/6383 for more details.

### CODE REVIEW

**Comment by tractorcow** [comment]
This is probably ok for 3.2, but I would mark it as deprecated at 4.0, as with aggregate API.

Test failures are pre-existing. @dhensby do you want to double check this is ok style-wise to merge?

**Comment by sunnysideup** [comment]
@tractorcow are you saying we need to add a deprecate statement in the _config.php file?  How and when would that be used / useful.  Not a rhetorical question - just trying to understand it.  Thank you, as always ;-)

**Comment by tractorcow** [comment]
This is purely my own opinion, but when we add code into 3.x that we don't want bubbling up into 4.0 it's ok to add with an immediate deprecation.

It might be safer to put this code into Aggregate class somewhere, and simply call it from _config.php, rather than inlining it. This would mean it's automatically deprecated.

**Comment by dhensby** [comment]
> It might be safer to put this code into Aggregate class somewhere, and simply call it from _config.php, rather than inlining it. This would mean it's automatically removed on merge up to master.

This is a good idea, can we do it?

**Comment by tractorcow** [comment]
Yeah @sunnysideup please make the suggested tweak, if that's ok :) Aggregate class was deleted, so when we merge we won't end up with artifacts in _config.php that don't do anything.

**Comment by sunnysideup** [comment]
Ok - sorry guys.  I have been super busy with ssmods.com so I have not been able to do any other open source work, but I can perhaps have a go at this in the next few days.

**Comment by dhensby** [comment]
moved to #6569

**Pull request closed without merging**
