### PR TITLE
Add icon for XLSX files (Fixes #5124).

### LINKED ISSUE #5124: Uploading XLSX file to the assets library shows a MS Word icon.
Possible solutions include adding a new app category to `filesystem/File.php` for Excel files, or adding a GIF file named `xlsx_32.gif` to `images/app_icons`.

### PR DESCRIPTION
**Pull request by LeviWB**

### CODE REVIEW

**Comment by jonom** [comment]
@LeviWB this looks fair but if you want to go above and beyond, would you feel like updating all of the icons in `images/app_icons`? They're inconsistent at the moment in size and visual style. Notably half of them are 16x16 but the name implies otherwise. A nice improvement might be to replace them all with open source icons from a single set, and make them PNGs with an alpha background. That part would require a small tweak to File::Icon(). Interested?

@scott1702 thoughts?

**Comment by scott1702** [comment]
Yes I agree, a lot of those images are quite outdated and inconsistent and while this is something we're probably looking to update for 4.0 with the new assets area, it would still be cool if somebody wanted to update them in the 3 branch.

**Comment by jonom** [comment]
Have you guys settled on an icon set already for 4, or have some favourites? If you want to share a link we may as well get it going in a similar direction in 3 branch.

**Comment by scott1702** [comment]
There are some custom-made icons [here](https://github.com/open-sausages/silverstripe-asset-admin/tree/master/javascript/src/img) (ignore treeicons folder and blue-folder...png which were ported over from the cms module). Currently I'm uncertain as to whether we're going to pull in an icon set to handle the rest of the images, but I'm guessing for images for files like these we're going to have custom images.

/cc @clarkepaul?

**Comment by jonom** [comment]
Sweet, thanks @scott1702. Whaddya say @LeviWB, want to give this a go? Otherwise I can do it when I get a chance.

**Comment by clarkepaul** [comment]
We haven't sided with a single icon set yet partly due to not really having a complete idea of what we require at this stage and at what size (even though they are vector sets are usually created to be optimal at certain sizes). The majority of the new icons have come from the set Entypo which isn't going to be varied enough for the CMS by itself. If you want to update icons you could use svg's from nounproject.com possibly and credit the authors? (I have created customised ones from icons on there).

Icons in context of the upcoming design (icons Scott shared are at the bottom): https://projects.invisionapp.com/boards/9GX68PTXUQFH/

**Comment by jonom** [comment]
How about these for 3 so they blend in to existing look:

generic
mov
doc
audio
zip

Based on the icon used in file admin gridfield for all files that aren't images or folders currently.

**Comment by jonom** [comment]
https://github.com/silverstripe/silverstripe-framework/pull/5186

**Comment by tractorcow** [comment]
Superseded with https://github.com/silverstripe/silverstripe-framework/pull/5186

**Pull request closed without merging**
