### PR TITLE
Minor: Unbolded labels in CMS

### PR DESCRIPTION
**Pull request by lry6003**
- updated _forms.scss removed font-weight
- also removed drop-shadow include
Luke Ryley - open source academy

### CODE REVIEW

**Comment by tractorcow** [comment]
It looks like you are pulling to a different branch you created this from... do you need a rebase?

**Comment by scott1702** [comment]
Nice! Happy with this change @tractorcow

**Comment by tractorcow** [comment]
What's the rationale for un-bolding labels in the CMS? This feels like it needs some discussion before I can justify merging it. :)

**Comment by jonom** [comment]
@lry6003 would you mind posting a before and after screenshot please?

**Comment by clarkepaul** [comment]
This was under my direction to minimize elements within the interface. There are too many competing elements in the current interface and labels are only a small part of that. The bold labels stand out a lot and the focus on the page should be more on the fields themselves.

**Comment by clarkepaul** [comment]
This is what I'm expecting (below). I would hope that it has had a bit of testing to make sure it makes sense with a range of scenarios. 

label-weight

**Comment by jonom** [comment]
That's a nice improvement

**Comment by tractorcow** [comment]
Sounds good.... merging. ;0

**Pull request merged**
