### PR TITLE
ENH Also check BASE_URL in host

### PR DESCRIPTION
**Pull request by emteknetnz**
Issue https://github.com/silverstripe/silverstripe-framework/issues/10156

Recipe test
- https://github.com/emteknetnz/recipe-kitchen-sink/pull/1

### CODE REVIEW

**Comment by michalkleiner** [comment]
I'm not 100% sure about the change.

On a correctly configured site (having the BASE_URL configured), with this change, it would always trump any Host header or HTTP_HOST server variable. That basically removes the functionality where a site can respond to multiple domains and let PHP decide what to do with it because it will always behave as on the single domain coming from BASE_URL.

**Comment by emteknetnz** [comment]
That's a good point, probably makes sense to move the call to baseURL() to lower down in the host() method

**Comment by emteknetnz** [comment]
On further inspection this is a pretty pointless PR.

`$default_base_url` comes from SS_BASE_URL https://github.com/silverstripe/silverstripe-framework/blob/4/src/Control/Director.php#L95

Which is also what feeds BASE_URL https://github.com/silverstripe/silverstripe-framework/blob/4/src/includes/constants.php#L111

**Comment by michalkleiner** [comment]
The change now corresponds with what was already expected based on the method's docblock, and I think we should merge this, however, I'm not sure it solves the problem we discussed privately which might be coming from the place where it uses the current request to get the Host header.

**Pull request closed without merging**
