### PR TITLE
API Apply all SilverStripe namespaces to framework

### LINKED ISSUE #5637: Add namespaces to all other classes in framework
From https://github.com/silverstripe/silverstripe-framework/issues/4562#issuecomment-136899388

Note: Below updates by @tractorcow as a new proposed structure.

Other namespaces to split out:

- [x] `SilverStripe\Admin` (to go into a module later) https://github.com/silverstripe/silverstripe-framework/issues/5878
- [ ] `SilverStripe\Assets` Filesystem (to go into a module later)
- [ ] `SilverStripe\Forms`
- [ ] `SilverStripe\Forms\GridField`
- [ ] `SilverStripe\Forms\HTMLEditor`
- [ ] `SilverStripe\View` 
- [ ] `SilverStripe\View\Parsers` moved from parsers folder to View/Parsers 
- [ ] `SilverStripe\Core`  Class, template, config manifest loader, Config, Injector
- [ ] `SilverStripe\Core\Manifest`
- [ ] `SilverStripe\Core\Startup`
- [ ] `SilverStripe\Core\Injector`
- [ ] `SilverStripe\Core\Config`
- [ ] `SilverStripe\Logging`
- [ ] `SilverStripe\i18n`
- [ ] `SilverStripe\Dev`
- [ ] `SilverStripe\Dev\Tasks` moved from tasks to Dev/Tasks

Namespaces already addressed / in-progress:

- [x] `SilverStripe\CMS` https://github.com/silverstripe/silverstripe-cms/issues/1572
- [ ] `SilverStripe\Control` https://github.com/silverstripe/silverstripe-framework/issues/5636
- [x] `SilverStripe\Security`
- [x] `SilverStripe\ORM`

Extend the above namespaces with these sub-namespaces:

- [ ] `SilverStripe\ORM\Search` move search folder to ORM/Search
- [ ] `SilverStripe\ORM\Filters` move search/filters folder to ORM/Filters
- [ ] `SilverStripe\Control\Email` move Email and Mailer into here
- [ ] `SilverStripe\Control\RSS` move RSSFeed into here

Cleanup some outstanding files that don't belong anywhere.

 - CliController -> `SilverStripe\Control`
 - SS_Cache -> `SilverStripe\Core`
 - src/SilverStripe/Framework/Injector/Factory.php -> `SilverStripe\Injector`

Files removed completely:

 - DataFormatter classes https://github.com/silverstripe/silverstripe-framework/pull/5877

### PR DESCRIPTION
**Pull request by tractorcow**
Closes #5637

Merge with these:

 - [ ] https://github.com/silverstripe/silverstripe-asset-admin/pull/243
 - [ ] https://github.com/silverstripe/silverstripe-cms/pull/1602
 - [ ] https://github.com/silverstripe/silverstripe-reports/pull/45
 - [ ] https://github.com/silverstripe/silverstripe-siteconfig/pull/36
 - [x] https://github.com/silverstripe/silverstripe-sqlite3/pull/25
 - [x] https://github.com/silverstripe/silverstripe-installer/pull/135
 - [x] https://github.com/silverstripe/silverstripe-behat-extension/pull/125
 - [ ] https://github.com/silverstripe/silverstripe-behat-extension/pull/126
 - [x] https://github.com/silverstripe/silverstripe-postgresql/pull/55
 - [ ] https://github.com/silverstripe/silverstripe-postgresql/pull/56
 - [x] https://github.com/silverstripe/silverstripe-mssql/pull/37
 - [ ] https://github.com/silverstripe/silverstripe-frameworktest/pull/21
 - [x] https://github.com/silverstripe/silverstripe-testsession/pull/38

I've created this PR early for peer review at @chillu's request. It's not yet ready to be merged.

This PR includes several smaller pieces of work, including:
 - Remove deprecated code (to save having to upgrade / namespace them)
 - Change in behaviour of FormField::_templates() to use the standard class hierarchy lookup.
 - Change SSViewer::get_templates_by_class() to return un-filtered candidate list (performance reasons)
 - Remove `@package` / `@subpackage` - these are no longer necessary within the namespaced hierarchy.
 - Broke each class into a class-per-file, and named appropriately to support psr-4 autoloading.
 - `Diff` library moved into third party, to avoid having to namespace it. `SilverStripe\View\Parsers\Diff` extends the thirdparty lib to encapsulate ss-specific functionality.
 - Cleanup of incorrect PHPDoc, code style improvements and fixes, some tidy up of inconsistent APIs (e.g. invalid method parameters and return types).
 - Replaced as many class string-literals as possible; Sometimes with `__CLASS__`, `get_class($this)`, `static::` and so on. These were problematic to automatically upgrade, so it's simpler if these are simply not necessary. The most common culprit were Config::inst() lookups, which I have attempted to supercede with the `Configurable` trait, and using `$this->config()`, `static::config()`, or `MyClass::config()`. E.g. `Config::inst()->get('SilverStripe\\Security\\RememberLoginHash', 'token_expiry_days')` becomes `RememberLoginHash::config()->get('token_expiry_days');`

### CODE REVIEW

**Comment by tractorcow** [comment]
Ok, the bulk of the work is now complete. I'm going to break this out into separate PRs now.

**Comment by chillu** [comment]
Peer review in comments here, since the diff is too giganormous :D

Do we need another card for updating docs?

The upgrading docs mention very little about namespacing, and only halfway through the docs. It's the single most disruptive upgrading issue, so we'll need to move it up at least. And add some guidance for devs who don't want to run the upgrader (or understand what it does). This could be a pointer to `.upgrade.yml` for a list of mappings, plus an example of how project code would be rewritten (remember, not every SS dev will even be familiar with the `use` statement).

image

We need to upgrade docs for referencing and overriding core templates (the `Make sure templates are in correct locations` section doesn't make it clear that a lot of core templates have moved)

**Comment by tractorcow** [comment]
The story is https://github.com/silverstripe/silverstripe-framework/issues/5763

**Comment by chillu** [comment]
`CompositeField_Holder.ss` - why do we add `$extraClass` there? Doesn't have anything to do with namespacing, right?

```diff
-			<% if $Zebra %> form__fieldgroup-zebra<% end_if %>"
+			<% if $Zebra %> form__fieldgroup-zebra<% end_if %>
+			<% if $extraClass %> $extraClass<% end_if %>"
```

`<% include SilverStripe/Forms/GroupedDropdownFieldOption %>` doesn't find `templates/SilverStripe/Forms/Includes/GroupedDropdownFieldOption.ss`

**Comment by tractorcow** [comment]
That came up during a rebase, I believe. I'm not sure how it got there; maybe I rebased incorrectly?

**Comment by tractorcow** [comment]
from https://github.com/silverstripe/silverstripe-framework/commit/79b7f84a46251245ad8da791e86d44e75cdbc1f9

**Comment by chillu** [comment]
`PublicAssetAdapter.php` - doesn't this change the `filesystem/` folder name?

```diff
-			'.htaccess' => "filesystem/Assets_HTAccess"
+			'.htaccess' => __CLASS__ . "_HTAccess"
 		),
 		'microsoft-iis' => array(
-			'web.config' => "filesystem/Assets_WebConfig"
+			'web.config' => __CLASS__ . "_WebConfig"
```

**Comment by tractorcow** [comment]
> PublicAssetAdapter.php - doesn't this change the filesystem/ folder name?

Yes, it's been moved to `templates/SilverStripe/Assets/Flysystem`

**Comment by sminnee** [comment]
Unless this seriously breaks things (failing tests or critical breakages in a smoke test) my strong preference would be to merge and raise the outstanding items as critical issues. A PR this big helps everyone by being merged sooner rather than later.

**Comment by tractorcow** [comment]
It's already too late... needs another rebase. =( @dhensby

**Comment by dhensby** [comment]
The changes that were merged up into master were quite simple - I don't mind merging this by hand if it's ready to go in now?

**Comment by tractorcow** [comment]
Heh, that's ok @dhensby , I need to rebase it anyway and fix up @chillu 's feedback. :)

**Comment by dhensby** [comment]
>Code Climate found 1,462 new issues.

uh oh

**Comment by tractorcow** [comment]
I've rebased and fixed the issue with the template $extraClass returning.

**Comment by chillu** [comment]
> Removed `Controller::getFormOwner`

Why's that? Add some rationale to the commit message

`HTTP:: filename2url()` should be broken out to a separate commit.

Why did you remove `i18n:: get_translatable_modules()`?

You didn't note the removal of `SS_Log:: add_writer()` in the changelog.

@sminnee I'm doing focused and fast peer review today, we should be in a good position to merge by the end of the day from my perspective.

**Comment by chillu** [comment]
`DataObject.php` - shouldn't this be unescaped 

```diff
-			if($class === 'SilverStripe\ORM\DataObject') {
+			if($class === 'SilverStripe\\ORM\\DataObject') {
```

Did you upgrade `BBCodeParser` as part of moving it into thirdparty? Can you note the before/after versions, ideally with a link to a changelog? Is it a new major release?

**Comment by tractorcow** [comment]
@chillu I just removed all deprecated API. I'll update the docs.

**Comment by tractorcow** [comment]
> > Removed Controller::getFormOwner
> Why's that? Add some rationale to the commit message

Oh, right, this method invoked code that was removed YEARS ago. It should have been deprecated.

**Comment by tractorcow** [comment]
> Why did you remove i18n:: get_translatable_modules()?

It didn't work and wasn't used.

**Comment by chillu** [comment]
> Code Climate found 1,462 new issues.

It looks like those are existing issues are all in a single file: `Dev/Install/client/dist/styles/install.css`. The PR here just changed the capitalisation of a folder name, hence Code Climate complains about it again - we can ignore that.

**Comment by tractorcow** [comment]
Added https://github.com/silverstripe/silverstripe-behat-extension/pull/126

**Pull request merged**
