### PR TITLE
Insert link styling adjustments incl. minor text updates

### PR DESCRIPTION
**Pull request by clarkepaul**
Step 1 being hidden is not part of my work as it was already visible but I've adjusted padding, 
given it standard inline bootstrap styles and adjusted some of the label text to make it more readable.

Before:
image

After:
image

### CODE REVIEW

**Comment by clarkepaul** [comment]
Fixes https://github.com/silverstripe/silverstripe-cms/issues/1561

**Comment by dhensby** [comment]
Behat tests not happy

**Comment by clarkepaul** [comment]
Updating tests now

**Comment by clarkepaul** [comment]
This PR requires tests on CMS on branch pulls/4.0/insert-link to be merged in order for them to pass.

Requires https://github.com/silverstripe/silverstripe-cms/pull/1597

**Comment by tractorcow** [comment]
I've run the behat tests locally. They all pass. :)

**Pull request merged**
