### PR TITLE
DOC CMS 3.x file migration section about versioned files

### PR DESCRIPTION
**Pull request by dnsl48**
The original source is here: https://docs.silverstripe.org/en/4/changelogs/4.3.6/#if-you-were-using-the-versionedfiles-on-your-3-x-site

### CODE REVIEW

**Comment by emteknetnz** [comment]
Looks great

Probably makes sense to target this to 4.5 though?

**Comment by dnsl48** [comment]
Well, the docs are generated from `4`, so this should be enough. Although if we really want to go with all the merging up, then perhaps should be `4.3`?

**Comment by emteknetnz** [comment]
Well whatever you think makes the most sense.  I guess it depends if we're likely to do patch releases on any of the existing minor branches in the medium term, might be nice to have module docs match any official looking docs we have around

**Comment by dnsl48** [comment]
retargeted to `4.3`

**Comment by emteknetnz** [comment]
LGTM

**Pull request merged**
