### PR TITLE
FIX extraClass() method to match parent method

### PR DESCRIPTION
**Pull request by xini**
rebased against 3, see #4480

### CODE REVIEW

**Comment by dhensby** [comment]
thanks

**Comment by tractorcow** [comment]
There's a small regression in this; See https://github.com/silverstripe/silverstripe-framework/commit/5470f23e2f46e95c97ab00dc891ffbda6283f035#commitcomment-15274570

**Comment by dhensby** [comment]
You fix a bug and you find instances that relied on that bug.... Sigh.

**Comment by tractorcow** [comment]
Logged at https://github.com/silverstripe/silverstripe-framework/issues/4895

**Pull request merged**
