### PR TITLE
Fix i18nTextCollector merge does not work with vendor modules

### PR DESCRIPTION
**Pull request by bimthebam**
While running the i18nTextCollector against a vendor-module - with merge option enabled - it won't merge with existing files due to a wrong module-path determination.

i18nTextCollector should use the ModuleLoader to determine the correct module-path.

### CODE REVIEW

**Comment by dhensby** [comment]
This looks reasonable - is there any existing test coverage that could be modified so that this regression could not happen again (without a test failing)?

**Comment by michalkleiner** [comment]
Is this somehow related to https://github.com/silverstripe/silverstripe-framework/pull/10179?

**Comment by emteknetnz** [comment]
Related easy PR to merge https://github.com/silverstripe/silverstripe-asset-admin/pull/1249

**Review by emteknetnz — APPROVED** [review]
Have tested locally, this works as intended

Note: the code when this PR was originally raised lacked `/vendor/` in $masterFile being defined.  This was since fixed [here](https://github.com/silverstripe/silverstripe-framework/pull/10179/files).

This PR is functionally the same as the existing code, just now it's less hardcoded

**Pull request merged**
