### PR TITLE
Allow use of display names with SwiftMailer

### PR DESCRIPTION
**Pull request by martinduparc**
The syntax to allow display names with SwiftMailer is as follow:
`->setFrom(['john@doe.com' => 'John Doe'])`

Just like you set the `Email.admin_email`, you can set the default sender display name through the `Email.admin_email_displayname` configuration setting.

Refs:
- https://swiftmailer.symfony.com/docs/introduction.html#basic-usage
- https://docs.silverstripe.org/en/4/developer_guides/email/#administrator-emails

Thanks for contributing, you're awesome! :star:
Please describe expected and observed behaviour, and what you're fixing.
For visual fixes, please include tested browsers and screenshots.
Search for related existing issues and link to them if possible.
Please read https://docs.silverstripe.org/en/contributing/code/

### CODE REVIEW

**Comment by dhensby** [comment]
Couldn't one just set the `Email.admin_email` option to be an associative array? Perhaps a docs update would be more appropriate?

eg:

```yml
Email:
  admin_email:
    me@example.com: SilverStripe Admin
```

**Comment by dhensby** [comment]
there are also linting issues in this PR, please see the travis failure

**Comment by martinduparc** [comment]
Hi Daniel,

Definitely, whatever makes the more sense to the SS core team. I will go ahead and make that change.

**Comment by dhensby** [comment]
Less code to maintain is best IMO and if we can achieve it like this, that'd be great.

Can you update the docblock for the config option to say it can be an array and also update the email docs if there's somewhere appropriate to add this?

**Comment by martinduparc** [comment]
Thanks for the feedback. I've made the changes

**Comment by martinduparc** [comment]
Hi @maxime-rainville Feel free to squash-and-merge. Thanks!

**Pull request merged**
