### PR TITLE
OptionsetField_holder.ss should use $HolderID for div id attr

### LINKED ISSUE #5786: OptionsetField_holder.ss still uses $Name for id attribute
I suspect [OptionsetField_holder.ss](https://github.com/silverstripe/silverstripe-framework/blob/master/templates/forms/OptionsetField_holder.ss) should be updated to use the new `$HolderID` value rather than  `$Name` for the html id attribute, as in [FormField_holder.ss](https://github.com/silverstripe/silverstripe-framework/blob/master/templates/forms/FormField_holder.ss)

### PR DESCRIPTION
**Pull request by sheadawson**
Fixes #5786

### CODE REVIEW

**Comment by dhensby** [comment]
Legit - now, is this a bug fix that could be applied in a 3 release?

**Comment by dhensby** [comment]
Looks like the behat tests need updating :/

**Comment by tractorcow** [comment]
Please rebase; this bug has been fixed.

**Comment by dhensby** [comment]
> Please rebase; this bug has been fixed.

how can it have been if this is merging cleanly?

**Comment by tractorcow** [comment]
Because merges are only non-clean if they modify conflicting files?

**Comment by tractorcow** [comment]
Nope, CI restarting only runs on the old merged commit. https://github.com/silverstripe/silverstripe-framework/commit/67a97ff0270b86b1e5ea1b6de2a785c688791bcf.

It won't test against the merged (this + current master) until a rebase.

**Comment by tractorcow** [comment]
I've made this change in the bootstrap forms update over at https://github.com/silverstripe/silverstripe-framework/pull/5826 too, to help get this over the line.

**Comment by sminnee** [comment]
Closing this as #5826 will address this.

**Pull request closed without merging**
