### PR TITLE
Fixing undeclared constant issue

### PR DESCRIPTION
**Pull request by dhensby**
This needs merging up

### CODE REVIEW

**Comment by dhensby** [comment]
@tractorcow this is a pretty big deal

**Comment by tractorcow** [comment]
I've merged into each of the RC branches and are making the 3 rcs now.

**Comment by tractorcow** [comment]
`FIX` or `BUG` please in future...

**Comment by dhensby** [comment]
Sorry. Thanks.

**Comment by tractorcow** [comment]
I've just noticed the changelog generator is missing quite a few changes; More that I'd anticipated. Probably need a more inclusive filtering pattern...

**Comment by chillu** [comment]
Argh my bad, sorry about that guys!

**Comment by tractorcow** [comment]
My bad too... I was the one who peer reviewed them!

**Pull request merged**
