### PR TITLE
API Extension hook for email default from

### PR DESCRIPTION
**Pull request by emteknetnz**
Follow up for https://github.com/silverstripe/silverstripe-framework/issues/10217

### CODE REVIEW

**Comment by GuySartorelli** [comment]
Would it be worth documenting this in [docs/en/02_Developer_Guides/10_Email/index.md](https://github.com/silverstripe/silverstripe-framework/blob/4/docs/en/02_Developer_Guides/10_Email/index.md#administrator-emails)?

**Review by michalkleiner — APPROVED** [review]

**Comment by emteknetnz** [comment]
Unit test failing is fixed here (4.10) instead - https://github.com/silverstripe/silverstripe-framework/pull/10252

**Comment by emteknetnz** [comment]
> Would it be worth documenting this

I don't think so, what you really should be doing is setting the email via the `SilverStripe\Control\Email::admin_email` config, and this is already documented

There's a lot of undocumented extension hooks through the codebase, so not documenting this is consistent

**Review by michalkleiner — APPROVED** [review]
Happy with the unit test issue being addressed separately in a patch.

**Pull request merged**
