### PR TITLE
Add a Gitter chat badge to README.md

### PR DESCRIPTION
**Pull request by gitter-badger**
### silverstripe/silverstripe-framework now has a Chat Room on Gitter

@sminnee has just created a chat room. You can visit it here: [https://gitter.im/silverstripe/silverstripe-framework](https://gitter.im/silverstripe/silverstripe-framework?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&content=body_link).

This pull-request adds this badge to your README.md:

[Gitter](https://gitter.im/silverstripe/silverstripe-framework?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=body_badge)

If my aim is a little off, please [let me know](https://github.com/gitterHQ/readme-badger/issues).

Happy chatting.

PS: [Click here](https://gitter.im/settings/badger/opt-out) if you would prefer not to receive automatic pull-requests from Gitter in future.

### CODE REVIEW

**Comment by sminnee** [comment]
Wow, that's creepy. I was just testing it out!

**Comment by dhensby** [comment]
creepy indeed

**Comment by dhensby** [comment]
if @gitter-badger breaks the build, I'm going to rage

**Comment by dhensby** [comment]
we aren't moving to gitter yet, and if we do, we'll likely promote a generic channel

**Comment by sminnee** [comment]
For anyone who comes across this: we haven't made any decision to advocate Gitter as a comms channel, and if we do, we'll discuss it on http://groups.google.com/group/silverstripe-dev first. Sorry if I caused any alarm with my exploration! :-)

**Pull request closed without merging**
