### PR TITLE
search term highlighting without altering case (fixes #1400)

### LINKED ISSUE #1400: [2011-04-19] Text.ContextSummary alters case
created by: dave@room9.co.nz
created at: 2011-04-19
original ticket: http://open.silverstripe.org/ticket/6605

---

Text.ContextSummary changes case of the original text. I.e. A search for "John Key" will highlight as "john key". This is a problem with proper names and brand names.

The search term should highlighted without changing the inner text.

### PR DESCRIPTION
**Pull request by volkerloew**
using preg_replace instead of str_ireplace

### CODE REVIEW

**Comment by dhensby** [comment]
cc @tractorcow

**Comment by tractorcow** [comment]
Could you please add a unit test which shows how the case remains unaltered?

**Comment by tractorcow** [comment]
E.g.

Text: `Here is some Testing text`
Search: `testing`
Expected: `Here is some <span class="highlight">Testing</span> text`

**Comment by volkerloew** [comment]
Sorry, missed that initially. I updated an existing test to reflect the change.

**Pull request merged**
