### PR TITLE
Add extension hook to Member isLockedOut() and registerSuccessfulLogin()

### PR DESCRIPTION
**Pull request by HARVS1789UK**
Allow developers to tie in to some of the Member login methods which relate to the 'soft' lockout (i.e. time based) functionality so that the lockout logic can be customised in extensions of the Member class

### CODE REVIEW

**Comment by robbieaverill** [comment]
Hey @HARVS1789UK - I'd suggest you rename the extension hooks to have an `update*` or `onAfter|onBefore` prefix to match the majority of the hooks in the framework already:

* `updateIsLockedOut`
* `onAfterRegisterSuccessfulLogin`

**Comment by tractorcow** [comment]
As @robbieaverill suggested, those renames would be great. :)

Can you PR to the 3 branch, since this is a new feature and needs to go onto the feature branch.

**Comment by HARVS1789UK** [comment]
@robbieaverill - Do my updates satisfy your request?

@tractorcow - I think I have changed the PR to be against the 3.0 branch as you requested, is that correct? It seems to have caused many more conflicts?

**Comment by dhensby** [comment]
@HARVS1789UK looks like this is against the wrong branch and your branch needs re-basing

**Comment by kinglozzer** [comment]
@HARVS1789UK It needs to be submitted against the `3` branch, not `3.0` 😄

**Comment by dhensby** [comment]
@HARVS1789UK OK - you're going to need to open a new PR because you've PR-ed from your own 3.5 branch rather than a branch just for this PR.

Please create a new branch in your repo (eg: pulls/login-hooks) from our `3` branch. Then apply your changes and open a PR against `3`. thanks

**Comment by HARVS1789UK** [comment]
Hopefully this PR - https://github.com/silverstripe/silverstripe-framework/pull/6762 - Is now correct

**Pull request closed without merging**
