### PR TITLE
Update GitHub pull request template to include a checklist for contribution pre-requisites

### PR DESCRIPTION
**Pull request by robbieaverill**
For wider discussion see here: https://forum.silverstripe.org/t/improving-the-way-we-maintain-the-silverstripe-open-source-ecosystem/859

When we finalise this template it'll become part of a wider automation process: https://github.com/silverstripe/silverstripe-framework/issues/8343

## Template demo:

Thanks for contributing to SilverStripe! To help the maintainers of this repository review your changes,
please ensure you've completed the following pre-requisite checklist. Please also check any that aren't
relevant to your change:

- [ ] Code changes conform to the [coding standards](https://docs.silverstripe.org/en/contributing/coding_conventions/)
- [ ] If necessary, relevant documentation has been updated
- [ ] New [automated tests](https://docs.silverstripe.org/en/developer_guides/testing/) have been written, or existing tests updated
- [ ] Commits are [prefixed with the appropriate tag](https://docs.silverstripe.org/en/4/contributing/code/#commit-messages)
- [ ] You agree to SilverStripe Limited releasing this code under the [BSD license](https://www.silverstripe.org/software/bsd-license/)

If this pull request resolves an open issue, please [mention it](https://help.github.com/articles/closing-issues-using-keywords/) in the description of this pull request.

For more information on how to contribute to SilverStripe modules, please read [the contributing guide](https://docs.silverstripe.org/en/contributing/code/).

### CODE REVIEW

**Comment by dhensby** [comment]
@robbieaverill we've discussed previously PR / issue templates and the general consensus was that these templates should be solving a known problem, rather than pre-emptive as otherwise we risk putting off contributors by putting a list of things they need to do in their way before contributing something.

Do we find that we are inundated with low quality PRs? Wil 95% of contributions actually ignore this template anyway? Will there be any process around how we handle PRs that don't complete all the prerequisites? These are just some of the questions we need to consider when thinking about the value of a PR template.

see previous discussion (https://github.com/silverstripe/silverstripe-framework/pull/7481)

**Comment by robbieaverill** [comment]
>Do we find that we are inundated with low quality PRs?

The common traits I see are:

* PRs being made from a core branch
* Commits not being prefixed with our (quite specific) cow tags
* PRs made against the wrong branches
* Tests not being updated or added with changes made

>Wil 95% of contributions actually ignore this template anyway?

Perhaps, but I guess having a checklist will show whether a contributor has acknowledged and completed the steps we ask them to when they contribute something from a glance at the Pull Requests tab.

TBH these templates would slow the core teams down a bit - I usually use `hub` to create pull requests and remove all of the existing PR template in framework anyway, so it'd take a bit of adjustment for me to get used to this for example.

>Will there be any process around how we handle PRs that don't complete all the prerequisites?

I think this is something we need to iron out and document. In terms of "core branch PRs" we can't do much. We can retarget and rebase PRs that are made against the wrong branches, as well as amend the commit messages to include cow prefixes. These are all relatively quick for us to do, and may be actions that require internal knowledge at times to correctly achieve.

Adding tests: it's something we (the core team or SilverStripe Ltd product teams) _could_ do but it's unlikely to be common. It's more likely that we'd post a comment encouraging the contributor to write some tests or update the existing ones.

---

As part of #8343 we're going to end up with generic issue and PR templates that will get pushed out to all commercially supported modules, so it'd be great to ensure that what we have is effective before we do this. It can always be done again easily enough of course.

FWIW I think the current issue template in framework is perfect, and it seems to be widely used by contributors in framework.

**Comment by wernerkrauss** [comment]
> Adding tests: it's something we (the core team or SilverStripe Ltd product teams) could do but it's unlikely to be common. It's more likely that we'd post a comment encouraging the contributor to write some tests or update the existing ones.

My first PR never got a test from me, cause that method was untested at that time and I didn't have the knowledge of tests. Afaik that PR was closed without being merged. Nowadays I hope to provide more useful commits, but the last commit to framework broke a test in admin that relied on the method I refactored. How should I have known?

> PRs made against the wrong branches

Is that documented anywhere? If yes, I didn't find it. I had to ask Robbie or Loz on slack to tell me which branch to use. Hopefully I now understood that.

While working in a project and "fix something" I normally just branch off the installed version. Maybe that's too lazy from me?

**Comment by robbieaverill** [comment]
@wernerkrauss 

>the last commit to framework broke a test in admin that relied on the method I refactored. How should I have known?

You won't really, without running a full integration test suite (like the [CWP kitchen sink recipe](https://travis-ci.org/silverstripe/cwp-recipe-kitchen-sink/builds/453200703)). I guess provided syntax is fine and API changes are mitigated, changes should usually be safe if the module has existing tests that cover the code.

>Is that documented anywhere? If yes, I didn't find it. I had to ask Robbie or Loz on slack to tell me which branch to use. Hopefully I now understood that.

We have a little bit [here](https://docs.silverstripe.org/en/4/contributing/code/#picking-the-right-version). This could be expanded a little to clarify things. Also see [the accepted RFC: reduce use of minor release branches](https://github.com/silverstripe/silverstripe-framework/issues/8189), which would indicate that we're moving towards suggesting people contribute all changes to the default next minor release branch (`4` at the moment) unless they're breaking changes.

In some cases I suppose the core team could then re-target patch changes at minor releases if they need to be releases sooner in an existing release line.

>While working in a project and "fix something" I normally just branch off the installed version. Maybe that's too lazy from me?

I do that too, I think it's a good way to do it 😆sometimes I think "should I fix this higher up" but usually I just target the current minor release branch.

It's common for people to do this as well but just add a commit to their `4.2` branch (for example) on GitHub directly, which is the "using a core branch" problem we're also trying to mitigate.

**Comment by ScopeyNZ** [comment]
The only issue I have here is that we're talking to the PR opener. I wonder if there's a way to change the wording to have it make sense if provided they don't edit it. Right now I'm going to delete the whole opening paragraph every time I open a PR. Ideally I'll just leave it verbatim and tick the boxes.

**Comment by maxime-rainville** [comment]
We discussed this quite a bit at one of our [Architecture catch up](https://silverstripe.atlassian.net/wiki/spaces/OS/pages/743735371/2019-02-12+Architecture+Catchup+Meeting+Notes).

>     Saved replies feature in GitHub, per-user config - we have a list of pre-existing ones stored in Confluence
> 
>     Both raiser and reviewer are responsible for the checklist
> 
>     Helps to improve transparency of our standards and process
> 
>     PR Template vs. Saved Reply
> 
>         We’ll put the Merge Checklist in the latter, so the reviewer can determine what's useful on a case-by-case basis
> 
>         Plus most contributors don't look at the PR template (but we can still improve it to try and combat that)
> 
>     What's the most important thing to expose to contributors in the PR template?
> 
>         The link to contributing docs
> 
>         Guy to do a write-up on using the Hub CLI to raise PRs
> 
>         Most common problem is pointing the PR at the wrong branch
> 
>         Perhaps 5 simple bullet points in the template with a link
> 
>     Focussed variants of the checklist for PRs relating to React code
> 
>     We might want to avoid purely linking to external resources as when they change it won't be obvious?
> 
>     Hard sometimes to understand what a PR's purpose is (missing description / bad commit message / no linked issue)
> 
>     What gets missed most often?
> 
>         Related documentation changes
> 
>         Browser compatibility (harder and harder to test in IE 11 for example)
> 
>         Incorrect branch targeting (less common)
> 
>     Can we achieve sufficient improvements with less than 10 checklist items?
> 
>     Let's try and get the Saved Replies into 'beta' and iterate
> 
>     Once they're in a good place, shift them out of Confluence to make them public
> 
>     We need to automate rolling out new PR templates across our repos

**Comment by dnsl48** [comment]
> PR Template vs. Saved Reply

I've done some research around Saved Replies, and unfortunately, GitHub only supports personal saved replies. There's also no appropriate APIs to automate their sync from a single source of truth.

Related: https://github.com/isaacs/github/issues/670

**Comment by unclecheese** [comment]
@robbieaverill Please rebase and retarget against 4.2 if you're still keen to get this merged.

**Comment by robbieaverill** [comment]
I'm still keen, but I don't think we had a consensus on the best way forward in the core team

**Pull request closed without merging**
