### PR TITLE
fixing issue where 'ss-tabs-force-active' wasn't actually working

### PR DESCRIPTION
**Pull request by pitchandtone**
and didn't account for multiple tabs having it set

### CODE REVIEW

**Comment by pitchandtone** [comment]
Particularly useful for advanced workflow to trigger the workflow tab if it's present.

**Comment by pitchandtone** [comment]
Usecase:
Page has many products (or any has many relationship)

1) Open page 1
2) Open page 1's product
3) Open second tab with page 2
4) Go back to first tab
5) Hit save.

Currently you get redirected. Or if you use versioned girdfield the product you were editing is now owned by page 2 (wha?). See https://github.com/icecaster/silverstripe-versioned-gridfield/issues/18

The reason is that it loads the currentPage from session rather than request and session is not distinct to tabs obviously.

This fix means that the page that it currently belongs to is sent in the POST and picked up.

**Comment by dhensby** [comment]
@jonom this looks important. Thoughts?

**Comment by jonom** [comment]
Sorry this bit of JS isn't familiar to me and I need to spend the rest of my Sunday on my tax return... sigh

**Comment by tractorcow** [comment]
Tested it; Seems to not break anything!

**Pull request merged**
