### PR TITLE
Pulls/4/remove jsmin

### PR DESCRIPTION
**Pull request by unclecheese**

### CODE REVIEW

**Comment by tractorcow** [comment]
Please remove the actual JSMinifier class too.

**Comment by unclecheese** [comment]
@chillu That makes sense, but minification lends itself nicely to a single injectable service. If we're just talking about "processing," it seems to me that the API needs to allow for multiple services to be injected.

```
SilverStripe\Core\Injector\Injector:
  SilverStripe\View\Requirements_Backend:
    properties:
      processors:
        - %$MinificationService
        - %$VariableReplacementService
        - ....
```

Or we could keep it simple and if the user wants multiple processors, you just chuck them all in one processor service, but that limits configurability.

**Comment by tractorcow** [comment]
Given we are removing and making a core function injectable, I don't think it's necessary to rename the service.

**Comment by chillu** [comment]
It seems weird that we creating new APIs for an approach we want to phase out. But I take your point about not over-optimizing this at the moment with creating a new processor API. How do you feel about marking this API as deprecated for 5.x?

**Comment by tractorcow** [comment]
> It seems weird that we creating new APIs for an approach we want to phase out. But I take your point about not over-optimizing this at the moment with creating a new processor API. How do you feel about marking this API as deprecated for 5.x?


Great idea. @unclecheese can you action this?

**Comment by unclecheese** [comment]
Sure thing.

**Pull request merged**
