### PR TITLE
Symfony ExpressionLanguage for Injector spec syntax integration

### PR DESCRIPTION
**Pull request by PawelSuwinski**
Hi

This is draft of [Symfony ExpressionLanguage](https://symfony.com/doc/current/components/expression_language.html) integration for Injector yaml syntax, similar to symfony DI container. Practically it is done, but as a beta version, no extra code comments, no test, no docs, just to show the idea.

I use such extension a lot. It takes Injector config to the next level towards low code solutions, a lot can be done with this in configuration space, especially in conjunction with pipe operator. 

Let me know if there is any interest in such an extension of Injector.  I will be for a while around silverstripe project and can complete this with unit tests, docs and apply any review suggestions.

Some simple examples of usage (could be done a lot more with that):

```yaml
SilverStripe\Core\Injector\Injector:

  # log file name based on environment
  # default log level is INFO overridable by LOGGER_LOG_LEVEL var
  Monolog\Handler\StreamHandler:
    constructor:
      - '@=constant("BASE_PATH") ~ "/logs/" ~ srv("SilverStripe\\Control\\Director").get_environment_type() ~ ".log"'
      - '@=env("LOGGER_LOG_LEVEL") ?: constant("Monolog\\Logger::INFO")'
 Psr\Log\LoggerInterface:
   calls:
      - [ pushHandler, [ '%$Monolog\Handler\StreamHandler' ] ]


  
  # HTTP Middleware to log request ended with error response. 
  ErrorResponseLoggingMiddleware:
    class:  SilverStripe\Control\Middleware\ExpressionBasedMiddleware
    properties:
      resExp: 'res.isError() &&  logger.warning("status " ~ res.getStatusCode() ~ ", user " ~ (sec.getCurrentUser() ? sec.getCurrentUser().Email))'
    # expression context vars given by constructor just to keep expression short
    # notice: context vars are resolved during Director instantiation, expression is evaluated at runtime
    constructor: 
      -
        # logger with security channel set
        logger: '@=srv("Psr\\Log\\LoggerInterface").withName("security")'
        # shortcut to security service
        sec: '%$SilverStripe\Security\Security'

  SilverStripe\Control\Director:
    properties:
      Middlewares:
        - '%$ErrorResponseLoggingMiddleware'
```

### CODE REVIEW

**Comment by GuySartorelli** [comment]
ping @silverstripe/core-team 
Seems like an RFC more than a PR

**Comment by michalkleiner** [comment]
I personally prefer a bit more code and verbosity over super convoluted config that might be hard to read/understand, but perhaps that's just me being too oldschool.

**Comment by dhensby** [comment]
I'm definitely up for more standardisation of this kind of thing, and if Symfony has a robust method to do it, then why not make use of it. I'd expect this needs to come in v5, if it is accepted.

I'm not sure about using a middleware to interpret the config - shouldn't this just be baked into the injector instead?

**Comment by GuySartorelli** [comment]
It seems like there's going to be no further activity on this pull request, so we’ve closed it for now.

If someone still thinks this is worth exploring please open a new issue and we can discuss it there.

**Pull request closed without merging**
