### PR TITLE
FIX Emulate Prepares now will set to false explicitly

### PR DESCRIPTION
**Pull request by dhensby**
Emulate prepares config is ignored if it's false (which it looks like we want it to be).

I assume the expectation was the default is false and we should only set it if it's true, but this appears to be incorrect and the default is true (in PHP 5.4 at least).

### CODE REVIEW

**Comment by tractorcow** [comment]
You've un-ravelled the ball of yarn. The worms can is open. Do you want to fix all these issues too? :P

It might be better to just leave it as is. :P

**Comment by dhensby** [comment]
Leave it broken or fix it? I choose FIX IT!!! but I'm just not sure what on earth is causing this error :/

**Comment by tractorcow** [comment]
Can you fix it so that PDO::MYSQL_ATTR_USE_BUFFERED_QUERY is automatically set depending on the value of is_emulate_prepare() ?

**Comment by dhensby** [comment]
@tractorcow I guess - is this connector solely for the use of MySQL

**Comment by dhensby** [comment]
Looks like no improvement :/

**Comment by tractorcow** [comment]
No it's used for lots of connectors; Postgres / sqlite etc should all have pdo support.

**Pull request closed without merging**
