### PR TITLE
Update jquery.js reference

### PR DESCRIPTION
**Pull request by thezenmonkey**
jquery is no longer included at the path specified. Shoudl be in the admin directory

### CODE REVIEW

**Comment by baukezwaan** [comment]
I think it also needs to be fixed in [config-form.html](https://github.com/silverstripe/silverstripe-framework/blob/master/Dev/Install/config-form.html#L9)
This way the js-errors on the install.php page are also fixed...

**Comment by dhensby** [comment]
We're looking at pulling admin out into its own module soon so this isn't a long term fix. Better to use Google's CDN?

**Comment by thezenmonkey** [comment]
Which version of jquery shoud be we be fulling from the CDN?

**Comment by dhensby** [comment]
[simple uses 1.7.2](https://github.com/silverstripe-themes/silverstripe-simple/pull/42/files), so probably that...

**Comment by dhensby** [comment]
thanks

**Comment by dhensby** [comment]
@baukezwaan sorry, I missed your comment some how! Would you mind opening a PR to fix config-form.html?

**Pull request merged**
