### PR TITLE
Total Items of a Paginated List

### PR DESCRIPTION
**Pull request by marcokernler**
Just added support for displaying the number of total items contained in a Paginated List across templates

### CODE REVIEW

**Comment by kinglozzer** [comment]
@marcokernler Doesn’t `$TotalItems` already work? Using `$TotalItems` should automatically call `getTotalItems()`

**Comment by kinglozzer** [comment]
Oh, I see, you do have to call `$getTotalItems` in templates. Looks like `SS_ListDecorator::TotalItems()` is wrong - it should call `$this->list->count()` instead. I think it would be better to fix this there.

Do you want to have a go at that instead @marcokernler?

**Comment by marcokernler** [comment]
Hi @kinglozzer, just tried your suggestion with calling $this->list->count() within SS_ListDecorator::TotalItems(), but using $Results.TotalItems will only return the number of items for the current page...

Any other suggestions?

**Comment by kinglozzer** [comment]
@marcokernler Hmm, that’s not the behaviour I see if I make that change and the use `$PaginatedList.TotalItems`... how about `$PaginatedList.Count`? That does the same thing

**Comment by marcokernler** [comment]
@kinglozzer Just installed a new SilverStripe instance (3.1.15) and enabled the Site Search. To display the total number of items, i added  `$Results.TotalItems` to the Page_results.ss template right beneath `<% if $Results %>`

Here are the results of my tests:

* Calling `$Results.TotalItems` results in the error: Object->__call(): the method 'totalitems' does not exist on 'ArrayList'.
* Changing `ListDecorator::TotalItems()` from `return $this->list->TotalItems()` to `return $this->list->count()`removes the error, but just will return the number of items per page.
* Calling `$Results.Count`also just return the number of items per page.

Maybe it's because the search does return an ArrayList instead of a PaginatedList?

**Comment by kinglozzer** [comment]
Ah, the page search functionality does use `ArrayList`, which is why `$Results.Count` doesn’t work (and why the fix I suggested won’t work too). However, the search form _does_ store the total item count using `setTotalItems()` (looks like this exact scenario is what that method is for!) - so I’ve come full circle and decided that this is the correct fix after all!

Thanks for bearing with me @marcokernler :stuck_out_tongue_closed_eyes:

**Pull request merged**
