### PR TITLE
Add FirstPage() and LastPage() to PaginatedList

### PR DESCRIPTION
**Pull request by kinglozzer**
Currently if you want to check if the current page is the first page in a template, you have to do 

```
<% if not $NotFirstPage %>
```

🤮

### CODE REVIEW

**Review by michalkleiner — CHANGES_REQUESTED** [review]
@kinglozzer can you please update the other methods to use a positive logic approach?

**Review by michalkleiner — CHANGES_REQUESTED** [review]
Thanks @kinglozzer, the changes look good. Can you please rebase on top of latest `4` to make Travis happy as well? It's now failing because of https://github.com/silverstripe/silverstripe-framework/pull/10113 being merged yesterday.

**Comment by kinglozzer** [comment]
Rebased again, tests are green now

**Review by michalkleiner — APPROVED** [review]
Wonderful, thank you for the contribution!

**Pull request merged**
