### PR TITLE
Fix for APCu cache otherwise you get 'Cache key must be string, "bool…

### PR DESCRIPTION
**Pull request by oilee80**
…ean" given'

Also corrects parameter variable name

### CODE REVIEW

**Comment by dhensby** [comment]
thanks

**Comment by tungdt-90** [comment]
Hi,

Can you merge this commit for Silverstripe 4.0.0-alpha5 ?

I'm testing the Alpha version, then I got this issue. And this commit fixed it.

**Comment by dhensby** [comment]
@tungdt-90 once can't merge fixes into tags as tags are static and don't change.

If you want this fix you'll need to run 4.0.x-dev or wait for the next release.

**Comment by tungdt-90** [comment]
@dhensby Thanks for your answer, actually i'm not really in such a hurry, so i guess i can wait for a proper release.

But at least, i can confirm that this fix works for SS 4.

**Pull request merged**
