### PR TITLE
Docs for personal data usage in core

### PR DESCRIPTION
**Pull request by chillu**
See https://github.com/silverstripe/silverstripe-framework/issues/7791

### CODE REVIEW

**Comment by chillu** [comment]
> I think making it more clear that login attempts are recorded if max_login_attempts is configured would be good.

I don't think that's the case, check `MemberAuthenticator->recordLoginAttempt()` which is the only place in core that creates a `LoginAttempt` record: https://github.com/silverstripe/silverstripe-framework/blob/4/src/Security/MemberAuthenticator/MemberAuthenticator.php#L167. It returns when `login_recording` isn't enabled.

**Comment by chillu** [comment]
@dhensby Happy to merge? Or do you disagree with my last comment?

**Comment by dhensby** [comment]
> @dhensby Happy to merge? Or do you disagree with my last comment?

Let's give this a few days ;)

**Comment by chillu** [comment]
OK, given this a few days ;)

**Comment by chillu** [comment]
Followed up with a correction at https://github.com/silverstripe/silverstripe-framework/pull/8079

**Pull request merged**
