### PR TITLE
DEP Set minimum symfony version to 3.4

### PR DESCRIPTION
**Pull request by emteknetnz**
Issue https://github.com/silverstripeltd/product-issues/issues/514

Travis issue
https://app.travis-ci.com/github/silverstripe/recipe-reporting-tools/jobs/555429636#L1234

Can replicate locally using symfony/yaml 3.3.18. Resolves with using 3.4.47

Related PR https://github.com/silverstripe/silverstripe-config/pull/53

### CODE REVIEW

**Review by maxime-rainville — CHANGES_REQUESTED** [review]
Not a big fan of changing dependency requirement in a patch release. Can you clarify why those change are needed? Is it just that this never worked in symfony <= 3.3 ?

**Comment by emteknetnz** [comment]
They did used to work in the past, just there's a specific bug that comes up now in php8 with pre 3.4 symfony

**Comment by emteknetnz** [comment]
I've raised a PR to clarify which branch to target here - https://github.com/silverstripe/silverstripe-framework/pull/10216 tl;dr aim to target a minor release if possible, however ok to target patch if it's to fix a bug.  Since this is fixing a bug I think this should remain a patch release.

**Review by maxime-rainville — APPROVED** [review]
Me happy.

**Pull request merged**
