### PR TITLE
FIX for #4095, TinyMCE not able to modify props of embed media (bug 1) and invalid HTML inserted (bug 2)

### PR DESCRIPTION
**Pull request by patricknelson**
PR for #4095

### CODE REVIEW

**Comment by patricknelson** [comment]
Side FYI: I removed a line that causing a separate bug, i.e. it was preventing the buttons script `editor_plugin_src.js` from being able to find the embed and not replacing the `img` tag with the appropriate `[embed]` short code. It was [from this line](https://github.com/patricknelson/silverstripe-framework/commit/0ba711846662f7136ae10df22e041eafbcee8b25#diff-f8efe467c47853bda85e3c63cce3b072R1367) from the old version of the commit (applying the same attribs twice, overriding the required CSS classes). Sorry about that!

**Comment by dhensby** [comment]
Hi @patricknelson - sorry these have been overlooked for so long - if this patch fixes the bug you reported we should get it in.

However it'll need to be against 3.4 - I'm going to change the target branch but would you mind rebasing and confirming it still solves the issue?

**Comment by patricknelson** [comment]
Isn't this still an issue or has this been fixed by some other PR @dhensby? I still have a hack in the core code of the CMS to workaround this.

**Comment by dhensby** [comment]
@patricknelson this has been automatically closed as the 3.4 branch has been retired. It'll need re-opening on 3.5 or 3...

**Comment by patricknelson** [comment]
Alright, cool thank you! Also: It must have been a while since I last tried doing this, I'm glad to see it's now finally possible: https://github.com/blog/2224-change-the-base-branch-of-a-pull-request (long time coming on that feature, sheesh)

**Pull request merged**
