### PR TITLE
FIX: Initial write with writeToStage()

### LINKED ISSUE #3695: Can't create new draft objects with writeToStage()
writeToStage() calls forceChange() which causes newly created objects to be written with Version=0 instead of Version=1. I don't know exactly why it happens there but I can confirm that's the source. This happens with SiteTree objects and I assume other versioned objects too.

To reproduce try:
```php
$s = new SiteTree();
$s->Title = 'Test';
$s->writeToStage('Stage');
```
Should show up in the CMS with status of 'Deleted'.

Tracking down this bug almost killed me, but on the bright side I know a lot more about versioning now. Hopeful patch on the way.

Related: 
* http://www.silverstripe.org/community/forums/general-questions/show/18017
* http://stackoverflow.com/questions/21671943/silverstripe-3-1-page-creating-publishing-from-the-frontend

### PR DESCRIPTION
**Pull request by jonom**
Fixes #3695

I'm not sure if checking whether the object has been written yet should be done here or in the writeToStage() function. Seek feedback.

### CODE REVIEW

**Comment by dhensby** [comment]
This change makes sense to me in that an item with no ID will have all it's field values written whether they are explicitly changed or not

**Comment by tractorcow** [comment]
We would need to write a test case to prove this works.

**Comment by dhensby** [comment]
> We would need to write a test case to prove this works.

What exactly are we proving, that forceChange marks new fields as changed or that a write on a new object which has had "forceChange" run writes all the fields?

Or.. am I being dense and really we need to check that this doesn't break "writeToStage" for new objects?

**Comment by tractorcow** [comment]
I mean a test case which replicates the issue found in #3695 to prove that this fixes the issue. :D

**Comment by jonom** [comment]
Alternative fix provided in https://github.com/silverstripe/silverstripe-framework/pull/3666

**Pull request closed without merging**
