### PR TITLE
NEW Allow setting of unlimited row counts on GridFieldPaginator

### PR DESCRIPTION
**Pull request by dhensby**
This change allows a dev to use `->setItemsPerPage(0)` to create a GridField with unlimited row count.

### CODE REVIEW

**Comment by tractorcow** [comment]
Any chance of a unit test?

**Comment by robbieaverill** [comment]
Just my opinion:

* Setting a null value for a limit can imply a reset to default rather than unlimited
* Perhaps `-1` would be better

**Comment by sminnee** [comment]
It should match the semantics of `DataList::limit()`. The semantics of `DataList::limit()` are really badly documented but I think a limit of `0` specifies unlimited.

**Comment by robbieaverill** [comment]
>It should match the semantics of `DataList::limit()`

Good call.

>...but I think a limit of `0` specifies unlimited.

But zero is a number too! :)

**Comment by tractorcow** [comment]
I wouldn't even mind an unlimit() method (in addition) to explicitly remove any existing limit.

**Comment by sminnee** [comment]
There's a solution that already exists. Robbie doesn't like it, but I don't think that mandates a change.

When I said "It should match the semantics of DataList::limit()" I didn't mean "Let's re-litigate the semantics of DataList::limit()"

**Comment by dhensby** [comment]
The `null` vs `0` discussion is moot because currently the `setItemsPerPage` method doesn't handle an explicit null type and I won't add it to this PR because it's not part of the feature set I'm implementing. 

I'll write a test soon :)

**Comment by dhensby** [comment]
Test added

**Comment by tractorcow** [comment]
It broke. =(

**Comment by dhensby** [comment]
That'll teach me for making up APIs

**Comment by dhensby** [comment]
hopefully that'll fix it...

**Comment by tractorcow** [comment]
It seems to be not. =(

**Comment by dhensby** [comment]
OK - looks like green!

**Comment by tractorcow** [comment]
We need to take care of those.

**Pull request merged**
