### PR TITLE
[#5147] Silence tearDown unlink errors

### PR DESCRIPTION
**Pull request by robbieaverill**
Addresses #5147

### CODE REVIEW

**Comment by tractorcow** [comment]
This seems to be hiding a potentially real error; If you have a permission problem on `/assets` and your tests aren't able to delete files between tests, it's going to affect test results.

Are you by any chance running tests on windows?

**Comment by robbieaverill** [comment]
Hey @tractorcow 

I'm running this in a docker container on OSX El Capitan via dinghy.

It seems odd to me that it can detect that the file exists then not be able to remove it.

Incidentally, I've since been running this through CircleCI and the error has stopped being reported... Perhaps close as cannot reproduce.

Cheers,
Robbie

**Comment by tractorcow** [comment]
I recall often needing to chmod my assets folder on composer install... what were your permissions?

**Comment by robbieaverill** [comment]
Hi @tractorcow 

The original permission was 755. I'm having a little trouble running the suite now after adding the blog module, but will test, chmod to 777 then re-test again and will close this if there's no difference.

Cheers,
Robbie

**Comment by tractorcow** [comment]
Hm, what else could it be... umask maybe?

**Comment by robbieaverill** [comment]
Not sure. Happy to close for now

**Pull request closed without merging**
