### PR TITLE
BUGFIX: Ensure $items isn't null in GridFieldDetailForm_ItemRequest->…

### PR DESCRIPTION
**Pull request by tom890180**
…Breadcrumbs() prior to performing operations on it.

### CODE REVIEW

**Comment by dhensby** [comment]
When would `Breadcrumbs()` return `null`? That sounds like a controller / model is breaking the obligations of the API we have defined

**Comment by tom890180** [comment]
@dhensby 

In AssetAdmin:

https://github.com/silverstripe/silverstripe-asset-admin/blob/1/code/Controller/AssetAdmin.php#L570

**Comment by dhensby** [comment]
ergh - what an absolute facepalm - even the PHPDoc there says it should be returning an `ArrayList`

**Comment by dhensby** [comment]
Right, that's been in AssetAdmin for 3 years now, so it's probably not going to be acceptable to return an empty ArrayList, but that really is a poor showing which now means this kind of code needs to be taken in :(

**Comment by tom890180** [comment]
I changed so $items gets declared as an empty ArrayList if it `Breadcrumbs()` returns null. 

This is because some code is dependent on `updateBreadcrumbs` passing an ArrayList (e.g. https://github.com/tractorcow-farm/silverstripe-fluent/blob/master/src/Extension/FluentLeftAndMainExtension.php#L34)

**Comment by dhensby** [comment]
Yes, that seems a bit more sensible

**Comment by ScopeyNZ** [comment]
Thanks :)

In the future, feel free to base your bugfixes on a patch branch (eg. `4.6`) - as this means we can release a new patch version of that release to ship the fix earlier.

**Pull request merged**
