### PR TITLE
improve scaffolding of Email Field to email field.

### PR DESCRIPTION
**Pull request by sunnysideup**
Right now, when you show Member fields on the front-end, it shows up as a text field and not an e-mail field. This patches fixes this.

### CODE REVIEW

**Comment by sunnysideup** [comment]
can we reopen this for trunk if I make a new patch?

**Comment by sunnysideup** [comment]
```shell
    composer create-project silverstripe/installer ./temp
```

then add the following page type:

```php

<?php
class PageThatCantBeRoot extends Page {

	private static $can_be_root = false;

}
class PageThatCantBeRoot_Controller  extends Page_Controller {


}
```

**Comment by wilr** [comment]
@sunnysideup sure. Closed more due to the risk of this breaking stuff like default admin. Would need to make sure Security::setDefaultAdmin('foo', 'bar') when saved in the CMS doesn't cause a validation error in which case we'd need to include a changelog entry for 3.2

**Comment by tractorcow** [comment]
If you want to re-submit it as a configurable option (turned off by default) that enables the above validation, then it would be fine to submit against the 3 branch (new feature). If it breaks backwards compatibility by default then it needs to go into master, but even then you'd need to describe how you'd work around the default admin issue.

**Comment by dhensby** [comment]
I think the issue here is that the field is called "email" but it's really a "username".

Perhaps this is something that should be changed/updated/added for 4?

**Comment by sunnysideup** [comment]
yes - username vs email has been confusing for a fair number of my clients... I think we should just make it e-mail and only allow usernames that are emails.

**Pull request closed without merging**
