### PR TITLE
Remove versioned cache from core caches

### PR DESCRIPTION
**Pull request by unclecheese**
Resolves: https://github.com/silverstripe/silverstripe-framework/issues/8020#issuecomment-391268602

### CODE REVIEW

**Comment by chillu** [comment]
@unclecheese Can you please fix the merge conflicts, and make sure that you're happy with Damian's work (ready to merge)?

**Comment by tractorcow** [comment]
Looks good to me.

**Comment by tractorcow** [comment]
Behat failure being fixed by another PR.

@unclecheese is this good to go?

**Comment by unclecheese** [comment]
Yes, was waiting for https://github.com/silverstripe/silverstripe-framework/pull/8113 to go green

**Pull request merged**
