### PR TITLE
BUG Fix missing framework/admin/tests

### PR DESCRIPTION
**Pull request by tractorcow**
These tests have been left out for who knows how long

### CODE REVIEW

**Comment by tractorcow** [comment]
It looks like postgres is having a little trouble with LeftAndMainTest::testUpdateTreeNodes

**Comment by tractorcow** [comment]
Marking as impact high, as it resolves currently missing broken tests.

**Comment by dhensby** [comment]
It seems a bit worrying that we have to ANSI quote the sort columns... (why) isn't this done automatically?

**Comment by tractorcow** [comment]
Because it's not a simple column name; It's a sql fragment, and there's no automatic quoting of columns within fragments in framework.

It fails in postgres because it's less resilient to non-standard sql.

**Pull request merged**
