### PR TITLE
DOCS 3.0 : eliminate hard coded numbers in tutorial labels & links

### PR DESCRIPTION
**Pull request by SpiritLevel**
This removes hard coded numbers as well as fixes internal links, with the aim of eliminating .htaccess rewrite rules for doc.silverstripe.org (as part of a tidy up of the rewrite rules there). Note that gurlchecker was used to identify broken internal links. Also note that multiple PRs will likely result since different doc versions have different internal link problems.

### CODE REVIEW

**Comment by dhensby** [comment]
ping @camfindlay

**Comment by camfindlay** [comment]
@dhensby this looks good to merge.

**Comment by tractorcow** [comment]
@camfindlay the files have been renamed so they don't have the 01_, 02_, etc prefix. Are we not doing this anymore?

**Comment by camfindlay** [comment]
@tractorcow this is an old version _before_ we moved to that convention. The prefixes here were to pseudo do in an old version of docsviewer what the new version does now for sorting.

**Comment by tractorcow** [comment]
Oh, I see.

**Comment by SpiritLevel** [comment]
Thanks...@tractorcow  more coming for 3.0.

**Pull request merged**
