### PR TITLE
NEW #4738: Ability to nest layout templates into sub-folders.

### PR DESCRIPTION
**Pull request by patricknelson**
New feature PR to demonstrate an implementation for issue #4738

### CODE REVIEW

**Comment by dhensby** [comment]
Would it be possible to write some tests to prove this code works as intended?

**Comment by tractorcow** [comment]
Can you please make sure that your tests demonstrate how well the code works with `module/templates` files, as well as `themes/mytheme/templates` files? :P

**Comment by tractorcow** [comment]
This feature has been superseded by the new strict template lookup in 4.x. Folders can be used to organise nested templates, but names are strictly applied, and must be used to refer to the template, rather than being a loose lookup. "folders used to organise templates but ignored during lookup" is a concept we've essentially outlawed, sorry.

**Comment by tractorcow** [comment]
Nevermind, this is a PR for 3.x. I'll leave it here then. :)

**Comment by dhensby** [comment]
This hasn't been touched for 1.5 years - I think it's a candidate for either closing or having someone take on the responsibility of writing the tests

**Comment by tractorcow** [comment]
I'll give @patricknelson  a chance :)

**Comment by patricknelson** [comment]
@tractorcow Even though this applies to `3.x`, you make a very good point here:

> Folders can be used to organise nested templates, but names are strictly applied, and must be used to refer to the template, rather than being a loose lookup. "folders used to organise templates but ignored during lookup" is a concept we've essentially outlawed, sorry.

That said, due to the impact of this change, I might pivot my approach to instead allowing the override the functionality with my own using SilverStripe's built in flexibility: Injector. That is, submit a PR to instead make this relatively simple change:

```php
// Load template manifest the main "Layouts" directory.
SS_TemplateLoader::instance()->pushManifest(Injector::inst()->create("SS_TemplateManifest",
	BASE_PATH, project(), false, $flush
));
```

... instead of `new SS_TemplateManifest` which is what is currently there right now both [in v3](https://github.com/silverstripe/silverstripe-framework/blob/3/core/Core.php#L132) and  [still apparently in v4](https://github.com/silverstripe/silverstripe-framework/blob/master/src/Core/Core.php#L101) in some form (not sure).

**Comment by dhensby** [comment]
@patricknelson I'd be happy for a PR like that - I'll close this as it seems like we won't be getting it merged unless you add some tests - happy to reopen if you have the chance to do so.

**Comment by patricknelson** [comment]
@dhensby See issue https://github.com/silverstripe/silverstripe-framework/issues/7305 / PR https://github.com/silverstripe/silverstripe-framework/pull/7306 (I always create an issue so I can version/number my branches anyway).

**Pull request closed without merging**
