### PR TITLE
FIX Imported namespaces now correctly used to determine class inhertance

### LINKED ISSUE #3707: Namespaced PermissionProvider implementors are not detected
If you namespace an implementor of PermissionProvider, like so:

```php
<?php namespace SomeCompany\Permissions;

use PermissionProvider;

class CustomProvider implements PermissionProvider {
    public function providePermissions() {
        return array(
            'DESTROY_WORLD' => 'Destroy the world',
        );
    }
}
```

Changes won't be picked up, so the permission codes will not be shown when creating roles.

### PR DESCRIPTION
**Pull request by dhensby**
Fixes #3707 

see #3899

### CODE REVIEW

**Comment by dhensby** [comment]
@assertchris  :) namespacing, whoo

**Comment by tractorcow** [comment]
Much more lovely code @dhensby :D Sorry for giving you pain over your other PR.

**Comment by tractorcow** [comment]
Should this fix be back-ported to 3.1?

**Comment by dhensby** [comment]
@sminee was of the opinion that only the most low risk bug fixes should go into 3.1, which makes sense. The upgrade to 3.2 should be quite frictionless. 

Though, if when you release the next patch to 3.1, you want it in there.. Then why not?

**Pull request merged**
