### PR TITLE
API TestSession request methods now use the correct HTTP method

### PR DESCRIPTION
**Pull request by Cheddam**
TestSession currently exposes 2 methods for sending a GET request:

- `get($url)`
- `post($url, [])`

The first one makes sense! The second... not so much.

If we follow the trail down, each of these methods is calling `Director::test` and passing `null` as the HTTP method, relying on `Director::test` to decide what method to use. Turns out, it decides based on whether the `$postVars` parameter passed is truthy. If yes, it's POST. Otherwise, it's GET.

Traditionally, `post()` would normally work as expected, as the vast majority of POST endpoints expect POST vars to be present. However, many POST endpoints in RESTful APIs use a JSON blob in the body of the request instead. To test these endpoints with TestSession today, we have to pass dummy POST vars into the `post()` call.

This PR makes `post()` POST, always. It also makes `get()` explicitly GET, and provides a third method - `sendRequest()` - which allows the developer to specify what HTTP method should be used (PUT and DELETE exist too!)

I'm raising this PR against master as it results in an API breakage - most uses of `post()` won't be relying on that request actually being passed as a GET, but some might.

### CODE REVIEW

**Comment by ScopeyNZ** [comment]
This is an interesting patch. I'd consider this a bug fix - suitable to target at a 4.x branch. 

Calling `$this->post` and having it run a `GET` request is just broken, and if tests are relying on that then that needs fixing.

cc @silverstripe/core-team

**Comment by ScopeyNZ** [comment]
We will probably have to remove the new API for a patch change though - it could be added in a separate PR to a minor branch though!

**Comment by chillu** [comment]
+1 on retargeting this on the 4.x branch. If you rely on a `GET` being fired when calling `->post()` somewhere, then you're on your own - I don't see this as an API breakage, it's a bugfix.

**Comment by Cheddam** [comment]
I've updated the PR to target the `4` branch, so that we can land the whole change at once 👍

**Comment by ScopeyNZ** [comment]
Just letting travis know the base branch changed :)

**Comment by Cheddam** [comment]
Keen to get this PR through, as it's difficult to test OPTIONS requests without the `sendRequest` method it introduces.

**Comment by chillu** [comment]
Ah yes, those pesky HTTP verbs - just use GraphQL ;)

**Pull request merged**
