### PR TITLE
Update 'spinner' to a SilverStripe branded version

### PR DESCRIPTION
**Pull request by nickspiel**
Updated PR based on feedback form #3678

PSD: http://nickspiel.me/uploads/silverstripe-assets/spinner.psd

### CODE REVIEW

**Comment by dhensby** [comment]
<3

@clarkepaul ahem

**Comment by chillu** [comment]
@clarkepaul will be back on 12th of Jan, sorry for the delay. @nickspiel can you please squash the commits in the meantime?

**Comment by nickspiel** [comment]
Okay I have squashed the commits, this is my first attempt at a squash. Let me know if there is any issues.

**Comment by clarkepaul** [comment]
Looking good, would it take much to make more white space surrounding the loader logo (it's pretty cramped within the white box) that could mean either making the box bigger or logo smaller.

Example:
pasted_image_14_01_15_4_21_pm

**Comment by nickspiel** [comment]
@clarkepaul Added some added as suggested.

**Comment by dhensby** [comment]
I think we are there :)

**Comment by clarkepaul** [comment]
Nice one cheers

**Comment by nickspiel** [comment]
So when can we merge this guy in?

**Comment by kinglozzer** [comment]
I say... now! I’ve checked out this change and tested it in situ everywhere I can find that it might appear - looks great. Many thanks @nickspiel :)

**Comment by dhensby** [comment]
:tada:

**Comment by nickspiel** [comment]
Awesome! 
:smile: :+1: :dancers:

**Comment by camfindlay** [comment]
radbuggers! :hamburger:

**Comment by clarkepaul** [comment]
Bravo

**Comment by nickspiel** [comment]
Any idea when this bad-boy will make a release?

**Comment by wilr** [comment]
@nickspiel Will be out with 3.2 so follow progress on that. Last I checked might be a month or 2.

**Pull request merged**
