### PR TITLE
API Add some convenience method for recording call to extend on Extensible trait

### PR DESCRIPTION
**Pull request by maxime-rainville**
Occasionally, I want to write unit tests that confirms that some extensions hooks have been called on a class that uses the Extensible traits. Right now, I would normally create a dummy extension that implement the methods I want to test and apply it to my targeted object during my unit test.

I wondering it it wouldn't be better to make it part of the actual Extensible API.

My idea would be to have a method call `enableRecordExtendCalls` on Extensible that would trigger `extend` to start recording all its calls. Then your unit test could call `extendCallsFor` to retrieve the list of extend calls and run some assertions on that.

This would remove the need to have dummy extension like this one: https://github.com/silverstripe/silverstripe-admin/blob/1/tests/php/ModelAdminTest/ModelAdminExtension.php

If people think this could be helpful I can write some extra unit test for it.

### CODE REVIEW

**Comment by kinglozzer** [comment]
Isn’t this what mock objects/`->expects()` are typically used for?

**Comment by maxime-rainville** [comment]
Would that work with mocking extension methods? I guess I could mock the `extend` method on the main object if mocking the extension method is not possible.

**Comment by dhensby** [comment]
I don't think we should be adding this kind of test code to classes. Mocks should be more than capable of recording calls to extends methods...

**Comment by kinglozzer** [comment]
>Would that work with mocking extension methods? I guess I could mock the extend method on the main object if mocking the extension method is not possible.

I was thinking more that you could create a mock of the extension itself, and then apply that mock extension with `::add_extension($mock)` (and maybe remove the original with `::remove_extension()`)

**Comment by dhensby** [comment]
Yeah, I've done that before, there's definitely a bit of help that could be given by SS to add mock extensions, but it's possible.

**Comment by ScopeyNZ** [comment]
I am in complete agreement with @dhensby's statement:

> I don't think we should be adding this kind of test code to classes.

We can provide test API for make asserting extensions easier - but we shouldn't be adding code for testing our non-test classes.

In my head, the perfect way for this to work would be to have some class that encapsulates calling extension methods rather than a trait - although a trait could be provided to make it easier to consume this class. Then you could have a "test version" of that class with API like what's proposed here, that leverages DI to be used in test runs.

**Comment by maxime-rainville** [comment]
Thanks everyone. That's very useful feedback. I'll go back to drawing board.

**Pull request closed without merging**
