### PR TITLE
Minor: changed background color

### PR DESCRIPTION
**Pull request by divya-patel**
> - I added another header color, sidebar color and center color
> first open source fix made by divya for silverstripe
image
@clarkepaul

### CODE REVIEW

**Comment by jonom** [comment]
Hi @divya-patel, can you please post a screenshot of what these changes look like. Also if it were to be accepted we'd probably want you to remove these kinds of comments in the code and commit messages: `/* changed by divya */` the commit history will show that you are the author so no need to add inline :)

**Comment by tractorcow** [comment]
@flashbackzoo can you please review this? Are these colours safe to change? :P

Thanks @divya-patel  appreciate the contribution.

**Comment by flashbackzoo** [comment]
Yep - happy to test and review with some screenshots :smile:

**Comment by tractorcow** [comment]
Is this ok @flashbackzoo ?

**Comment by flashbackzoo** [comment]
Just had a chat to Paul, he has one change, which he'll post soon.

**Comment by tractorcow** [comment]
Merged with https://github.com/silverstripe/silverstripe-framework/commit/fbc68f433fc53451af700447e894104737018b57?diff=unified

**Pull request closed without merging**
