### PR TITLE
Use short array syntax across the framework's codebase

### PR DESCRIPTION
**Pull request by michalkleiner**
Replace all usages of `array()` with `[]` — in code, in tests, in docs.
Fixed a couple of typos and missed brackets in code examples along the way.

I see this might potentially be a bit controversial move. What would it take to get this merged in? All code appearances can be converted automatically. I can perhaps look at updating relevant open PRs so they don't create new collisions or won't get denied just for not being compliant.

### CODE REVIEW

**Comment by michalkleiner** [comment]
Thanks @maxime-rainville, that makes sense. I've excluded the `thirdparty` folder from the update and from being linted as well.

**Comment by dhensby** [comment]
> Thanks. I've reviewed 60-70% of the changes, ignoring a lot of the test files. I did see a typo fixed in one of the files which indicates that this PR wasn't entirely automated. LGTM overall. Perhaps someone would like to review the tests so we have rough coverage on both parts?

maybe a core committer should just update the linting rule and run lint-clean and commit it to 4?

**Comment by dhensby** [comment]
I've pushed a fully automated linting clean up directly to 4 after discussing this with @robbieaverill

**Comment by dhensby** [comment]
OK - there were some good fixes to docs as well, so I've opened a new PR to cover those changes

**Pull request closed without merging**
