### PR TITLE
API remove DataFormatter class and all subclasses

### PR DESCRIPTION
**Pull request by tractorcow**
Cleanup of #5461

These classes aren't necessary to keep around, and were originally added to support the now-defunct RestfulService.

### CODE REVIEW

**Comment by dhensby** [comment]
yay - they were always a nightmare anyway!

**Comment by chillu** [comment]
Wait, what? These are required for the still operational `restfulserver` (a supported module), not the `RestfulService` which has been removed from core. See https://github.com/silverstripe/silverstripe-restfulserver/blob/f6025eac1d934a80e650c0aa9b700d35342cb44c/code/RestfulServer.php#L293. Can you please add those to restfulserver to avoid it breaking horribly in 4.x?

**Comment by chillu** [comment]
Also, changelog mention please!

**Comment by tractorcow** [comment]
Logged at https://github.com/silverstripe/silverstripe-framework/issues/6318

**Pull request merged**
