### PR TITLE
Update font icon library

### PR DESCRIPTION
**Pull request by scott1702**
Needed with - https://github.com/silverstripe/silverstripe-cms/pull/1268
Also updated the buttons in the files area to the new 'flat' style

### CODE REVIEW

**Comment by kinglozzer** [comment]
Looks like this also fixes #4528 :)

**Comment by dhensby** [comment]
@kinglozzer have you tested locally? good to take in?!

**Comment by dhensby** [comment]
I tested locally, though I don't have IE 10 and couldn't replicated #4528 with IE11 in emulation mode.

I don't see any obvious regressions and the new buttons look nice.

**Comment by scott1702** [comment]
Just added implementation of new logout font-icon to this PR
image

**Comment by dhensby** [comment]
@kinglozzer would you be able to test IE10?

**Comment by kinglozzer** [comment]
Tested in IE8, 9, 10 & 11, Chrome, Firefox and Safari - the icons looks great in all of them! Thanks @scott1702

**Comment by scott1702** [comment]
Thanks!

**Pull request merged**
