### PR TITLE
API redux-logger respects ss environment

### PR DESCRIPTION
**Pull request by tractorcow**
So that you don't get console spam when deploying or testing.

Rebased on top of https://github.com/silverstripe/silverstripe-framework/pull/5346 because that's getting merged soon.

### CODE REVIEW

**Comment by tractorcow** [comment]
Rebased. :D

**Comment by sminnee** [comment]
Seems reasonable to me. Including environment type in the standard config doesn't seem like it would introduce risk on production environments.

**Comment by chillu** [comment]
Tested locally, and rebased. We'll need to apply the same to the `asset-admin` module - although I'm a bit confused why this module has a `rootReducer` as well, it should just use the `lib/ReducerRegister` functionality.

**Comment by sminnee** [comment]
> Although I'm a bit confused why this module has a rootReducer as well, it should just use the lib/ReducerRegister functionality.

I think its implementation predates the existence of lib/ReducerRegister. Agree that refactor would make sense.

**Pull request merged**
