### PR TITLE
Versioned::choose_site_stage non persistent

### PR DESCRIPTION
**Pull request by g4b0**
Added a config value for choosing if choose_site_stage should be persistent or not. See discussion [here](https://groups.google.com/d/msg/silverstripe-dev/1Hjza_MWXiI/to6yfVgJB24J)

### CODE REVIEW

**Comment by dhensby** [comment]
This seems sensible, but we really need tests AND docs around this

**Comment by dhensby** [comment]
This will need to go against 3 branch too

**Comment by sminnee** [comment]
@g4b0 did you want to finish this change off with tests, docs, and a resubmission to the `3` branch? It's been sitting for a while but it would be good to get it included

**Comment by tractorcow** [comment]
Please re-open on 3 branch, thanks.

**Pull request closed without merging**
