### PR TITLE
add async and defer attributes to js requirements

### PR DESCRIPTION
**Pull request by xini**
as discussed in  #4427 rebased to master and replaced parameters for combine_files() with options array. 
Please let me know if you need any more changes.
Cheers.

### CODE REVIEW

**Comment by dhensby** [comment]
OK, final thing, can we add some docs for this? see https://docs.silverstripe.org/en/3.2/developer_guides/templates/requirements/

**Comment by sminnee** [comment]
@chillu @dhensby @tractorcow how does this overlap with the JS work y'all been doing lately?

**Comment by chillu** [comment]
This is still relevant, since `Requirements` can be used for all websites, not just the CMS (where `async` and `defer` likely won't play a role)

I tried to rebase this for 15 minutes on `master`, and there's substantial conflicts due the addition of `$options` and `provides` functionality to `Requirements` since this PR was raised. I'm going to close it for now, but @xini is welcome to reopen with a fixed version. I promise we'll look at getting it over the line quicker this time!

**Comment by xini** [comment]
I had completely forgotten about this one. I'll see what I can do.

**Pull request closed without merging**
