### PR TITLE
DOCS: typos, rewording, updated links.

### PR DESCRIPTION
**Pull request by SpiritLevel**

### CODE REVIEW

**Comment by willmorgan** [comment]
How very eloquent!

**Comment by SpiritLevel** [comment]
Thanks @willmorgan. I aim to please ;) Though I suppose what is more important is whether or not the end result is a bit more readable!

**Comment by dhensby** [comment]
On line 22 you updated the version to 3.2 but reference master as being 3.2 also, when it's actually 4.0

**Comment by SpiritLevel** [comment]
OK...will fix :)

**Comment by willmorgan** [comment]
:blush:

**Pull request merged**
