### PR TITLE
DEP Require psr/http-message ^2.0

### PR DESCRIPTION
**Pull request by emteknetnz**
Issue https://github.com/silverstripe/.github/issues/306

### CODE REVIEW

**Comment by GuySartorelli** [comment]
Is the mock stuff related? There's no information here other than the commit message saying you're updating a dependency, which at face value doesn't seem related to those changes.

**Comment by emteknetnz** [comment]
The mock stuff needed to be updated because they implement interfaces in psr/http-message, and need to match the new signatures

**Comment by GuySartorelli** [comment]
What uses this mock stuff? Is there an easy thing I can test locally? This isn't code I'm familiar with so some hand-holding is unfortunately needed here.

**Comment by emteknetnz** [comment]
EmbedUnitTest, I don't think anything else does

**Review by GuySartorelli — APPROVED** [review]
Oooohhhhhhh I'm stupid, sorry, I didn't notice these are in the `Test` namespace. DOH.
LGTM

**Pull request merged**
