### PR TITLE
API Director::host() now formally includes port in host consistently

### PR DESCRIPTION
**Pull request by tractorcow**
Also adds hostName() and port() methods

Replaces #7685

See notes on that ticket for design justification.

### CODE REVIEW

**Comment by dhensby** [comment]
Looks like an unrelated test failure...

**Comment by tractorcow** [comment]
Oh right, versioned module decorates the gridfieldconfig. I'll fix in another PR.

**Comment by tractorcow** [comment]
https://github.com/silverstripe/silverstripe-framework/pull/7782 seems to fix these issues.

**Comment by dhensby** [comment]
now getting a CMS behat failure :/

**Comment by tractorcow** [comment]
The new regressions are caused by https://github.com/silverstripe/silverstripe-admin/pull/394#issuecomment-359928032; Awaiting a fix.

**Pull request merged**
