### PR TITLE
Symfony 4 support

### PR DESCRIPTION
**Pull request by sminnee**
If we simply bump the packages, how many of our tests break?

### CODE REVIEW

**Comment by sminnee** [comment]
That was... surprisingly successful. Note that Yaml and Finder are still pinned to Symfony 3 by config. Looking to address that here: https://github.com/silverstripe/silverstripe-config/pull/45, which would necessitate 1 config 1.1.0 release...

**Comment by sminnee** [comment]
OK there's a circular dependency issues with the CMS build. This is a good sign of the issue with embedding recipes into the module tests: it creates bidirectional dependencies that make changes more complex. In the case of the CMS test it's a bit unavoidable, though. The recipe-core PR above will resolve that.

For the other build, I've removed the unnecessary recipe-core dependency, but we could roll that back if desired.

**Comment by sminnee** [comment]
Note that I would recommend that we merge the PHP 8 PR in first, as it introduces a prefer-lowest build that will be important for testing both major lines of Symfony.

**Comment by sminnee** [comment]
I want to note that this is only passing because we're not actually testing all of Symfony 4 and that the recipe-core patch will be needed to get that working (by bumping config to 1.1 which doesn't pin its deps to symfony 3)

The framework tests should pass once this happens; the CMS ones haven't been executed yet.

**Comment by dnsl48** [comment]
I've reran the tests and it looks like all of them. However, looks like it's the same issue for everything.

**Comment by sminnee** [comment]
Yeah I believe that this has been broken by recipe-core being used on all tests; one of the modules that it pulls in has a problem. I'll debug.

**Comment by sminnee** [comment]
It's worth noting that most frequent issue we've had so far is duplication in yaml files being silently accepted by symfony/yaml 3 and breaking in symfony/yaml 4. This may be something we want to call out in the upgrade notes as it can occur in people's config files without having an explicit yaml dependency.

**Comment by sminnee** [comment]
https://github.com/silverstripe/silverstripe-mimevalidator/pull/41 will help

**Comment by sminnee** [comment]
Ok the mimevalidator patch got this working again.

**Review by dhensby — APPROVED** [review]

**Comment by dnsl48** [comment]
Looks cool, but I'll try it with kitchen-sink before we merge :)

**Comment by brynwhyman** [comment]
@dnsl48 is away from the office this week, so I took the liberty of running this through the kitchen-sink to get an early gauge of whether there would be any issues.

Here is the build referencing this PR's fork: https://travis-ci.org/github/creative-commoners/cwp-recipe-kitchen-sink/builds/731144538

**There is only one failure and that's existing**. [See the most recent kitchen-sink build with the same failure](https://travis-ci.org/github/silverstripe/cwp-recipe-kitchen-sink/builds/731416479).

**Comment by brynwhyman** [comment]
😞  Since this was merged we're seeing failures in all module Travis tests that include Behat (which isn't in the kitchen-sink build)

Travis is installing symfony 4.4.14 which is conflicting with what's in module's behat.yml, e.g.: `The reserved indicator "%" cannot start a plain scalar; you need to quote the scalar at line...` https://github.com/silverstripe/silverstripe-versioned-admin/blob/1/behat.yml#L11

Example failure: https://travis-ci.org/github/silverstripe/silverstripe-versioned-admin/jobs/731825287

**Comment by ScopeyNZ** [comment]
That should be a simple fix to `versioned-admin`. That line just needs to be quoted. I'll make a 10 second untested PR for you.

**Comment by robbieaverill** [comment]
It's a shame that it's a breaking change in terms of "you used to be able to use unquoted % symbols in your YAML config but now you can't" but at least devs will notice immediately when upgrading their core dependencies and running a flush.

**Comment by sminnee** [comment]
That, and the rejection of duplicate keys, are both things we'll want to highlight in the upgrade guide, suggesting that people pin their projects to symfony/yaml:^3 if they don't want to deal with the changes.

**Pull request merged**
