### PR TITLE
NEW: Feature/prev next object

### PR DESCRIPTION
**Pull request by Firesphere**
This gets the previous or next, based on the given field. Defaulting to the ID.

### CODE REVIEW

**Comment by dhensby** [comment]
@Firesphere - this looks good but has been unloved for a year.

I think it needs to go against 3 branch and shouldn't be using `DataObject::get_one` - so I'm going to close this as I think most of this needs to be re-written anyway.

**Comment by Firesphere** [comment]
Woah, I wasn't even aware it was still open :D

Yeah, it definitively needs a rewrite to a better method, including a better test. Thanks for reminding me!

**Comment by christopherdarling** [comment]
Looks a useful addition, but won't this require sorting on a unique field? I think it's worth mentioning that in the docs somewhere.

For example if you were to have news posts ordered by Date, two posts with the same Date value, this wouldn't return the 'next' record.

Record 1 - 2015-01-01
Record 2 - 2015-01-01
Record 3 - 2015-01-02

Calling getNext(Date) on record 1 would give you record 3, not 2.

**Comment by Firesphere** [comment]
Yep, it definitively needs a whole bunch of refinements. If I have the time, I might give this suggestion a kick and restart an improved version when ready.

Or someone else might give this a shot, but that's not on me ;)

**Pull request closed without merging**
