### PR TITLE
NEW Allow SSViewer to be injectable

### PR DESCRIPTION
**Pull request by robbieaverill**
Unless there's a good reason why SSViewer isn't injectable by default, how do we feel about this change? If this gets approved then I've got a couple of other module PRs to smash up afterwards.

### CODE REVIEW

**Comment by sminnee** [comment]
@robbieaverill what would the other module PRs be?

**Comment by sminnee** [comment]
This change is okay, although as far as extensibility APIs go, we could potentially do better.

E.g. something like:

```php
interface Template
{
  /**
   * Populate this template with the given data and return the result as a string
   */
  function process($data);
}

// Remains as is expect for implementing the new interface
class SSViewer implements Template
{ ... }


interface TemplateFinder
{
  function getTemplateForIdentifierList($templates);
}
```

**Comment by sminnee** [comment]
That interface pair is just a quick sketch but the main thing is having an object that represents a single template ready to be rendered, and then another which is a factory for getting the right template based on the identifier list. The latter one would be an injector service.

In principle you could use this to plug in support for other template engines, including having some kind of dispatch that checked what kind of template was used for the given identifier

**Comment by robbieaverill** [comment]
Sounds like a good idea. I wish I had a use case to test this with!

**Comment by sminnee** [comment]
Yeah – that's what I was going to ask. Were the aforementioned "other PRs" test use-cases?

**Comment by robbieaverill** [comment]
Ah, ok - so the "other PRs" were the other core modules that use `new SSViewer` -> `SSViewer::create()`. The reason I'm suggesting this change is to allow us to add a proxy layer over SSViewer to monitor template usage etc.

**Comment by sminnee** [comment]
...like a middleware added to the TemplateFinder? :-D

**Comment by robbieaverill** [comment]
That sounds nice 😄

**Comment by sminnee** [comment]
...it's hackday next Friday and that's not a breaking API. ;-)

**Comment by tractorcow** [comment]
@robbieaverill I suggest making SSViewer_FromString injectable too.

```php
$viewer = new SSViewer_FromString($content);
```

**Comment by sminnee** [comment]
I'd probably approach that like...

```
interface TemplateFinder
{
  function getTemplateForIdentifierList($templates);
  function getTemplateFromString($templateContent);
}
```

**Comment by robbieaverill** [comment]
Would you both be OK with this PR making things injectable and another to add some interface structures?

**Comment by sminnee** [comment]
Yeah I'm okay with that if other core team agree.

**Comment by robbieaverill** [comment]
Cool - I'll change the title to WIP then add injection for the other SSViewer classes too

**Comment by robbieaverill** [comment]
Ok, done

**Comment by tractorcow** [comment]
@sminnee given we discussed the interface approach being another set of work, would it be ok to merge this? I've given in my blessing. :D

**Comment by robbieaverill** [comment]
Thanks team - the other PRs are open (listed above)

**Comment by sminnee** [comment]
Merged all 3.

**Pull request merged**
