### PR TITLE
Update it.yml - parse error on line 321 (323)

### PR DESCRIPTION
**Pull request by hdpero**
Error while building Italian version of framework. There is a wrong formatting in line 321 (ex. 323).

### CODE REVIEW

**Comment by tractorcow** [comment]
I've also fixed this string at https://www.transifex.com/silverstripe/silverstripe-framework/translate/#it/master/72668585?key=URLDESCRIPTION

Can you please make any translation strings in transifex; Just ping me if you need to be added as a reviewer.

It's ok to make a PR as long as it's changed there first. :)

**Comment by hdpero** [comment]
Hy, yes please, add me as a reviewer. I may be have some more translations strings to fix/add.
My Transifex username is @petar.simic

**Comment by tractorcow** [comment]
Hi @hdpero I've added you to our Italian team. Check your email for invitation.

**Comment by hdpero** [comment]
@tractorcow could you also add me to Croatian team? Ty

**Comment by tractorcow** [comment]
All done (I think!).

**Pull request merged**
