### PR TITLE
FIX: ViewableData::setFailover() didn't remove cached methods

### PR DESCRIPTION
**Pull request by kinglozzer**
Hopefully the unit test explains what’s going on here. Turns out @tractorcow was quite correct in his comment in https://github.com/silverstripe/silverstripe-framework/pull/4870#issuecomment-166722469:

> You might also need a mechanism and test to ensure you remove methods from the removed failover, since it looks like the new ones are being merged with the old.

### CODE REVIEW

**Comment by dhensby** [comment]
That refactor commit needs to go into 3 branch IMO - it's not a bug fix.

**Comment by dhensby** [comment]
In fact, if we want to be real anal, this should all go into 3 and you need to fix this issue in 3.4 but putting all the logic in `setFailover` :/

**Comment by kinglozzer** [comment]
The thing is it *can’t* all go in `setFailover()` - `Object::$extra_methods` is private, so unless we fancy messing around with `ReflectionProperty` I can’t see another way to do this :(

**Comment by kinglozzer** [comment]
I can remove that refactor commit though

**Comment by dhensby** [comment]
Let's just put it in 3?

**Pull request closed without merging**
