### PR TITLE
Update Common Problems with mod_rewrite issue

### PR DESCRIPTION
**Pull request by muskie9**
[Reference for issue #58 in silverstripe-installer](https://github.com/silverstripe/silverstripe-installer/issues/58#issuecomment-74509529)

### CODE REVIEW

**Comment by dhensby** [comment]
Thanks for this. I'd like to get a patch in this for 3.1.11 or 3.2 - could you update the docs to say "prior to 3.1.10"...

**Comment by muskie9** [comment]
All set @dhensby

**Comment by dhensby** [comment]
Thanks @muskie9 - I'm just waiting on likelihood that the fix will make 3.1.10 (I doubt it will) so this may need to say "before 3.1.11" (sorry, I know my original suggestion was 3.1.10, but looking at it it's ambiguous in it's current form if the fix isn't released in 3.1.10)

**Comment by dhensby** [comment]
You can make PRs safely against the 3.0 branch which doesn't need to say anything about prior versions

**Comment by muskie9** [comment]
Makes sense. I can update this once 3.1.10 stable is out and we know whether the fix made it in, unless you'd rather have it against the 3.0 branch.

**Comment by dhensby** [comment]
@muskie9 It should go against all previous docs branches (2.4, 3.0 and 3.1) as it's a problem for all versions until it's fixed

**Comment by muskie9** [comment]
@dhensby am I correct in thinking this would need a separate PR against 3.0 branch since the docs structure and files have changed from 3.0 to 3.1?

**Comment by dhensby** [comment]
That's right

**Comment by dhensby** [comment]
ok, can you update it to 3.1.11 please

**Comment by dhensby** [comment]
<3

**Comment by dhensby** [comment]
ARGH DANG I just noticed you said to put it *before* the `<IfModule mod_rewrite.c>` but it needs to go inside that clause...

Because you don't want to turn off the index.php interception if mod_rewrite is not enabled!!

**Comment by muskie9** [comment]
I looked at your PR at some point, I should've caught that. Updated. Guessing that should get updated in 3.0 as well.

**Comment by dhensby** [comment]
> Guessing that should get updated in 3.0 as well.

yes, please, sorry. I should have read better

**Comment by dhensby** [comment]
Thanks a lot, really appreciated - sorry for the tedious revisions

**Comment by muskie9** [comment]
No worries, wanted to make sure I got it right ;)

**Pull request merged**
