### PR TITLE
Fixing issue where words ending ay/ey/iy/oy/uy are not pluralised correctly

### PR DESCRIPTION
**Pull request by dhensby**
Words that end in a vowel and then a "y" should have an "s" added to the end, not have the "y" replaced with "ies".

play -> plays

### CODE REVIEW

**Comment by dhensby** [comment]
replaces #4750

**Comment by jonom** [comment]
Nice. Just wondering - does this get used for all locales by default? Wonder if it should be restricted to a subset, for example:

> the almost regular forming of plural noun forms (appending an ‘s’) is hardly found in German
> http://www.gnu.org/software/gettext/manual/gettext.html#Plural-forms

Maybe we could bake in [gettext support for plural forms](http://php.net/manual/en/function.ngettext.php)? Does `i18n_plural_name()` already do something like this or do plural forms have to be manually entered for non-English languages?

**Comment by dhensby** [comment]
@jonom we need a lexicon class that works for different languages for something like you're suggesting.

The way the system works is "assume English and use language files for others" and that will continue to work with this implementation.

**Comment by dhensby** [comment]
Basically, write your code and classes in english and translate them using language files is the process for SS (and, I think, most programming)

**Comment by jonom** [comment]
Fair enough :+1:

**Comment by sminnee** [comment]
In general, this kind of automatic language processing is necessarily going to be pretty limited / language specific and so if people complain about their edge-case being missed, "using a yaml lang file" is a better solution.

**Pull request merged**
