### PR TITLE
Add behat method to select an image in an html field

### PR DESCRIPTION
**Pull request by emteknetnz**
Issue: https://github.com/silverstripe/silverstripe-asset-admin/issues/1086

New behat function for https://github.com/silverstripe/silverstripe-asset-admin/pull/1115

Function is a copy-paste-adapt from the function above it `stepIHighlightTextInHtmlField()`

### CODE REVIEW

**Comment by emteknetnz** [comment]
We could, it would make that other PR easier to merge since it relies on this

It does seem a little more logical in framework though because there's a function directly above it which selects text from tinymce.  It may be useful to reuse in the future. Selecting an image from tinymce isn't really an asset-admin/file-manager thing either.

Let me know if you want me to keep it here or move it to asset-admin

**Comment by robbieaverill** [comment]
I second @maxime-rainville's request

**Comment by maxime-rainville** [comment]
Having this in framework doesn't provide much value ... it's only used in asset-admin. If we leave it in framework, every time we update this test we'll have to do an update on framework as well and we'll have to constantly double check we're installing the correct version of framework when running our asset-admin behat test.

I'm in favour of moving it to asset-admin.

**Comment by emteknetnz** [comment]
Will move this to asset-admin

**Pull request closed without merging**
