### PR TITLE
Move test to autoload-dev

### PR DESCRIPTION
**Pull request by szepeviktor**
...in composer config

### CODE REVIEW

**Comment by robbieaverill** [comment]
From memory this was deliberate, as autoload dev is a project level setting so would mean modules installed wouldn’t have their test classes auto loaded. I’m happy to be corrected!

**Comment by szepeviktor** [comment]
I agree:

- if you use the framework as a project you run tests
- if you install it as a dependency you never run tests

What do you think?

**Comment by robbieaverill** [comment]
That's not usually how SilverStripe is installed - we install one of the three core recipes: silverstripe/installer, silverstripe/recipe-cms or silverstripe/recipe-core. During Travis builds we install the repository as a project and run its tests, but those recipes are examples of "real world" installations where modules such as framework are installed in vendor/silverstripe/* and have suites of tests run against them. At this stage I don't think we'll be looking to change that architecture. Thanks for the PR though!

**Comment by szepeviktor** [comment]
Okay, I see.

**Pull request closed without merging**
