### PR TITLE
Reverting a page to a specific version is not working correctly : SS 3.2

### PR DESCRIPTION
**Pull request by priyashantha**
disabled creating a new version record for child Page_versions table but not in SiteTree_versions (Page extends SiteTree and when Page has db array) . Issue #5040

### CODE REVIEW

**Comment by tractorcow** [comment]
I have no idea why it said I changed the title... I didn't =/

**Comment by tractorcow** [comment]
Why does 'false' for the `$createNewVersion` parameter force creation of a new version in each table? IT seems to imply the opposite of the desired affect.

Maybe a unit test would help to prove this fix works? :D

**Comment by tractorcow** [comment]
See my comment at https://github.com/silverstripe/silverstripe-framework/issues/5040#issuecomment-184403197 with what I suspect is the actual problem.

**Comment by priyashantha** [comment]
As you said it makes sense when we revert to a older version, it creates a  new version. But the problem is the newly created version is only in for near child version table but not in parent. For instance : 

Page extends SiteTree {
  private static $db = array('test' => 'Varchar')
}

Now we have both Page and SiteTree table. When I revert page to a older version, the new version is only created in Page_versions table but not in SiteTree_versions table. Then we have an orphaned record in Page_versions table and we getting duplicate entry error when we re-try to revert to another version.

**Comment by tractorcow** [comment]
> As you said it makes sense when we revert to a older version, it creates a new version. But the problem is the newly created version is only in for near child version table but not in parent. For instance :


I agree this needs to be fixed. I'm just not sure that this specific fix will resolve the issue in a semver-compatible way; I'd rather one that we could merge without breaking semver. Or for that matter, without changes in behaviour we could avoid. :D

**Comment by priyashantha** [comment]
I came up with this solution because in previous SS version (3.1) there was no new version creation when we revert to a new version :) and I felt good to make $createNewVersion false in doRollbackTo() function as we'd not need a new version when we revert it back to an existing one. But that guess is not valid anymore because creating a new version record when reverting is a feature in the new version. 

I'm looking into fix for this and will let you know my findings.

**Comment by priyashantha** [comment]
I think we have the issue in $manipulation array according to my scenario. 

in augmentWite() function line number 663: if(empty($manipulation[$table]['fields']['Version']))
Here we have 2 tables (Page and SiteTree). Above condition is false only for SiteTree table as it contains Version field but not for Page table. I tested this against to SS3.1 installation and there we have Version field for both of Page and SiteTree tables. That's why there is no new version record in SS3.1 when rollbacking.

**Comment by tractorcow** [comment]
Maybe it'd be best to start with a unit test that reproduces the error?

**Comment by tractorcow** [comment]
Anyone looking here; I wrote a PR that might fix it at https://github.com/silverstripe/silverstripe-framework/pull/5074

**Comment by dhensby** [comment]
@tractorcow did it fix it?

**Comment by tractorcow** [comment]
Yep. :D

**Pull request closed without merging**
