### PR TITLE
Including canCreate in if statement so that button gets removed if us…

### PR DESCRIPTION
**Pull request by rafaeldsousa**
…er isn't to be able to create new records.

### CODE REVIEW

**Comment by robbieaverill** [comment]
Looks good, we can retarget this at a 4.x patch release branch however. If you want to do this yourself you can "Edit" next to the PR title and change the target branch to 4.4, then rebase your PR branch onto 4.4 (removing all irrelevant commits). Otherwise I can do it for you.

**Comment by rafaeldsousa** [comment]
Totally @robbieaverill will get that done soon.

**Comment by michalkleiner** [comment]
Would it be possible to do a rebase as well? 210 commits seem way too many for a change like that.

**Comment by rafaeldsousa** [comment]
@robbieaverill @michalkleiner Apologies on the hold up.
Should be all sorted now. (:

**Comment by rafaeldsousa** [comment]
@robbieaverill @michalkleiner any feedback on this one guys ?

**Comment by robbieaverill** [comment]
The phpcs failure is unrelated to this change. Thank you!

**Pull request merged**
