### PR TITLE
Adding nl_BE and fr_BE as common_locales

### PR DESCRIPTION
**Pull request by jpvdpoel**
In order to make them selectable as language in admin.

### CODE REVIEW

**Comment by dhensby** [comment]
Please can you add them in the "correct" place in the array (ie: in order next to "french" and "dutch") rather than right at the end?

**Comment by jpvdpoel** [comment]
Ahh, my bad, changed it.

**Comment by willmorgan** [comment]
These commits now need to be squashed

**Comment by dhensby** [comment]
@jpvdpoel are you able to squash these commits?

**Comment by tractorcow** [comment]
Squashed and merged with https://github.com/silverstripe/silverstripe-framework/commit/5dbb9c1da087bb603481366b6f70ce02977013b6

**Pull request closed without merging**
