### PR TITLE
Add getter/setter functions for FormField's dontEscape

### PR DESCRIPTION
**Pull request by mcccclean**
I've got a couple areas in the CMS on a project I'm working on where it makes sense to include a link to another record in amongst the form fields, and it's a pain to have to create an extra holder variable when everything else can be accessed by setters through `ReadOnlyField::create`.

Maybe it'd make more sense in the long term to make some kind of ClickableLinkReadOnlyField? But this at least brings $dontEscape inline with the other properties.

### CODE REVIEW

**Comment by dhensby** [comment]
@tractorcow I'm sure there's already a way to do this?

**Comment by dhensby** [comment]
Why not use a `LiteralField`?

**Comment by tractorcow** [comment]
Yes I think it needs getter/setter.

However, I really dislike the existing naming of this variable.

How about flipping the name though to make it more understandable.

```php
public function setEscapeEnabled($enabled) {
	$this->dontEscape = !$enabled;
}
```

**Comment by dhensby** [comment]
I'm going toclose this as stale - it's been open a long time with no progress from orignal author (sorry @mcccclean)

If you find you're able to implement the feedback, that'd be great and we can reopen this.

**Pull request closed without merging**
