### PR TITLE
FEATURE: validate text field length based on record objects allowed length

### LINKED ISSUE #3681: Default Varchar size is 50 - should default to 255
Default Varchar size is 50 - should it not default to 255?

Or is it has to be 50 then it needs to be mentioned a lot better in the docs.

### PR DESCRIPTION
**Pull request by stevie-mayhew**
Fixes #3681

### CODE REVIEW

**Comment by camfindlay** [comment]
Just reviewing the UserVoice features that are "started" any progress on this one?

**Comment by stevie-mayhew** [comment]
Sorry, I got Christmas'd. Will have a look at this as soon as I get an opportunity next week and start working on the approach outlined by @tractorcow.

**Comment by camfindlay** [comment]
Any movement on this? It's listed as Started on UserVoice https://silverstripe.uservoice.com/forums/251266-new-features/suggestions/6786049-validate-text-field-length-based-on-record-objects

**Comment by tractorcow** [comment]
Another bug for a rainy day I guess.

**Comment by stevie-mayhew** [comment]
Sorry for letting this go stale. I'm going to close this PR as its too far gone down the beaten track.

**Comment by camfindlay** [comment]
Thanks @stevie-mayhew I'll update the roadmap stuff to reflect this today.

**Pull request closed without merging**
