### PR TITLE
Login Redirect

### PR DESCRIPTION
**Pull request by MichaelJJames**
Issue I found yesterday with the login not redirecting when no backURL is set #7636

### CODE REVIEW

**Comment by tractorcow** [comment]
My own experience is that when attempting to access the CMS, and framework requests the user to log out of one member, and login as another, the "BackURL" is lost. There are quite a few steps involved where we COULD possibly persist the BackURL a bit better:

- Login as non-cms user
- Access /admin
- Shows message `I'm sorry, but you can't access that part of the CMS. If you want to log in as someone else, do so below.`
- Click "Log in as someone else"
- Log in as member with CMS permissions
- Redirect to home page (when I would expect to be sent back to admin)

It's not so much a bug, but it is a necessary enhancement that would slightly improve the re-authentication experience.

**Comment by tractorcow** [comment]
@MichaelJJames I would see if adding the BackURL querystring to the "login as someone else" action might fix this.

**Comment by dhensby** [comment]
@tractorcow the specific issue being described is logging out of the CMS then logging in again.

1. Logging out of the CMS takes you to a login page, should it? Should you just be taken to the home page after logging out of the CMS? It seems strange to assume that you'd be wanting to log back into an area you just logged out of
2. Can we add a `BackURL` to the logout link in the cms? - just tested, the answer is yes - we can add `?BackURL=admin` to the logout url and it'll set up the back url goodness

**Comment by dhensby** [comment]
> I would see if adding the BackURL querystring to the "login as someone else" action might fix this.

This should also be done, too. If there's a permissions failure and you've been redirected to the login form (but are logged in) then the BackURL should be persisted

**Comment by kinglozzer** [comment]
For reference, the 3.x behaviour is to just redirect back after logging out. E.g:

- Log in
- Visit `/admin/pages/edit/show/1`
- Click log out button (href is just `/Security/logout`)
- Get redirected “back”, based on referer header, which because of a permission failure will redirect you to `/Security/login?BackURL=%2Fadmin%2Fpages%2Fedit%2Fshow%2F1`

I think this may be something that I missed when adding the CSRF token to the logout action (I added it to the [logout form](https://github.com/silverstripe/silverstripe-framework/blob/4.0/src/Security/LogoutForm.php#L54-L63) for when the token is missing). We should be able to populate the back URL hidden field from the referer header I think?

**Comment by dhensby** [comment]
see https://github.com/silverstripe/silverstripe-admin/pull/368

I prefer being explicit than relying on a referer header. We could add the referer if it exists, but I'm not convinced that's a good idea.

**Comment by kinglozzer** [comment]
I’ll submit a PR to re-add the referer behaviour to `LogoutHandler`: that’s something that was missed by me, and hitting the logout URL without a valid CSRF token already falls back to the referer header as per the 3.x behaviour.

The two PRs aren’t mutually exclusive, though, so we can still add the base admin URL as `BackURL` if it’s deemed a better default

**Comment by dhensby** [comment]
ok - I'm closing this as it's not a solution we are happy with and we've got a couple of PRs that shuuld solve the initial bug

**Comment by MichaelJJames** [comment]
Great thanks guys for sorting it :)

**Pull request closed without merging**
