### PR TITLE
BUG fix issue with popup menu appearing on the left

### PR DESCRIPTION
**Pull request by tractorcow**
BUG fix incorrect selector on preview panel toggle
Fixes https://github.com/silverstripe/silverstripe-cms/issues/1581

Requires https://github.com/silverstripe/silverstripe-cms/pull/1618

Before:

image

After:

image

### CODE REVIEW

**Comment by clarkepaul** [comment]
The actual problem of the main actions was a missing CSS class (.ui-buttonset) surrounding the "Save" and "Publish" action. Is this something you noticed?

**Comment by tractorcow** [comment]
Those are the old jquery ui styles though... I think we want to get away from relying on those?

**Comment by tractorcow** [comment]
Ok, I've re-implemented the old behaviour, but rather than using jquery-ui styles I've used the bootstrap button row.

**Comment by clarkepaul** [comment]
Looks good and test in IE, ready for merge @chillu

**Comment by tractorcow** [comment]
Rebased to get rid of merge block.

**Comment by clarkepaul** [comment]
Just doing testing on master now and I'm not seeing these changes coming through. Will look into it...

**Comment by clarkepaul** [comment]
the cms branch wasn't was missed during merge, all done now

**Pull request merged**
