### PR TITLE
API Allow has_many fixtures to be declared with array format as well as many_many

### PR DESCRIPTION
**Pull request by tractorcow**
CC @dhensby who has struggled with this problem in the past. :D

Broken out of #5921

### CODE REVIEW

**Comment by sminnee** [comment]
Seems fine to me.

**Comment by dhensby** [comment]
No back port for 3? :(

**Comment by tractorcow** [comment]
It can be back-ported if you want to. It needs to go into master immediately though.

**Comment by dhensby** [comment]
Does that mean I have to back port? :P

**Comment by dhensby** [comment]
Well, that was easy - it was just your silly short array syntax that broke tests - see PR #5988

**Pull request merged**
