### PR TITLE
Remove question marks, equal signs and hashes

### PR DESCRIPTION
**Pull request by Taitava**
Those were not removed if multibyte was allowed.

### CODE REVIEW

**Comment by tractorcow** [comment]
Could you please include a test in URLSegmentFilterTest with setAllowMultibyte(true) and some of those characters?

**Comment by Taitava** [comment]
Ok, I did that, but apparently it came up as a new pull request #4963. I thought that GitHub would combine the pull requests when creating a new one while having another still open. Anyway, is this good now?

**Comment by tractorcow** [comment]
Are you able to please, maybe, try putting them into the same PR? Otherwise the tests won't pass with the fix. You'll need to switch to your patch-1 branch in the github editor and put the changes there.

**Comment by dhensby** [comment]
see #4973

**Pull request closed without merging**
