### PR TITLE
BUG Fix GridFieldAddExistingAutocompleter

### LINKED ISSUE #5382: GridFieldAddExistingAutocompleter Adds Incorrect Item to GridField
**Browser**: Google Chrome
**SilverStripe Version**: 3.3 (I first noticed in a 3.1 install but have recreated with a fresh install of 3.3)

**How to Replicate:**
1. Search for an existing DataObject using the GridFieldAddExistingAutocompleter and a fairly loose search term (so you are presented with a list of potential options, rather than just one)
2. Select option #1 (the dropdown of options disappears and your selected option shows in the search field and a hidden input field containing the DataObject ID is added to the DOM ```html <input type="hidden" name="relationID" value="100" id="relationID">```)
3. You change your mind (perhaps you clicked the wrong option by accident) and delete the contents of the search field
4. You re-search and select a different/the correct DataObject, lets say DO #2 
5. You hit enter or click 'Link Existing'
6. DataObject #1 is linked to your page and inserted into the GridField **not** DataObject #2 which you just selected

The issue here is that the hidden field in step 2 is neither cleared during step 3 or overwritten in step 4.

**Code Example**

Page:
```php
<?php
class Page extends SiteTree {

    private static $db = array(
    );

    private static $has_one = array(
    );

    private static $has_many = array(
        'MyDataObjects' => 'MyDataObject'
    );

    public function getCMSFields() {
        $fields = parent::getCMSFields();

        $fields->push($gf = new Gridfield('MyDataObjects', 'MyDataObjects', $this->getComponents('MyDataObjects'), new GridfieldConfig_RelationEditor()));
        return $fields;
    }

}
```

DataObject:
```php
<?php

class MyDataObject extends DataObject {

    private static $db = array(
        'AddressOne'        => 'Varchar(255)',
        'AddressTwo'        => 'Varchar(255)',
        'AddressCounty'     => 'Varchar(255)',
        'AddressCountry'    => 'Varchar(255)',
        'AddressPostcode'   => 'Varchar(10)',
        'Sort'              => 'Int'
    );

    private static $summary_fields = array(
        'AddressOne'        => 'Line One',
        'AddressTwo'        => 'Line Two',
        'AddressCounty'     => 'County',
        'AddressCountry'    => 'Country',
        'AddressPostcode'   => 'Postcode'
    );

    private static $has_one =  array('Page' => 'Page' );

    private static $default_sort = array(
        'Sort' => 'ASC'
    );
}
```

**Screenshots**

### PR DESCRIPTION
**Pull request by tractorcow**
This fix exchanges references to sub-components by ID with class references
Fixes #5382

Probably best reviewed with '?w=1' to remove whitespaces from diff.

CC @HARVS1789UK  for review. Can you please confirm this fixes your issue?

### CODE REVIEW

**Comment by tractorcow** [comment]
I'll fix these tests.

**Comment by tractorcow** [comment]
4.x version at https://github.com/silverstripe/silverstripe-framework/pull/5437

**Comment by tractorcow** [comment]
The 4.x version is fixed. Anyone care to merge this into 3.3? It's too late fro 3.3.2 unfortunately.

**Comment by kinglozzer** [comment]
Tested this locally and verified that it fixes #5382. Nice work @tractorcow

**Comment by HARVS1789UK** [comment]
Thanks @tractorcow - Sorry I didn't have time to test it myself for you before it got merged, I will be pulling down the changes as soon as I get back to this personal project. Thank you for the fix!

**Pull request merged**
