### PR TITLE
Added support for alpha-3 keys

### PR DESCRIPTION
**Pull request by JorisDebonnet**
Perhaps I shouldn't actually have opened an issue ticket first. Ah well, so this is linked to #3442. 

Does not break any code, as the `alpha3` config value defaults to `false` which leaves the functionality as it was. 

This is incomplete however, as I can't figure out how to actually make config values work outside of the class!... I can't figure out how to set `$this->config()->alpha3`, but clearly the config values must be set somewhere else. I just can't find where; it's not in this class file since those other config variables (default_to_locale and default_country) can't actually be changed by changing them in this file. Someone enlighten me?

### CODE REVIEW

**Comment by JorisDebonnet** [comment]
You make a good point - and it seems I'm extremely late to reply here!

I updated the file, which is now fully working. I had to move the `$source`-generation into the `Field` method, because it needs the `alpha3` config to know how to populate it.

I also believe I've totally managed squashing the commits this time, so I'm hoping this is ready! 

(granted, my repository is hopelessly behind the silverstripe one, but I'm assuming that's not a problem if this file was never changed)

**Comment by JorisDebonnet** [comment]
Should I do this against branch "3" instead?

**Comment by dhensby** [comment]
> Should I do this against branch "3" instead?

Please

What's the benefit of alpha3?

**Comment by JorisDebonnet** [comment]
Some companies may have another database (CRM) that lists their countries by alpha3 instead of alpha2. So if you're saving contact persons on the website as well, and you want to merge that with your CRM, you'll want those country codes to have matching formats of course. 
(this was the case for a client of mine)

So that's the only benefit: widening compatibility with other databases. 
(and aside of that, user prefence I guess, if people just love seeing 3 letters)

**Comment by sminnee** [comment]
Having a form field support a couple of different common backend data formats seems okay, although I'd be more comfortable with a setDataFormat config option that took a couple of different values instead.

String values mapped to class constants would probably be the best (config yaml will need to use the string values, code can use the class constants).

**Comment by JorisDebonnet** [comment]
I guess that makes sense, then in the future the [numeric ISO codes](https://en.wikipedia.org/wiki/ISO_3166-1_numeric) could easily be added. If I can use an abbreviated prefix like CountryCode, the class constants could be called `CC_ALPHA2`, `CC_ALPHA3` and `CC_NUMERIC`? 

The drawback to using configs however is that it goes against the suggestion of @kinglozzer to make it easily settable to the actual instantiated object, rather than something class-specific. To still incorporate that suggestion, I can still use those class constants, but just for the setter, and not in any config. 

Or I could just do both: support the yaml config system for a default class setting, and allow overwriting it per instance through the setter.

**Comment by dhensby** [comment]
@sminnee any further thoughts on this?

**Comment by sminnee** [comment]
Something that I'd like to investigate in 4.0 is the ability to update the config provider on an object-by-object basis, so that we don't have this problem for every fskcing option. Another piece of global state to step away from.

But that shouldn't hold up this. I think we should do both:

 * `private $static default_country_code_format`, acessed with `this->config()->default_country_code_format` should define the default format.
 * The value can be `CountryDropdownField::CC_ALPHA2`, `CountryDropdownField::CC_ALPHA3`, or `CountryDropdownField::CC_NUMERIC`, which are the same as the strings "alpha2", "alpha3", and "numeric". The strings are necessary for yaml config updates.
 * `$this->setCountryCodeFormat()` will override this on a field-by-field basis

Sound good?

Also, this should be rebased to either the `3` or `master` branch.

**Comment by sminnee** [comment]
@JorisDebonnet is this something you were still interested in working on or should we close this PR?

**Comment by JorisDebonnet** [comment]
I am still planning on finishing this (some time..), but the pull request should probably to be done against the 3-branch anyway, so I suppose this can be closed.

**Pull request closed without merging**
