### PR TITLE
Improve styling on modal dialogs

### PR DESCRIPTION
**Pull request by flashbackzoo**
Removed the thick black border around the dialog and close button. Added a 1px border with dropshadow and updated the close button icon.

### CODE REVIEW

**Comment by dhensby** [comment]
Can we see some screenshots of before and after, please?

**Comment by flashbackzoo** [comment]
Before:
before

After:
after

**Comment by nzjoel** [comment]
Will be so good to have this change in place. This has to be my biggest niggly design issue with the CMS since ever.

**Comment by dhensby** [comment]
This does look nice :)

**Comment by chillu** [comment]
Looking great, thanks guys!

**Pull request merged**
