### PR TITLE
destroy session on logout instead of restarting it

### PR DESCRIPTION
**Pull request by xini**
IMHO there is no reason to keep the session around after logout? When you visit a public page the session is not started either, so there is no reason to keep a session around after logout.

### CODE REVIEW

**Review by maxime-rainville — COMMENTED** [review]
Looking at Session, it looks like `restart` will call `destroy`. https://github.com/silverstripe/silverstripe-framework/blob/ae61be3a49bf60a2509ac9f2bdd02e2bcda7e24c/src/Control/Session.php#L246-L250

And `Session::init()` looks like it wants to start a new session if one doesn't already exists.
https://github.com/silverstripe/silverstripe-framework/blob/ae61be3a49bf60a2509ac9f2bdd02e2bcda7e24c/src/Control/Session.php#L226-L239

I suspect that in 99% of logouts, you'll be redirected to some page that will want to start a new session.

**Comment by xini** [comment]
Hi @maxime-rainville,

Thanks for your reply. 

> Looking at Session, it looks like `restart` will call `destroy`. 

Yes, `restart` does call `destroy`, but it also restarts a new session. For a normal page without a form a session is not needed. When you visit a default Silverstripe page, a session is not started. Hence we should destroy the session after logout. No?

> And `Session::init()` looks like it wants to start a new session if one doesn't already exists.

Correct, but we don't re-init the session after logout. 

> I suspect that in 99% of logouts, you'll be redirected to some page that will want to start a new session.

That might be the case, but that really is up to the developer building the site. If the target page needs a session, it can/will create it. But we don't need to force it. right?

**Comment by dhensby** [comment]
Whilst I agree with @maxime-rainville that most pages will probably start a session anyway, there's no point forcing the session to be started unless it's really needed. So I think this change is sensible.

I think it should go into 4 branch, though. Not 4.8.

**Comment by xini** [comment]
@dhensby I have rebased this. Thanks.

**Review by dhensby — APPROVED** [review]

**Comment by dhensby** [comment]
Apparently there are some linting issues 😕

**Pull request merged**
