### PR TITLE
Removing @deprecated 3.1 functionality and classes.

### PR DESCRIPTION
**Pull request by halkyon**
Changelog has been updated to include what was removed in terms of
major functionality, and what to use as a replacement.

### CODE REVIEW

**Comment by dhensby** [comment]
erm...... semver @tractorcow

**Comment by sminnee** [comment]
ugh, these were removed from master before we decided to go semver. I guess we could revert from 3.2 and merge forward to 3?

**Comment by dhensby** [comment]
Yep, I think that's what needs to happen...

**Comment by sminnee** [comment]
Raised #4514 as a reminder.

**Pull request merged**
