### PR TITLE
Fixed iframe postmessage breaking non-string messages

### PR DESCRIPTION
**Pull request by roed**
See issue: https://github.com/silverstripe/silverstripe-framework/issues/6562

This is a fix for that, which was already implemented in the code for version 4.0.

### CODE REVIEW

**Comment by dhensby** [comment]
If this affects 3.4 I'll rebase it against that

**Comment by dhensby** [comment]
hmm - you've opened a PR from your 3.5 branch, so we can't rebase against 3.4 :P

**Comment by roed** [comment]
I am sorry. How can I fix this?

**Comment by dhensby** [comment]
> I am sorry. How can I fix this?

You should only open PRs using branches intended for the PR. But it's ok we just won't fix it in 3.4 - it's a very low risk issue and 3.4 is technically only security fixes

**Comment by roed** [comment]
Ok, so I should have made a feature/fix branch?

**Comment by dhensby** [comment]
yes

**Comment by roed** [comment]
Ok, will do that the next time

**Pull request merged**
