### PR TITLE
Declare the global mapping

### PR DESCRIPTION
**Pull request by Firesphere**
Fix for  #4426

### CODE REVIEW

**Comment by Firesphere** [comment]
In addition, this doesn't break working CLI commands, but un-breaks a few non-working CLI calls, like Behat testing.

**Comment by dhensby** [comment]
If this is a bug fix, it's safe to go into 3.1 IMO

**Comment by sminnee** [comment]
If it were raised in 3.1 then I'd merge it but it in 3.2

**Comment by tractorcow** [comment]
By the way this caused a regression. :) 

https://github.com/silverstripe-labs/silverstripe-travis-support/pull/19

**Comment by dhensby** [comment]
Heh, I knew I should have been more cautious :P

**Pull request merged**
