### PR TITLE
DOC Update atomic MigrationTask description

### PR DESCRIPTION
**Pull request by emteknetnz**
Make it clear that you need to subclass this class, rather than the current description that just looks like a todo item

### CODE REVIEW

**Comment by michalkleiner** [comment]
Should it be an `abstract` class then?

**Comment by Cheddam** [comment]
@michalkleiner Yes, but unfortunately that would be an API change 😅

**Comment by michalkleiner** [comment]
@Cheddam but we can still create a PR for that, right? What branch would it target? `4` or `master`?

**Comment by Cheddam** [comment]
@michalkleiner Yep, you'd want to target `master`.

**Comment by michalkleiner** [comment]
PR #9432 created.

**Pull request merged**
