### PR TITLE
FIX Avoid JS errors for HTMLEditorFields in small holders

### LINKED ISSUE #7210: HTMLEditorField in FieldGroup caused obtuse JavaScript error
Doing something like the following in getCMSFields():
```php
$fields->addFieldsToTab("Root.MyTab", array(
    $fg = FieldGroup::create(
        HtmlEditorField::create('MyFieldContent', 'MyField Content')
    )
));
```

Causes the following JavaScript errors in console and HTMLEditorField doesn't appear at all:
```javascript
LeftAndMain.EditForm.js?m=1500872371:222 Uncaught TypeError: Cannot read property 'getInstance' of undefined
    at init.oneditorinit (LeftAndMain.EditForm.js?m=1500872371:222)
    at init.<anonymous> (jquery.entwine-dist.js?m=1500872398:1764)
    at one (jquery.entwine-dist.js?m=1500872398:1011)
    at init.prxy [as from .htmleditor_editorinit] (jquery.entwine-dist.js?m=1500872398:1036)
    at HTMLDocument.<anonymous> (jquery.entwine-dist.js?m=1500872398:1751)
    at HTMLDocument.dispatch (jquery.js?m=1500872400:3332)
    at HTMLDocument.eventHandle (jquery.js?m=1500872400:2941)
    at Object.trigger (jquery.js?m=1500872400:3210)
    at HTMLTextAreaElement.<anonymous> (jquery.js?m=1500872400:3869)
    at Function.each (jquery.js?m=1500872400:660)
```

### PR DESCRIPTION
**Pull request by dhensby**
fixes #7210

### CODE REVIEW

**Comment by SilbinaryWolf** [comment]
@dhensby Wouldn't it be more correct to just update "FormField_holder_small.ss" to have $extraClass in the wrapping div like FormField_holder.ss?

**Comment by dhensby** [comment]
I'd expect that to cause significant regressions for people relying on the current core templates. This is the least intrusive fix that solves the problem.

**Comment by SilbinaryWolf** [comment]
Yeah good call :)

**Comment by dhensby** [comment]
@tractorcow are you happy with this for the 3.5 patch?

**Pull request merged**
