### PR TITLE
Dead code removal (constructor type-hints are sufficient)

### PR DESCRIPTION
**Pull request by Ocramius**
Thanks to @lcobucci for making me notice this.

### CODE REVIEW

**Comment by tractorcow** [comment]
Look good. :) Will merge on tests passing.

**Comment by Ocramius** [comment]
@tractorcow passed ;-)

**Comment by lcobucci** [comment]
Wow that was really fast :smile:

I apologize for not sending the PR myself. Some people told wrong things about silverstripe community and instead of trying I just listened them.

You can expect some commits from me. 

Thanks @Ocramius.

**Comment by tractorcow** [comment]
Getting submissions merged or responded to quickly is something we still need to improve on. :)

**Pull request merged**
