### PR TITLE
Issue #4073: Implemented the validate() method for the TextField class

### PR DESCRIPTION
**Pull request by kamrandotpk**
Issue #4073: Implemented the validate() method for the TextField class and check if the value is not greater than the set max length of the TextField

### CODE REVIEW

**Comment by kinglozzer** [comment]
@kamrandotpk Great work! Just a few things that need correcting:

- We use tabs instead of spaces for indentation, could you switch to tabs please? (except .yml files as those use spaces). Could you also add an empty new line to the end of `TextFieldTest.php`?
- The indentation of the entity you added to en.yml doesn’t quite match up to the existing entities: each level should be two spaces “deeper” than its parent
- I’d probably remove the `setup()` method and extra properties from the test class and just pass the field name + length as normal - if someone changes that length to affect one test in future, they might accidentally affect other tests. We can also remove the extra validator class: other form field tests just pass an empty `RequiredFields` validator: `$field->validate(new RequiredFields());`

The only other thing is that this PR should’ve been submitted against the 3 branch instead of 3.1 (as we follow [semantic versioning](http://semver.org/), this will need to go in the next “minor” release). If you can rebase this PR against the 3 branch and re-open it, great! If not, don’t worry about it: we can merge it into 3 for you :)

Thanks!

**Comment by kamrandotpk** [comment]
@kinglozzer Many thanks for the excellent feedback =) I'll make the necessary changes and update here. Thanks.

**Comment by kamrandotpk** [comment]
@kinglozzer hey Loz, I've made the necessary changes. 

Regarding submitting the PR against 3 instead of 3.1, it would be awesome if you can merge it to 3 for me. Thanks! =)

**Comment by kinglozzer** [comment]
@kamrandotpk Looks good, thanks! As soon as #4175 is merged I’ll merge this into the 3 branch :)

**Comment by tractorcow** [comment]
#4175 has been merged @kinglozzer

**Comment by kinglozzer** [comment]
Squashed and merged: 20c9d6f02e1c45f8ac9926d167558687e35fb446. Thanks @kamrandotpk!

**Pull request closed without merging**
