### PR TITLE
Support polymorphic ManyManyThrough when 'from' end defines $owns

### PR DESCRIPTION
**Pull request by normann**
Support polymorphic ManyManyThrough when 'from' end defines $owns and end objects And / OR through object are versioned

### CODE REVIEW

**Comment by tractorcow** [comment]
Ah, good job understanding this method; it was a bit of a nightmare to design.

I don't suppose you could include a test to prove it works? :P

**Comment by normann** [comment]
yes, @tractorcow it is on our schedule to make a test,
Cheers.

**Comment by robbieaverill** [comment]
Let's sit on this and hope for a unit test to accompany it =) thanks for contributing @normann!

**Comment by emteknetnz** [comment]
@normann Hi just checking in on this pull-request - are you going to be able to write an accompanying unit test for this?

**Comment by emteknetnz** [comment]
This pull request hasn't had any activity for a while. Are you going to be doing further work on it, or would you prefer to close it now?

**Comment by emteknetnz** [comment]
It seems like there's going to be no further activity on this pull request, so we've closed it for now. Please open a new pull-request if you want to re-approach this work, or for anything else you think could be fixed or improved.

**Pull request closed without merging**
