### PR TITLE
Change drag/drop icon and make them only appear on hover

### PR DESCRIPTION
**Pull request by scott1702**
image

### CODE REVIEW

**Comment by tractorcow** [comment]
It looks a bit broken on my checkout

image

**Comment by scott1702** [comment]
@tractorcow You might have to flush your cache now that the image is changed.

**Comment by tractorcow** [comment]
Nevermind, cleared my cache and it ... ah too late you saw it.

**Comment by tractorcow** [comment]
An issue I notice is during drag; If you drag a page over another one, the icon will appear, but instead of the icon appearing on the left it shifts the whole text to the right.

image

**Comment by scott1702** [comment]
Good spotting, updated it. See what you can break now :)

**Comment by tractorcow** [comment]
I've re-tested it and it seems fine to me now.

Does anyone else want to put their opinion on this change? @silverstripe/core-team ?

**Comment by kinglozzer** [comment]
I think this looks great! I’ve tested it in IE8 and IE9 too and it works well in both of those :) my only bits of feedback are:

- The area that displays the “move” cursor is quite small, it tends to flicker between cursor types when you try to hover over the drag handle. That doesn’t stop you dragging of course, but the move cursor implies that that’s the only way to move items, so it’d be good to make it easier to “grab”. Perhaps a little extra width on the icon would help?
- The drag handle doesn’t show until you hover over the text to the right of it. Hard to explain, but start with your mouse to the left of the menu and slowly move it to the right and you should see what I mean. Adjusting the padding on the anchor instead of the margin seems to fix this

Loving all these little improvements to the UI!

**Comment by scott1702** [comment]
Very valid points @kinglozzer, I'll have a look into polishing it up a little first thing in the morning.

**Comment by willmorgan** [comment]
As long as it's also visible on focus as well as hover, decluttering the menu design is a :+1: from me.

**Comment by scott1702** [comment]
Thanks for the feedback guys, updated :)

**Comment by jonom** [comment]
Hey @scott1702 I noticed that you modified some css styles that reside in the `thirdparty` directory - I would suggest leaving those files unchanged and instead introducing a style rule to override them in ` admin/scss/_tree.scss`. I assume (or hope) that all those thirdparty files get updated from time to time and we wouldn't want your work to be lost in the process :)

**Comment by chillu** [comment]
:+1:, as long as the thirdparty code modification issue is resolved.

**Comment by scott1702** [comment]
Yep, just found another bug too that I need to fix. I'll make those changes now.
image

**Comment by scott1702** [comment]
Updated, Thanks @jonom

**Comment by kinglozzer** [comment]
I’ve re-tested in IE8, IE9, Firefox and Chrome and everything’s working perfectly. The thirdparty issue is resolved, and I’ve confirmed that the drag handle does show on focus, so I think we’re good to go!

Thanks @scott1702!

**Comment by willmorgan** [comment]
:trophy:

**Pull request merged**
