### PR TITLE
Renamed IMagickBackend to ImagicBackend

### PR DESCRIPTION
**Pull request by christopherdarling**
Also updated config:: to Config:: on line #52

### CODE REVIEW

**Comment by dhensby** [comment]
@christopherdarling can you explain exactly what the issue is here? is it because `Config` is case sensitive with it's class names and so this fails to actually make a difference?

**Comment by christopherdarling** [comment]
@dhensby I've personally not run into a issue with it, I was just looking through the code and spotted it was different to the usage elsewhere, so just a update for consistency as far as I'm aware.

**Comment by dhensby** [comment]
So what was the issue you experienced and did this fix it?

**Comment by christopherdarling** [comment]
I've personally not run into a issue with it... 
... so just a update for consistency as far as I'm aware.

**Comment by dhensby** [comment]
Deep. Sorry, I'm on my phone so not reading properly!

**Comment by christopherdarling** [comment]
No worries :)

On 2 March 2015 at 09:40, Daniel Hensby <notifications@github.com> wrote:

> Deep. Sorry, I'm on my phone so not reading properly!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/silverstripe/silverstripe-framework/pull/3952#issuecomment-76682602>
> .
>



-- 
Kind Regards,
Christopher Darling
www.christopherdarling.co.uk

**Comment by dhensby** [comment]
thanks!

**Pull request merged**
