### PR TITLE
make Group use tri-state can* extension hooks, fixes #9580

### LINKED ISSUE #9580: Extending Group::canView() Doesn't Follow the 'Tri-State' Response Pattern
## Affected Version
4.5.3

## Description

Rather than allow for a 'tri-state' style response of true/false/null on extensions of `canView`, `canEdit()` etc. `Group` only allows extensions of these methods to count towards [forcing the failing](https://github.com/silverstripe/silverstripe-framework/blob/4.5.3/src/Security/Group.php#L591) of these checks, never [forcing the success](https://github.com/silverstripe/silverstripe-framework/blob/4.5.3/src/Security/Member.php#L1594) like `Member` and other classes allow for.

### Use Case
I want to provide a list of Groups the current member belongs to, via a GraphQL query, to my front-end. This is to facilitate for some basic display logic (e.g. are they in the clients group, or an admin etc). 

Currently this is not possible as members cannot 'view' any groups, even if they are an active member of the group, unless they have the `CMS_ACCESS_SecurityAdmin` permission, which end-users should not have.

## Steps to Reproduce

- Extend `Group` via a `DataExtension` and add a `canView()` method that returns a 'tri-state' of true/false/null (or just `return true;` for simplicity)
- Test the output of `Group::canView()` on a member who doesn't have the `CMS_ACCESS_SecurityAdmin` permission (e.g. an end user)
- It will return false (even though our extended `canView()` gets called *and* returns a blanket `true` response)

## Expected Behaviour

- Testing `Group::canView()` should return `true` as per the blanket value of `true` which we are returning from our extension.

This is how `Member` [for example](https://github.com/silverstripe/silverstripe-framework/blob/4.5.3/src/Security/Member.php#L1594) (and most other classes I think) deals with extending `canView()` and is generally a much more useful and flexible implementation  

## PR
- https://github.com/silverstripe/silverstripe-framework/pull/10751
- https://github.com/silverstripe/developer-docs/pull/262

### PR DESCRIPTION
**Pull request by xini**
## Issue
- #9580

### CODE REVIEW

**Comment by GuySartorelli** [comment]
This represents a breaking change. We can't do this in CMS 4 and it's unfortunately missed the window to be included in CMS 5. 
Closing this pr for now - we can revisit this for CMS 6.

**Comment by xini** [comment]
All of a sudden picky about breaking changes?! 😆

Please reopen and tag with v6. Or are you keeping a list of v6 things and will ask for a new pr once v6 is on the horizon?

**Comment by GuySartorelli** [comment]
It was clearly signposted in changelogs, release anouncements, and the major release policy.

We don't have a branch for CMS 6 changes yet. The issue this is intended to resolve is still open, and we'll be able to recover this PR at the appropriate time as it's referencing that issue.

**Comment by xini** [comment]
That's been the case for all 4.x releases and still every one of them has breaking changes . But no worries. 

Actually I dont think it is a breaking change. If someone has extended this and returns false, the behaviour is the same. With this change there is the added functionality that yoy can also return true now. So it doesnt break current behaviour, only extends the current functionality.

**Comment by michalkleiner** [comment]
I wouldn't be so harsh here and reopen this, retarget at `5` and consider it for the `5.1` release because we appreciate community contributions and the time people spend trying to make the CMS and the framework underneath it better.

**Comment by GuySartorelli** [comment]
We do appreciate community contributions - I don't think that's a good enough reason to allow this if it _is_ a breaking change, but it is a good enough reason to give it a more careful look over.

It could be considered a breaking change in regards to how the permission check reacts to a `true` result returned from an extension - however I had originally thought the change affected `false` values as well. @xini thank you for pointing out that won't change.
I've also looked back to see if I can find a reason it was ignoring `true` values previously - this bit of code was added aaaages ago in [this commit](https://github.com/silverstripe/silverstripe-framework/commit/bd2b9efede59acc53b0bb506afc8634be5115f1b) and there's no mention of intentionally ignoring `true` values - maybe it was an oversight, or maybe this was before the more standard "let any extension boolean through" approach took hold.

I think I'm okay with this for 5.1, though I'll need to give it a closer look I'll reopen for now - @xini please retarget this PR at the `5` branch and rebase.

**Comment by xini** [comment]
Thank you very much. This is now rebased and ready to go.

**Review by GuySartorelli — APPROVED** [review]
Looks good, thanks. I've created https://github.com/silverstripe/developer-docs/pull/262 to document this change.

**Pull request merged**
