### PR TITLE
Fix background size for spinner @2x

### PR DESCRIPTION
**Pull request by kinglozzer**

### CODE REVIEW

**Comment by dhensby** [comment]
What's the issue here? can we see before/after screens?

**Comment by kinglozzer** [comment]
The background size is incorrect - the spinner in this context is squashed vertically. It’s hard to get a screenshot as it only displays briefly. This was just overlooked when [other](https://github.com/kinglozzer/sapphire/blob/pulls/spinner-fix/admin/scss/_retina.scss#L61) [values](https://github.com/kinglozzer/sapphire/blob/pulls/spinner-fix/admin/scss/_retina.scss#L68) were updated.

**Comment by dhensby** [comment]
This is what current beta looks like for me on my "retina" screen:

retina

**Comment by dhensby** [comment]
Ah, it's in a dialog:

**Comment by kinglozzer** [comment]
Yeah sorry I should’ve mentioned that!

**Pull request merged**
