### PR TITLE
Make sure format for the string matches DB format

### PR DESCRIPTION
**Pull request by pitchandtone**
Currently the code attempts to insert '["Thurs","Fri","Sat"]' whereas the format should be "Thurs,Fri,Sat"

### CODE REVIEW

**Comment by pitchandtone** [comment]
This field needs more testing, these changes make sure the field goes into the DB, but it still needs work coming back out of the DB and pre-filling a checkboxlist.

**Comment by tractorcow** [comment]
It should join the values together with `,` shouldn't it?

**Comment by pitchandtone** [comment]
Yeah it uses a MYSQL SET which is “Value1,Value2,Value3”

While the code i submitted gets the data in i wasn’t sure if i’d handled it in the right way.

Next issue was to either transform it as it comes back which I couldn’t find a pattern for, or make checkbox field handle a comma separated value which seemed a fragile route.

So keen for input.

**Comment by pitchandtone** [comment]
Should I be using this instead:
https://github.com/symbiote/silverstripe-multivaluefield ?

**Comment by tractorcow** [comment]
This field should work.

**Comment by maxime-rainville** [comment]
This got fixed independently by https://github.com/silverstripe/silverstripe-framework/pull/8499

**Pull request closed without merging**
