### PR TITLE
Show message when done.

### PR DESCRIPTION
**Pull request by bergice**
This is useful as you can see the timestamp when it completed and you also know it reached the end of the migration script.

### CODE REVIEW

**Comment by robbieaverill** [comment]
With the software in RC stage, we aren't taking in any new features, however this is super low value/impact so it's probably OK.

**Comment by dnsl48** [comment]
I'd guess this one goes into 4.4.1 though

**Comment by robbieaverill** [comment]
Again, super low value/impact, but this looks like an enhancement to me so would need to go into 4.5 if you're not going to bring it into 4.4.0 stable

**Comment by michalkleiner** [comment]
It might be seen as a patch to a missing functionality of not outputting a Done message -> 4.4.1

**Comment by robbieaverill** [comment]
I guess that's why they call it "semantic" versioning 😆

**Pull request merged**
