### PR TITLE
Optimised keyedColumn() and map() for MySQLQuery

### PR DESCRIPTION
**Pull request by mikenz**
I'm not sure if you want DB specific implementations like this but thought I'd create a PR in case there was interest.

### CODE REVIEW

**Comment by dhensby** [comment]
I don't think we mind MySQL-centric syntax in the MySQL classes.

What kind of performance increase does this give and why is it more performant than what we have?

**Comment by mikenz** [comment]
before

after

**Comment by dhensby** [comment]
Well look at that. @kinglozzer @tractorcow

Please can we get some test coverage (skip the tests if not a mysql driver)? Then I'm happy :)

**Comment by mikenz** [comment]
I guess there's no existing test that uses keyedColumn so the current code isn't tested either. I'll write a test this week and added it to this PR.

**Comment by kinglozzer** [comment]
Makes sense to me, but I think we need our database overlord @tractorcow to sign this off 😄

**Comment by dhensby** [comment]
testfailure on postgres - the keys (IDs) are different. We need to make sure the test doesn't make assumptions about what the IDs are and instead pull them out of the DB...

**Comment by mikenz** [comment]
Yeah, I'll change the test to use the Sort column instead of the ID column - an equally valid test and the Sort values are defined in the fixture.

**Comment by dhensby** [comment]
Oh, whoops, sorry I just pushed a change up (I thought you'd be sleeping)

**Comment by dhensby** [comment]
Thanks for the test coverage, super helpful. Once this is green, I'll merge. It's going into master and so @tractorcow can revert if he doesn't like it.

Can we make any of these kinds of improvements to other parts of core?

**Comment by mikenz** [comment]
I'm working on performance of our installation all this week so where I can (and think it'll get merged) I'll raise PRs. Some of my improvements only work because I can make assumptions that won't hold true for everyone.

**Comment by dhensby** [comment]
OK - great, thanks - really appreciate that :)

**Comment by dhensby** [comment]
@mikenz also, if you find any areas that are bottlenecks but can't submit a PR for them, please raise them as issues.

**Comment by tractorcow** [comment]
Sorry, this needs to be reverted since it's not compatible with mysql-nd, and is breaking sites. =(

**Pull request merged**
