### PR TITLE
Delete orphaned Group_Members records after deleting a Member

### PR DESCRIPTION
**Pull request by JorisDebonnet**

### CODE REVIEW

**Comment by dhensby** [comment]
I'm sure this was logged before, can you take a quick look for an old ticket or PR covering this?

**Comment by lerni** [comment]
@dhensby related: https://github.com/silverstripe/silverstripe-framework/issues/1903#issuecomment-339520737

**Comment by dhensby** [comment]
@lerni that's the one - thanks.

@tractorcow what do you think to this? is there likely to be movement on #1903 any time soon?

**Comment by tractorcow** [comment]
I don't think #1903 is going to be implemented any time soon. Let's just merge this.

**Pull request merged**
