### PR TITLE
Remove WebPI references

### PR DESCRIPTION
**Pull request by chillu**
WebPI was a Microsoft initiative to make it easier for Windows users to install web-based software, by bundling Microsoft stacks like SQL Server Express and IIS with software codebases into a one-click install: https://webgallery.microsoft.com/apps/SilverStripeCMS

While this seemed like a good idea back in 2009 ([announcement](https://www.silverstripe.org/blog/installing-on-windows-now-easier-thanks-to-microsoft-web-platform-installer/)), the world has moved on: Developers on Windows are commonly using virtual machines to set up development stacks, and cloud-based services like Bitnami allow to trial software simply by launching a machine image into a cloud server.

WebPI still part of the [release docs](https://docs.silverstripe.org/en/4/contributing/making_a_silverstripe_core_release/#stage-4-web-platform-installer-release), but those haven't been followed since 3.2.0. So we're [publishing](https://www.microsoft.com/web/gallery/silverstripecms.aspx) an unsupported version of SilverStripe on the Microsoft portal.

The last review on WebPI is from 2013, they don't have download stats, but I'd expect it to tend towards zero. Not even Drupal 8, which was released for three months already, is on there - so not a high priority for them either. The whole WebPI store has 88 apps total, so it's hardly a crowded space.

In light of our small team size, I'm recommending to shut down this release channel, and use the time more productively on improving the release processes for the vast majority of our users.

This doesn't change the support status of the [silverstripe/mssql](https://github.com/silverstripe/silverstripe-mssql) module, or the fact that we list IIS as a [supported platform](https://docs.silverstripe.org/en/3.3/getting_started/installation/other_installation_options/windows_iis7/).

### CODE REVIEW

**Comment by chillu** [comment]
Note that after we've come to a decision here, we also need to contact Microsoft to get the app unlisted from their WebPI store (https://webgallery.microsoft.com/apps/SilverStripeCMS)

**Comment by halkyon** [comment]
Do we even want to continue supporting IIS? I don't know the numbers of who manually installs SilverStripe on a Windows platform using IIS, but I don't imagine it's very high, just like WebPI.

**Comment by chillu** [comment]
Given we're not actively testing releases on IIS, and we don't have CI set up for it, our support is already limited in practice. The [server requirements](https://docs.silverstripe.org/en/4/getting_started/server_requirements/) page is quite outdated, probably listing some unsupported platforms (IIS 6?). And we could do a better job at describing what we consider "supported platforms" (Apache, nginx), and what's more community supported.

**Comment by dhensby** [comment]
@sminnee was looking into [appveyor ](http://appveyor.com) integration a while ago, which would have given us much more certainty over our windows support as well as MSSQL module stability. but I think it's fallen by the wayside.

**Comment by tractorcow** [comment]
I vote leave. :) It was near impossible to test, and doesn't give us much added value.

**Comment by chillu** [comment]
OK, we've got four core committers commenting favourably for this proposal (@dhensby, @tractorcow, @halkyon and myself). Everybody else had two weeks to weigh in. Can we merge this?

**Comment by halkyon** [comment]
👏

**Pull request merged**
