### PR TITLE
Expose sake via vendor/bin dir with composer

### PR DESCRIPTION
**Pull request by dhensby**
Well it's about time we could use `vendor/bin/sake`!

### CODE REVIEW

**Comment by dhensby** [comment]
Working for me locally:

```sh
[root@localhost html]# vendor/bin/sake dev/build

Building database vagrant using SilverStripe\SQLite\SQLite3 3.7.17


CREATING DATABASE TABLES

  + Checking database integrity
  + VACUUMing
 * MyDO
 * BlogCategory
 * BlogTag
 * File
 * SiteConfig
 * ChangeSet
 * ChangeSetItem
 * SiteTree
 * Group
 * LoginAttempt
 * Member
 * MemberPassword
 * Permission
 * PermissionRole
 * PermissionRoleCode
 * RememberLoginHash
 * Folder
 * Image
 * Page
 * Blog
 * BlogPost
 * ErrorPage
 * RedirectorPage
 * VirtualPage

CREATING DATABASE RECORDS

 * MyDO
 * SilverStripe\Blog\Model\BlogCategory
 * SilverStripe\Blog\Model\BlogTag
 * SilverStripe\Assets\File
 * SilverStripe\SiteConfig\SiteConfig
 * SilverStripe\Versioned\ChangeSet
 * SilverStripe\Versioned\ChangeSetItem
 * SilverStripe\CMS\Model\SiteTree
 * SilverStripe\Security\Group
 * SilverStripe\Security\LoginAttempt
 * SilverStripe\Security\Member
 * SilverStripe\Security\MemberPassword
 * SilverStripe\Security\Permission
 * SilverStripe\Security\PermissionRole
 * SilverStripe\Security\PermissionRoleCode
 * SilverStripe\Security\RememberLoginHash
 * SilverStripe\Assets\Folder
 * SilverStripe\Assets\Image
 * Page
 * SilverStripe\Blog\Model\Blog
 * SilverStripe\Blog\Model\BlogPost
 * SilverStripe\ErrorPage\ErrorPage
 * SilverStripe\CMS\Model\RedirectorPage
 * SilverStripe\CMS\Model\VirtualPage

 Database build completed!
```

**Comment by kinglozzer** [comment]
Not questions of this PR, but rather questions that this PR raises...

---

Looking at the contents of `sake`, it could do with some updates: 

- Now that we’ve moved framework into `vendor/`, the paths all look wrong (though I admit I’ve not tested it)
- There are legacy things in there, like references to sapphire, that we can probably ditch
- We explicitly check for `php` and `php5` binaries, but not `php7`
- Does the process control stuff actually work or have any real-world uses these days?

**Comment by dhensby** [comment]
Yes, sake could probably do with basically being removed and moving to just a PHP bin file and not guessing at php bin locations.

We'll leave that for now, though ;)

**Comment by tractorcow** [comment]
It's in :D

**Comment by chillu** [comment]
@dhensby Good stuff! Could you fix the docs for sake as well please?

**Comment by dhensby** [comment]
@chillu done in #7513

**Pull request merged**
