### PR TITLE
allow themed renderWith even if theme is disabled

### PR DESCRIPTION
**Pull request by sunnysideup**
```php
$this->renderWith(foo)
```
called while the user is editing the CMS (e.g. when creating a newsletter) often leads to unexpected results: the theme of the site is not being used and therefore no themed templates can be found because the CMS turns of the site's theme (for good reasons).  

This proposed addition to the renderwith method allows devs to render in theme style even if called from within the CMS (of other situations where the theme is disabled).

Maybe it will be better to allow it to work both ways - so that you can choose with or without theme. I am happy to resubmit of course.

Nicolaas

### CODE REVIEW

**Comment by sminnee** [comment]
@tractorcow @sunnysideup did we want to progress this one or close it off? Note that it would have to be rebased to the `3` branch.

**Comment by sunnysideup** [comment]
I am keen, but offer nothing because I am short of time. Sorry.

**Comment by kinglozzer** [comment]
If we’re adding this to 3, here’s an alternative suggestion that saves a few lines of code:

```php
Config::nest();
if ($forceTheme) {
    Config::inst()->update('SSViewer', 'theme_enabled', true);
}

// ... render stuff

Config::unnest();
```

As I type this I have a concern entering my mind, though: what’s the additional memory footprint of nesting config?

**Comment by sminnee** [comment]
Anyone who is keen to work on this feel free to re-open with an update.

**Pull request closed without merging**
