### PR TITLE
TEST ONLY - MAJOR: caching queries and dataobjects

### PR DESCRIPTION
**Pull request by sunnysideup**
TEST ONLY!

### CODE REVIEW

**Comment by GuySartorelli** [comment]
Please don't open pull requests that's aren't intended to be merged. You can link to the code in your fork without needing a pull request.

**Comment by sunnysideup** [comment]
Is there a way to run the tests without opening a pull request?

**Comment by GuySartorelli** [comment]
All unit and behat tests can be run locally, yes.

**Comment by GuySartorelli** [comment]
You could also run ci in your fork - and looking at the actions tab in your fork you did run it on push automatically

**Pull request closed without merging**
