### PR TITLE
Adding SVG to allowed file types

### PR DESCRIPTION
**Pull request by nickspiel**
Adding svg to allowed extensions array, this should be merged in conjunction with a change I am making to the htaccess file in the silverstripe-installer repo (also on 3 branch). I will link to this when I have completed the PR.

### CODE REVIEW

**Comment by nickspiel** [comment]
This PR is also required to be merged for this to work as the .htaccess file in the assets directory also disallows SVGs. https://github.com/silverstripe/silverstripe-installer/pull/106

**Comment by nickspiel** [comment]
Am I able to get some feedback on this? I need it pretty desperately for a project.

**Comment by jonom** [comment]
This seems like a harmless change to me - just curious though, for the project you need it for can't you just add SVG to the htaccess file after installation, and then to the config system like so?
```yml
File:
  allowed_extensions:
    - 'svg'
```
Don't think you should need this merged to use it on your own project? If you wait for this change to make a stable release you wouldn't see it until 3.3 is released I believe.

**Comment by nickspiel** [comment]
Ah nice! That works.

**Comment by dhensby** [comment]
Thanks

**Pull request merged**
