### PR TITLE
FIX for #5251 to address minor URL decoding/parsing bug.

### PR DESCRIPTION
**Pull request by patricknelson**
See issue #5251

Ping @tractorcow

### CODE REVIEW

**Comment by patricknelson** [comment]
p.s. Since so much logic is crammed here into `main.php` I'm not sure how I could apply good test coverage. Do you?

**Comment by sminnee** [comment]
This seems like a reasonable patch-release change. It won't affect the behaviour of "ordinary" URLs, and for the URLs that it does effect, current behaviour is clearly broken.

Yeah—there's not a lot we can do about writing testing for this code without adding more infrastructure; solving that feels like a problem for a more significant refactor on `master`.

**Comment by tractorcow** [comment]
Tested locally, and it seems fine.

**Comment by patricknelson** [comment]
Yep. Maybe this can be thrown into the pile for `v4.0` :sunglasses:

**Comment by tractorcow** [comment]
Better merge it up then...

**Comment by patricknelson** [comment]
Haha, yes sir. Well, then again, I'd have to code it up first and that just seems like actual work. I'll keep it in mind, though, since I routinely encounter this `main.php` file and end up thinking to myself "Why?!"

**Comment by patricknelson** [comment]
@tractorcow Re @sminnee comment from before:

> Yeah—there's not a lot we can do about writing testing for this code without adding more infrastructure; solving that feels like a problem for a more significant refactor on master.

I was thinking that a lot of the core framework files, particularly `main.php` and `Core.php` (among others) which make direct references to other files via `require_once()` statements point to a more fundamental issue which would relate tangentially to the test coverage of a bug like this. This is my thought process:

1. Find a way to restructure/abstract this code into classes, which requires
2. Having some basic autoloading so that the `require_once()` statements aren't necessary and files are no longer vulnerable to the special order of loading issues, which requires [possibly]
3. Doing some namespacing to assist with folder structure so that files are located properly, which ties into the mega-issue https://github.com/silverstripe/silverstripe-framework/issues/3548

Or am I thinking too broadly?

**Pull request merged**
