### PR TITLE
Tweak UploadField width for better alignment

### PR DESCRIPTION
**Pull request by jonom**
@kinglozzer quick-fix for https://github.com/silverstripe/silverstripe-framework/issues/3382
Thanks to @lerni.

screen shot 2015-07-16 at 10 17 13 am

### CODE REVIEW

**Comment by lerni** [comment]
oh didn't see all the comments in #3382 :+1: for this PR!

**Comment by chillu** [comment]
Does that work when nested in a `FieldGroup` or a `SelectionGroup`?

**Comment by jonom** [comment]
Let me just check tha- AARGGH! MY EYES!

silverstripe_-_edit_page

It does not work in a FieldGroup but it's not because of this PR - that's how it already looks. All I've done is increase the max-width of this field. Works fine in SelectionGroup.

**Comment by kinglozzer** [comment]
Looks good, `FieldGroup` has always been... like that...

Tested in `ToggleCompositeField` and it’s fine there too, build failure is completely unrelated. Thanks @jonom!

**Pull request merged**
