### PR TITLE
NEW: Support dot syntax in form field names

### PR DESCRIPTION
**Pull request by sminnee**
This change adds support for these in a few places.

 - Form::saveInto($record)
 - Form::loadDataForm($record)
 - Form::loadDataForm($_POST)

Fixes https://github.com/silverstripe/silverstripe-framework/issues/9163

## To do

 * [x] Documentation
 * [x] Tests

### CODE REVIEW

**Comment by sminnee** [comment]
Making as WIP as the tests need to be fixed, new tests need to be written, and docs

**Comment by emteknetnz** [comment]
This pull request hasn't had any activity for a while. Are you going to be doing further work on it, or would you prefer to close it now?

**Comment by sminnee** [comment]
I'm using this code in production via composer-patches so I'm definitely keen to see it make its way into mainline. I'll endeavour to get tests added and tests passing to make it mergeworthy in the next few weeks.

**Comment by chillu** [comment]
@sminnee Still keen on adding tests here?

**Comment by chillu** [comment]
I've put this through its paces, wrote some unit tests, and docs with extensive code examples that I've tested manually as well. Found a few functional gaps, e.g. the ability to get the field via `fieldByName()`. Note that the API overlaps between two use cases now: Using dots for nested `CompositeField` (e.g. `TabSet`), and using dots for relationship saving. One natural limitation is that you can't do both:

```php
new FieldSet([
  new TextField('My.Field'),
  new TabSet('My', [
      new TextField('Field'),
  ])
]);
```
I think that's acceptable, and very unlikely to happen in the real world.

I've also considered the security aspects of this, and can't fault it. You'll need to opt-in to this behaviour by whitelisting the relationships which are allowed to be written. There's some sensitivity about explicitly checking `can*()` permissions on the nested relationships, and being careful about create vs. update (since `DataObject->getComponent()` will auto-create a non-existent relationship). This is clearly flagged in the tutorial.

@emteknetnz @dhensby @sminnee Good to merge?

Marginally related gotcha: Some unrelated `FormTest` failures caused by https://github.com/silverstripe/silverstripe-framework/pull/9948.

**Comment by chillu** [comment]
Alright got a thumbs up from a core committer (Dan), and the work is semi peer reviewed, so I'm calling this done! Just added another commit with a changelog entry to raise the visibility of the tutorial.

**Pull request merged**
