### PR TITLE
Try Catch for embeded media - Backport to 4.6

### PR DESCRIPTION
**Pull request by emteknetnz**
Issue https://github.com/silverstripe/silverstripe-framework/issues/9601

Backport of https://github.com/silverstripe/silverstripe-framework/commit/3bf89b2d13bf882803f5f5409284c76b41166c6c

### CODE REVIEW

**Comment by ScopeyNZ** [comment]
I've just cherried stuff like this in the past without a PR 😅

**Comment by brynwhyman** [comment]
Thanks guys :)

**Comment by camfindlay** [comment]
Does this mean this issue is fixed in 4.6.0 or a pending 4.6.1 release?

**Comment by emteknetnz** [comment]
@camfindlay pending 4.6.1 release

You can optionally use this straight away if you pin the merge commit in your `composer.json`, though not being an official release it means it hasn't gone through our full regression suite.  i.e. (apologies if I have the syntax wrong)

`"silverstripe/framework": "4.6.x-dev#87200439be8bdc88c1182aa47356c26b5920bee4"`

**Comment by camfindlay** [comment]
Thanks @emteknetnz eta on 4.6.1?

**Comment by emteknetnz** [comment]
@camfindlay We've had interest from a few different parties regarding this particular fix, so we've just tagged 4.6.1 now

https://github.com/silverstripe/silverstripe-framework/releases/tag/4.6.1

**Comment by christopherdarling** [comment]
> @camfindlay We've had interest from a few different parties regarding this particular fix, so we've just tagged 4.6.1 now
> 
> https://github.com/silverstripe/silverstripe-framework/releases/tag/4.6.1

Any chance of 4.6.1 recipe releases too?

**Comment by ScopeyNZ** [comment]
It's a bit more of an ordeal to do a full recipe release, but if you want you can "unpack"/inline a recipe into your composer.json by using `composer require-recipe`.

**Pull request merged**
