### PR TITLE
adding a space before casting into a different type

### PR DESCRIPTION
**Pull request by spekulatius**

### CODE REVIEW

**Comment by spekulatius** [comment]
Hello @tractorcow ,

can you review this one as well? Thanks :)

Cheers,
Spek

**Comment by tractorcow** [comment]
Why is this the best convention? Which coding standard are you following?

**Comment by spekulatius** [comment]
Hello @tractorcow ,

I always thought it was in the SS coding conventions. But I couldn't find it. I must have kept this as a habit from former work. It improves the readability IMHO. What do you think?

Spek

**Comment by tractorcow** [comment]
I can merge this, but I don't think anyone will follow this convention. :)

**Pull request merged**
