### PR TITLE
Better Zend references

### PR DESCRIPTION
**Pull request by assertchris**
Good ol' Composer...

### CODE REVIEW

**Comment by kinglozzer** [comment]
This will break things for people who install without using composer (i.e. zip archive), won’t it? Unfortunately we still need to support that :(

**Comment by assertchris** [comment]
Ah, no ways. That's a good point and makes me sad.

**Comment by chillu** [comment]
Shouldn't we just include `vendor/composer/autoload.php` stuff in the ZIP download by default?

**Comment by kinglozzer** [comment]
@chillu I thought that was something that had only been proposed, but looking at the zip archive from http://www.silverstripe.org/software/download/ it’s already in place!

**Comment by assertchris** [comment]
Hey, wait...Does that mean this change could actually happen?

**Comment by kinglozzer** [comment]
@assertchris the problem is that it’s not currently _required_, so this would be a breaking change for anyone who didn’t upload `vendor/` to their server and dropped in the new `framework/` expecting it to work.

I’d be in favour of _requiring_ this (i.e. requiring people without composer to download from silverstripe.org) in future SS versions so we can take advantage of stuff like this, though that’s probably a dev-list discussion of its own!

**Comment by assertchris** [comment]
Yip - perhaps a 4.0 thing, if errybody likes the idea of classmap over `require`...

**Comment by tractorcow** [comment]
I don't think this is a breaking change, but it wouldn't hurt to do it in 4.0 anyway.

**Pull request closed without merging**
