### PR TITLE
Add SSL capability to PDO MySQL connector

### PR DESCRIPTION
**Pull request by johndalangin**
SSL parameters will be read from mysite/_config.php.

### CODE REVIEW

**Comment by johndalangin** [comment]
fixes #7077

**Comment by dhensby** [comment]
Thanks for taking the time to do this @johndalangin 

This feels more like a new feature than a bug fix, so this should be targeted at the `3` branch. You'll have to close this PR and open a new one as you've opened this PR directly from your 3.6 branch. In the future you should create branches specifically for the PR ([see our guide](https://docs.silverstripe.org/en/4/contributing/code/#step-by-step-from-forking-to-sending-the-pull-request)).

Also, this allows users to utilise the parameters but provides no way to supply them (there are no new ss environment settings being added or checked for in [`configureFromEnv.php`](https://github.com/silverstripe/silverstripe-framework/blob/3/conf/ConfigureFromEnv.php)).

**Comment by johndalangin** [comment]
Thanks @dhensby for providing very helpful tips. It's my pleasure to contribute to the Silverstripe Project. :) 

I will review the guidelines and redo the work. I will be submitting a new PR by tomorrow.

Thank you!

**Comment by chillu** [comment]
Also, can you please find a place to document this in `framework/docs`?

**Comment by dhensby** [comment]
I'm going to close this and way for the new PR.

Thanks

**Comment by johndalangin** [comment]
Hi @chillu, no problem, I'll include slugs for `configurefromenv` _ss.environment.php and maybe the `security` part of the docs with "Enabling remote SSL connections for PDO MySQL".

Thanks.

**Comment by johndalangin** [comment]
@dhensby No problem, I'll ping you once the new PR is up

Thank you.

**Comment by johndalangin** [comment]
@dhensby @chillu Also, I noticed this morning that `silverstripe/installer` has it's own PDOConnector. I'll go about making a PR on that as well since the change to `PDOConnector.php` on `silverstripe/framework` still does not enable SSL connections on the installer.

**Comment by dhensby** [comment]
@johndalangin there's no PDO connector in installer :/ just the config to get started using it.

**Pull request closed without merging**
