### PR TITLE
DOCS fix DataList::filter example

### PR DESCRIPTION
**Pull request by christopherdarling**

### CODE REVIEW

**Comment by ScopeyNZ** [comment]
I'm pretty sure these are functionally equivalent?

https://github.com/silverstripe/silverstripe-framework/blob/350888bf502ef1b79693b0e794745ea3593fdd71/src/ORM/DataList.php#L389-L396

**Comment by christopherdarling** [comment]
That's true, I guess the formatting of the code example could either be the way I've done the PR or may be clearer if formatted in a single line like the others? `>filter('FirstName' => ['Sam', 'Sig']);`

Either way, happy to close if you're happy with the current docs

**Comment by michalkleiner** [comment]
I'd say there should be a preferred convention defined by the core team and then all docs, classes etc. using that one.

**Comment by maxime-rainville** [comment]
> Both methods are acceptable and common, i.e. filter($key, $value[s]) and filter($predicates). 

I agree that both usage are useful and we shouldn't encourage one over other. [Method overloading is a common feature](https://www.geeksforgeeks.org/c-sharp-method-overloading/) of many languages. The concept is not natively supported in PHP and requires a bit of manual type checking with default parameters, so that's possibly why PHP developers are not as familiar with it.

My instinct would be to close this PR.

**Pull request closed without merging**
