### PR TITLE
Revert "BUG Fix duplicate files being included in case of flush"

### PR DESCRIPTION
**Pull request by tractorcow**
Reverts silverstripe/silverstripe-framework#4720

### CODE REVIEW

**Comment by tractorcow** [comment]
@hafriedlander your revert didn't revert the 3.1 branch properly. :D

**Comment by dhensby** [comment]
@tractorcow how come this got reverted? Is the original bug still present?

**Comment by tractorcow** [comment]
Because the solution was wrong; This fix works fine for static files, but would break on any php minified scripts. E.g. `/minifier.php?script=myfile.js`

**Comment by dhensby** [comment]
Fun stuff! so we've identified this as a bug and know the cause, we just need a fix, yes?

Do we have an open issue?

**Comment by tractorcow** [comment]
I've re-opened https://github.com/silverstripe/silverstripe-framework/issues/4553

**Pull request merged**
