### PR TITLE
FIX Files should only report as "existing" if the file actually exists

### PR DESCRIPTION
**Pull request by dhensby**
see https://github.com/silverstripe/silverstripe-framework/pull/4060

### CODE REVIEW

**Comment by tractorcow** [comment]
Er, lots of test failures. :D Sorry @dhensby .

Given that this issue has been well-discussed already, I'm ready to merge it, once tests are fixed.

**Comment by dhensby** [comment]
OK. Got the tests passing. turns out this change just uncovered some bad fixtures, an issue with `Image_Cached` and a chicken and egg filesystem problem with `UploadFieldTest` fixtures

Travis is having a bad time on the legacy infrastructure, but tests are passing locally:

```sh
[root@localhost html]# vendor/bin/phpunit framework/tests
PHPUnit 3.7.38 by Sebastian Bergmann.

Configuration read from /vagrant/www/phpunit.xml.dist

.............................................................   61 / 1591 (  3%)
...................................I.........................  122 / 1591 (  7%)
.........................I...................................  183 / 1591 ( 11%)
..I..........................................................  244 / 1591 ( 15%)
.............................................................  305 / 1591 ( 19%)
.............................................................  366 / 1591 ( 23%)
.............................................................  427 / 1591 ( 26%)
.............................................................  488 / 1591 ( 30%)
.............................................................  549 / 1591 ( 34%)
......................................I......................  610 / 1591 ( 38%)
.............................................................  671 / 1591 ( 42%)
.............................................................  732 / 1591 ( 46%)
.............................................................  793 / 1591 ( 49%)
.............................................................  854 / 1591 ( 53%)
.............................................................  915 / 1591 ( 57%)
.............................................................  976 / 1591 ( 61%)
............................................................. 1037 / 1591 ( 65%)
............................................................. 1098 / 1591 ( 69%)
............................................................. 1159 / 1591 ( 72%)
..........SSSSSSSSSSSSSSSSS.................................. 1220 / 1591 ( 76%)
.............SS.............................................. 1281 / 1591 ( 80%)
............................................................. 1342 / 1591 ( 84%)
............................................................. 1403 / 1591 ( 88%)
............................................................I 1464 / 1591 ( 92%)
............................................................. 1525 / 1591 ( 95%)
............................................................. 1586 / 1591 ( 99%)
....

Time: 5.56 minutes, Memory: 141.50Mb

OK, but incomplete or skipped tests!
Tests: 1590, Assertions: 6580, Incomplete: 5, Skipped: 19.
```

**Comment by tractorcow** [comment]
I believe you, but yikes, travis =O We better fix that soon.

Should I merge up the changes to .travis.yml from 3.1 branch?

**Comment by dhensby** [comment]
@tractorcow I think a merge up is needed. I think they are trying to force people off of the legacy system, hey?

**Comment by tractorcow** [comment]
Maybe someone in the UK with energy could do it? :dancer: 

Also please do cms.

**Comment by tractorcow** [comment]
See https://github.com/silverstripe/silverstripe-framework/commit/2036f7e6c21a024d51ad0e0b2ae19aba25ea1e61  for those interested in what the fix was.

**Comment by dhensby** [comment]
Sure, I'll get joel on it

**Comment by dhensby** [comment]
ready @tractorcow

**Comment by tractorcow** [comment]
Squashed and merged with https://github.com/silverstripe/silverstripe-framework/commit/f32fa4631ac91ea52962e1cf1c631266816fd41c

**Comment by tractorcow** [comment]
Hm, I found a regression in this pull request.

When you create fixtures during unit testing, if all parent folders for a file don't exist, the file will end up being placed at the top level, meaning that text fixtures don't end up in the right locations.

**Comment by tractorcow** [comment]
Fix at https://github.com/silverstripe/silverstripe-framework/pull/4719

**Pull request closed without merging**
