### PR TITLE
Lazy Loaded Fields break when initial query runs in default stage

### PR DESCRIPTION
**Pull request by crgwbr**
This pull request fixes issue #3182 and adds a test case for it.

### CODE REVIEW

**Comment by sminnee** [comment]
Did you want to have a go at implementing @tractorcow's suggestions, @crgwbr ?

**Comment by tractorcow** [comment]
Please rebase on master... the code has changed a bit, but your fix is still valid. :D

I don't mind if you don't implement my feedback, but please rebase.

**Comment by crgwbr** [comment]
Sorry for the delay, it's been a while since I've worked on this project. I'll try and get to doing this rebase soon.

**Comment by tractorcow** [comment]
Rebased at https://github.com/silverstripe/silverstripe-framework/pull/5447

**Comment by tractorcow** [comment]
@crgwbr I think it is us who should apologise for the delay. :)

**Pull request closed without merging**
