### PR TITLE
Update buttons to new flat bootstrap style

### PR DESCRIPTION
**Pull request by wilr**
NOTE: MOVED TO OPENSOURCERERS REPO!

Upgrading the CMS admin interface to use the new buttons and remove `ss-ui` references. Also upgrading to use the new font icon style.

Removes the use of jQuery UI Button (yay!)

Have left the old styles in the stylesheet to make sure older buttons will have some form of styling.

Old: screen shot 2016-11-30 at 11 34 19 am

New: screen shot 2016-12-01 at 9 29 33 am

screen shot 2016-12-01 at 9 20 43 am

Marking as WIP for @clarkepaul to review. Requires branches for:

~~CMS: https://github.com/wilr/silverstripe-cms/tree/feature/ui-button-refresh~~
~~SiteConfig: https://github.com/silverstripe/silverstripe-siteconfig/pull/42~~

PR's moved to Opensourcers repo:
https://github.com/open-sausages/silverstripe-siteconfig/tree/features/4.0/ui-button-refresh
https://github.com/open-sausages/silverstripe-cms/tree/features/4.0/ui-button-refresh
https://github.com/open-sausages/silverstripe-framework/tree/features/4.0/ui-button-refresh
*Also the same branch names on:*
frameworktest
reports
assetadmin

## Todo

- [x] Save / Publish button transitions

### CODE REVIEW

**Comment by clarkepaul** [comment]
Whoot! :)

**Comment by wilr** [comment]
Save and publish buttons styled.
screen shot 2016-12-01 at 5 40 31 pm

**Comment by tractorcow** [comment]
Nice. :)

Keep in mind that some behat tests may rely on certain classes in order to detect buttons.

**Comment by wilr** [comment]
Updated the import CSV design, tidied up alignments and also updated the permission icons to use the new flat style.
screen shot 2016-12-07 at 3 46 33 pm
screen shot 2016-12-07 at 3 46 18 pm

screen shot 2016-12-07 at 3 52 59 pm

**Comment by clarkepaul** [comment]
I'll give it a peer review tomorrow if no one beats me to it :)

**Comment by chillu** [comment]
Ooooh, shiny!

**Comment by clarkepaul** [comment]
Clicking on "Save" throws an error:
image
image

**Comment by wilr** [comment]
@clarkepaul Looks like a PHP error on your end, page saves fine here. Got any modules perhaps?

**Comment by clarkepaul** [comment]
not that I know of, will do all the standard checks and see what happens.

**Comment by clarkepaul** [comment]
na not sure whats going on :(. I've got the three banches checked out framework/cms/siteconfig, was there other ones?

**Comment by clarkepaul** [comment]
@wilr I can continue without saving/publishing, I'm going to make some changes/improvements but do you mind if I add these to the opensourcerers repo and make a PR from there instead?

**Comment by clarkepaul** [comment]
Some of the issues I'm fixing:
image

Actions should have green text and tick on save:
pasted_image_8_12_16__6_53_pm
image

Wrong background/selected colours:
pasted_image_8_12_16__6_12_pm

**Comment by clarkepaul** [comment]
@wilr I think its just the main save and publish icons now, they should alternate between the tick icon/colour and their respective default icons. Any chance you could look at that if your in soon? I'll try to rebase tomorrow ready for proper review and hopefully merge.

**Comment by clarkepaul** [comment]
Browser tested and ready for another review, perhaps @flamerohr ?

**Comment by chillu** [comment]
@wilr @tractorcow I can still find 54 occurrences of `ss-ui-button` in core after all of this would be merged, with 15 of these in SCSS files (so potentially still affecting styling) - is there leftover work we need to track?

**Comment by clarkepaul** [comment]
This PR was to remove the dependency on the Jquery-ui for buttons but we should have removed all left over unused classes in core. I think someone advised that there could be modules which may be using the styling if hardcoded with the classes, and said to leave them from memory?

**Comment by chillu** [comment]
> I think someone advised that there could be modules which may be using the styling if hardcoded with the classes, and said to leave them from memory?

We've done so many CSS changes in SS4 that I don't think we need to keep extraneous CSS classes around. I've created a follow up ticket: https://github.com/silverstripe/silverstripe-framework/issues/6479

**Pull request closed without merging**
