### PR TITLE
BUG Prevent url= querystring argument override

### LINKED ISSUE #1368: [2009-03-09] Avoid ?url= GET parameter redirection if not on sapphire.php script
created by: @chillu (ischommer)
assigned to: @kmayo-ss (kmayo)
created at: 2009-03-09
original ticket: http://open.silverstripe.org/ticket/3684

---

This is an interesting one, raised by one of our partners: you can redirect to different internal URLs by using the "url" GET parameter.

Example (works on standard installation): ```/about-us/?url=contact-us``` will show the "contact-us" page, not "about-us". This has several implications:

 * On a sufficiently long URL, this might be used to obfuscate the target page
 * It might be used to create attacks on the page-rank of a target page - Google will index these links and rate them as duplicate content, which decreases pagerank

I would suggest to limit parsing of the ?url parameter to scenarios where REQUEST_URI starts with <baseurl>/sapphire/main.php

@Sam: Thoughts? How does this get influenced by your work on URLs without mod-rewrite (index.php/about-us)?

### PR DESCRIPTION
**Pull request by tractorcow**
fixes #1368

The issue can be detected whenever `$_SERVER['QUERY_STRING']` contains two `url=.*` fragments, where the leading fragment is the one added via .htaccess, and the other the one appended to the url.

Existing url parsing functionality (built on top of parse_str) has been refactored to help and solving this issue, plus a bit of duplicate code cleanup.

I originally attempted to resolve this issue via htaccess, but decided against this, since this issue also affected IIS, and many installations will use custom htaccess rules which would not be immediately upgradable.

Tested on apache (mod_php), iis7, php built in server.

### CODE REVIEW

**Comment by chillu** [comment]
So that's solving an inconsistency, right? `/mypath?url=fakepath` will currently match the `fakepath` route, right? Since devs might limit URL access through htaccess, this might even be considered a security flaw?

I'd prefer to solve this in master by a new routing implementation which doesn't rely on a `url` GET parameter in the first place, but this would do for the meantime - since its not an API change, I'm happy for it to go into 3.1.

**Comment by tractorcow** [comment]
travis failed due to https://github.com/silverstripe/silverstripe-framework/issues/3749, I'll restart and will expect it to pass. :)

**Comment by tractorcow** [comment]
Tests are fine now anyway. :)

**Comment by tractorcow** [comment]
This still fixes the issue :D

**Comment by tractorcow** [comment]
Ah thanks :D

**Pull request merged**
