### PR TITLE
Behat: Wait until CMS loading overlay is removed

### PR DESCRIPTION
**Pull request by chillu**
This makes tests more robust at the expense of an additional
check with every step. The "ajax steps" logic works similarly,
but does not respect the loading indicator. While this logic
waits for a short time after ajax requests are finished,
in some cases that isn't enough time for the browser to
process the response and remove the loading indicator.
Since the "ajax steps" logic applies to operations outside of the CMS
as well, we can't add the loading indicator check there.

Note: It would be cleaner to create a JS API for checking the loading
state of the CMS, but I'd consider that scope creep here ;)

### CODE REVIEW

**Comment by chillu** [comment]
@tractorcow Any idea why the branch alias isn't picked up here? Looks like travis-support creates it

**Comment by tractorcow** [comment]
Are you referring to the framework appearing as 3.x-dev instead of 3.2.x-dev? I think that could be a feature of the framework repo being the one that is actually tested. That being said, is there any harm in how it's working currently? :D

**Comment by chillu** [comment]
@tractorcow Re-ran tests, and they're still passing. I think the branch alias problem resolved itself in the meantime. Wanna merge?

**Comment by tractorcow** [comment]
Small bugfix for cms errors at https://github.com/silverstripe/silverstripe-framework/pull/5370

**Pull request merged**
