### PR TITLE
ENH Correctly parse SomeClass::class syntax in textcollection

### PR DESCRIPTION
**Pull request by GuySartorelli**
This is a pretty naive approach - there was some discussion in the parent issue about refactoring all this to use an existing php parser, but this was quicker and got the job done for now.

It makes the same assumptions mentioned in https://github.com/silverstripe/silverstripe-framework/issues/7647#issuecomment-347139883:
- `SomeClass` has been imported via a use statement, or;
- `SomeClass` exists in the same namespace (global or otherwise) as the current class

## Parent issue
- https://github.com/silverstripe/silverstripe-framework/issues/7647

### CODE REVIEW

**Comment by michalkleiner** [comment]
Do we want to add an anonymous class to the test as well since we recently had an issue with anonymous class instantiation? It might not be directly relevant but possibly worth having in the tests.

**Comment by GuySartorelli** [comment]
I think this is a very different scenario than the injector issue we had - while it does make sense in some situations to use injector to replace some concrete class or service with an anonymous class, I can't see any scenario where someone would want to use an anonymous class as a key for translations. Honestly I think it's totally fine to just leave that behaviour undefined. It's not something we would want to support, I don't think.

I will add tests for it if you insist or someone else agrees with you, though I'd need some guidance as to what the expected behaviour should be in order to test it.

**Comment by michalkleiner** [comment]
Nah, all good, was just a question if it made sense.

**Review by michalkleiner — APPROVED** [review]
Do we want this as a fix in 4.12 as it fixes a bug?

**Comment by GuySartorelli** [comment]
Does it fix a bug or does it just give the text collection parser an ability it didn't have before?
Either way I'm not terribly fussed as to whether it gets into 4.12 or not.... not sure how others feel.

**Comment by michalkleiner** [comment]
Let's leave the target branch as is.

**Pull request merged**
