### PR TITLE
FIX | IntlLocales implementation return country codes in upper case

### PR DESCRIPTION
**Pull request by dnsl48**
To conform with ISO 3166-1 alpha-2, country codes should be in Upper case

Fixes https://github.com/silverstripe/silverstripe-framework/issues/8968

### CODE REVIEW

**Comment by robbieaverill** [comment]
I'm lazy - do you have a reference to the spec that requires this? 😆

**Comment by dnsl48** [comment]
haha, sure. the actual standard document cost money, but here's its wiki page - https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

**Comment by robbieaverill** [comment]
Cheers. All the examples on that page are uppercase, so I guess it makes sense.

@tractorcow worked on this part of the code most recently - any thoughts?

**Comment by dnsl48** [comment]
> All the examples on that page

those are not merely examples. They are actual codes described by the standard.

**Comment by tractorcow** [comment]
Just make sure you check any core places that use that method, and check they are unaffected by the case change.

**Comment by dnsl48** [comment]
> Just make sure you check any core places that use that method, and check they are unaffected by the case change.

I could not find any usage of this method in core (checked everything which goes with the installer recipe).

**Comment by robbieaverill** [comment]
Fluent might be an example that uses it @dnsl48

**Comment by dnsl48** [comment]
> Fluent might be an example that uses it @dnsl48

oh, sure, will check it out, thanks :+1:

**Comment by GuySartorelli** [comment]
There's no branch to retarget this to yet - this PR will be closed when the master branch is deleted. But it's attached to the issue, which has the api-break label on it, so we'll likely look at it when it comes time to start working on CMS 6.

**Pull request closed without merging**
