### PR TITLE
NEW: Add visibility updates to `upgrade.yml`

### PR DESCRIPTION
**Pull request by bergice**
This will make the inspect upgrader command ensure these visibilities are used

### CODE REVIEW

**Comment by maxime-rainville** [comment]
I'm just thinking here that if you are running an older version of the upgrader that doesn't know about visibility you'll get a boat load of warnings when running.

image

Do you think there's an easy way around this to avoid displaying all those warnings?

@chillu Would you consider this an acceptable down side?

**Comment by bergice** [comment]
> I'm just thinking here that if you are running an older version of the upgrader that doesn't know about visibility you'll get a boat load of warnings when running.
> 
> image
> 
> Do you think there's an easy way around this to avoid displaying all those warnings?
> 
> @chillu Would you consider this an acceptable down side?

Composer require? :D

**Comment by maxime-rainville** [comment]
The problem is that until now, the upgrader always expected the `warning` entries in `.upgrade.yml` to have a `message` key. So if someones gets the updated framework `.upgrade.yml` with the old upgrader installed, they'll get that big list of PHP notice.

**Comment by chillu** [comment]
I don't think this is appropriate for the `warnings` key. Warnings are things we can't fix automatically, but still tell users about. The config stuff *can* be fixed automatically, and just causes upgrader log output like all other rewrites. I'd recommend creating a new toplevel key in `.upgrade.yml`.

**Pull request closed without merging**
