### PR TITLE
API Move CMSPreviewable to admin module

### PR DESCRIPTION
**Pull request by GuySartorelli**
This isn't used for anything without `silverstripe/admin` installed, so it doesn't belong in framework.

See also https://github.com/silverstripe/silverstripe-admin/pull/1340

## Parent issue
- https://github.com/silverstripe/silverstripe-admin/issues/1339

### CODE REVIEW

**Comment by kourawealthtech** [comment]
Some time ago I wanted to have a preview similar to the one the Pages have.

My thoughts were: imagine a class is `CMSPreviewable`, and this makes the CMSEditForm automatically turn into a split-screen similar to the Pages editor...

However, that was not the case, but could be handy sometimes - when the edited DataObject can be represented as HTML.

**Comment by gurucomkz** [comment]
Some time ago I wanted to have a preview similar to the one the Pages have.

My thoughts were: imagine a class is `CMSPreviewable`, and this makes the CMSEditForm automatically turn into a split-screen similar to the Pages editor...

However, that was not the case, but could be handy sometimes - when the edited DataObject can be represented as HTML.

**Comment by GuySartorelli** [comment]
That's something that can be done easily as-of 4.11.0: https://docs.silverstripe.org/en/4/changelogs/4.11.0/#cms-preview
The caveat that this PR (along with the other PRs linked in the associated issue) resolve is that you need silverstripe/cms installed to use it - which most projects will anyway.

**Comment by gurucomkz** [comment]
Thank you for the pointer! 

I agree on the subject, though.

**Comment by GuySartorelli** [comment]
I've changed my mind about moving `CMSPreviewable` - it makes more sense to leave where it is. That way modules can include models that are previewable if silverstripe/admin is installed on the project, but they don't _necessarily_ have to have admin as a dependency for that model to be useful.

**Pull request closed without merging**
