### PR TITLE
Issue #2854: Permit ViewableData children to avoid caching 

### PR DESCRIPTION
**Pull request by g4b0**
Useful for frontend Session work. The issue: https://github.com/silverstripe/silverstripe-framework/issues/2854

### CODE REVIEW

**Comment by g4b0** [comment]
Hey, any news about this PR?

**Comment by tractorcow** [comment]
@dhensby has been working on an updated ViewableData for 4.0. Maybe see whether he can incorporate this into his pr?

**Comment by tractorcow** [comment]
This PR probably couldn't go into 3.1 anymore... since we've adopted semantic versioning any new api should probably go into 3.2 (3 branch) at the least.

**Comment by dhensby** [comment]
@g4b0 I need to look at this a bit. I'm not sure I fully understand what the problem is here (mostly because I haven't familiarised myself with this issue).

NB: the ViewableData stuff I'm working on is here #3924

**Comment by g4b0** [comment]
@dhensby the problem is simple: if you store a DataObject in session (for example an Ecommerce Cart), cached values will override real values.
An example in my issue: https://github.com/silverstripe/silverstripe-framework/issues/2854

**Comment by tractorcow** [comment]
It would be better to allow caching to be overridden, rather than simple disabled or enabled as needed via a flag. That way you could implement a better caching mechanism in your subclass, if the default isn't useful enough.

**Comment by tractorcow** [comment]
Also, refactoring the caching into a protected method could make this PR still eligible for 3.1 (since it's a simple refactor, rather than a new mechanism).

**Comment by g4b0** [comment]
It's not so easy, since SS internals calls ViewableData::obj that caches the DO whit it's own logic, so which method are you thinking to refactor?

**Comment by tractorcow** [comment]
Check out https://github.com/silverstripe/silverstripe-framework/pull/3955

Its preferable to customise behaviour using code, rather than flags with explicit behaviour coded in behind it, as the developer has a lot more control over how the overriding class behaves. It some cases it may not be sufficient to simply turn caching on or off, but rather it may be necessary to customise other elements of the caching mechanism (e.g. the caching store, lifetime, etc).

**Comment by tractorcow** [comment]
Moved this PR to the 3 branch (3.2) https://github.com/silverstripe/silverstripe-framework/pull/3985

**Pull request closed without merging**
