### PR TITLE
MINOR Empty YAML config causes invalid argument error

### PR DESCRIPTION
**Pull request by dhensby**
This fixes an issue where an empty yml config file causes the `ConfigManifest` to throw an invalid argument error for the foreach.

### CODE REVIEW

**Comment by dhensby** [comment]
Ok, once the second commit passes, I'm happy to squash. Just using 2 commits to prove the bug.

Feedback, please?

**Comment by stevie-mayhew** [comment]
I've made this change in local installs before and support it going into the core - its especially frustrating when a third party module has this incorrectly configured (such as here: https://github.com/lekoala/silverstripe-mandrill/pull/2)

Although adding a new line fixes the issue, same as with the _config.php file.

**Comment by willmorgan** [comment]
:+1:

**Comment by hafriedlander** [comment]
Looks good, and I don't think there's any BC risk. There's no explicit test here though, just changes to another test that cause that test to break without the fix (so if we did re-break it somehow we wouldn't get a nice "Empty fragment test failed" message, we'd just get an unhelpful error).

**Comment by dhensby** [comment]
@hafriedlander true. The tests for the ConfigManifest are... interestingly written. I haven't got my head around it.

Also, as it's just a PHP warning for the current bug, it'd be a pain to catch and we'd get this error anyway. Not sure how we'd go about writing a specific test to make sure we don't get an invalid argument warning

**Comment by dhensby** [comment]
Also, that'd just be testing a very specific implementation bug (ie: it'd just make sure that the code didn't throw a warning) which is using our knowledge of the fact that a foreach is being used.

If the function was re-written then the test would be too perscriptive. Ultimately, we just want to know that all the existing tests pass with empty yml files, not that this function doesn't explicitly throw this error. Or do I have the wrong end of the stick?

**Comment by sminnee** [comment]
Let's merge this into the `3.3` branch, eh?

**Comment by tractorcow** [comment]
@dhensby can you please re-open this on 3.3?

**Pull request closed without merging**
