### PR TITLE
Docs: Fixed Typo

### PR DESCRIPTION
**Pull request by Meeeeeeow**
Changed 'Gudes' to 'Guides'

### CODE REVIEW

**Comment by tractorcow** [comment]
Gudes enough for me

**Comment by SpiritLevel** [comment]
You've Gudes to be kidding ;P

**Comment by tractorcow** [comment]
He that brings the gudes hath surely a right to dispose of the gear.

**Comment by SpiritLevel** [comment]
Gudes god...enough already :P

**Comment by tractorcow** [comment]
Will merge once the tests pass...

**Comment by scott1702** [comment]
Gudes to go @tractorcow

**Pull request merged**
