### PR TITLE
FIX mark a successful login attempt when completing a password reset

### PR DESCRIPTION
**Pull request by wilr**
## Description

See issue #10100

## Manual testing steps

* Lock yourself out of a site (5 password fails)
* Reset your password via 'Forgot Password'
* Password reset fails as user is 'Locked out'

## Issues

- #10100

## Pull request checklist

- [x] The target branch is correct
    - See [picking the right version](https://docs.silverstripe.org/en/contributing/code/#picking-the-right-version)
- [x] All commits are relevant to the purpose of the PR (e.g. no debug statements, unrelated refactoring, or arbitrary linting)
    - Small amounts of additional linting are usually okay, but if it makes it hard to concentrate on the relevant changes, ask for the unrelated changes to be reverted, and submitted as a separate PR.
- [x] The commit messages follow our [commit message guidelines](https://docs.silverstripe.org/en/contributing/code/#commit-messages)
- [x] The PR follows our [contribution guidelines](https://docs.silverstripe.org/en/contributing/code/)
- [x] Code changes follow our [coding conventions](https://docs.silverstripe.org/en/contributing/coding_conventions/)
- [x] This change is covered with tests (or tests aren't necessary for this change)
- [x] Any relevant User Help/Developer documentation is updated; for impactful changes, information is added to the changelog for the intended release
- [x] CI is green

### CODE REVIEW

**Review by GuySartorelli — CHANGES_REQUESTED** [review]
Sorry it's taken so long to review this.

Looks sensible to me, but it should be conditional against `Security::config()>get('login_recording')` - see `MemberAuthenticator::recordLoginAttempt()`

**Comment by wilr** [comment]
@GuySartorelli Looking at that, if you make it conditional then you would still hit the issue if you had `login_recording` set to false, but `lock_out_after_incorrect_logins` set to true.

**Comment by GuySartorelli** [comment]
I'm okay with it being conditional against both of those, if that's the case. Though my understanding is that this bug can't happen if `login_recording` is set to false, because it won't be writing any login attempt records at all.

**Comment by wilr** [comment]
@GuySartorelli updated accordingly!

**Review by GuySartorelli — APPROVED** [review]
LGTM. Thanks for making that change so quickly.

**Pull request merged**
