### PR TITLE
fixing examples

### PR DESCRIPTION
**Pull request by spekulatius**
PSR-2 style for examples

### CODE REVIEW

**Comment by spekulatius** [comment]
Hello @dhensby 

do you want to merge this in quickly?

Cheers,
Spek

**Comment by tractorcow** [comment]
That's not actually psr-2 though :) Or did you just mean tab to space conversion?

**Comment by tractorcow** [comment]
I'm not sure why this is going into 3.1 branch; Is there a context that I'm missing?

**Comment by dhensby** [comment]
Hmm. How does out docs viewer like the space changes?

**Comment by tractorcow** [comment]
I think it works with 4xspaces the same as it does tabs.

**Comment by SpiritLevel** [comment]
Happy New Year SilverStripers! I hope everyone is relaxed and refreshed, especially after the stunning holiday weather we have had here in NZ. 

@tractorcow, @dhensby...quick question: Is the aim to eventually have all SS code strictly following PSR-2 ? Is there a summary or discussion of which parts of PSR-2 you want SS to strictly adhere to ? 
I have noticed that a lot of SS code has 8 spaces but PSR-2 only requries 4, and that PSR-2 requires opening "{" to be on a new line whereas SS typically leaves this on the same line as the class or function declaration. There are other things as well. I am reading a lot of the SS internal code lately and would be happy to convert to PSR-2 as I go. I don't want to irritate you with a flood of PRs so if you let me know what you'd like done, I'd be happy to chip away at it :) Or, are you going to get helpfulrobot onto it ?

**Comment by tractorcow** [comment]
> Is the aim to eventually have all SS code strictly following PSR-2 ?

Yes, but it'll be a gradual adoption rather than immediate. I expect some non-psr-2 names will stick around for the time being.

Framework is currently not psr-2 at all, but we'll do a reformat before releasing 4.0.

**Comment by SpiritLevel** [comment]
OK...Master only :) 

Is it just me, or do other people cringe at the sight of camel case as well ? Same with putting "{" on new lines. I much prefer K&R style bracing. Oh well, these are minor and there are benefits to conforming...

**Comment by tractorcow** [comment]
I think the benefit of adopting psr-2 is having to avoid all those conversations. :) Someone somewhere has already argued about all these boring things, and psr-2 is the result.

**Comment by SpiritLevel** [comment]
I know, I know...I just had to get my two cent's worth in!   :P  From this point forward I'll be a religious zealot, and follow the most important commandment: Thou shalt not put any other coding styles before PSR-1,2,....

**Comment by tractorcow** [comment]
The only annoying part is that we'd recently re-named some methods to FOLLOW the silverstripe convention. If we'd left them, they'd be closer to psr-2 than they are now. :)

**Comment by SpiritLevel** [comment]
That reminds me of Dan's recent comment about fixing a bug and then coming across implementations that require the bug! Double handling is painful not only in coding but also in moving furniture, a currently felt pain since I moved house over the holidays and am still unpacking boxes and shifting furniture around.

**Comment by tractorcow** [comment]
Yeah, @dhensby, stop putting bugs in other people's changes. :P

**Pull request merged**
