### PR TITLE
NEW Allow use of new AnnotationTransformer for configuration

### PR DESCRIPTION
**Pull request by ScopeyNZ**
Requires https://github.com/silverstripe/silverstripe-config/pull/35

If that PR is merged then this PR enables configuration in SilverStripe with annotations. See that PR for more details.

### CODE REVIEW

**Comment by robbieaverill** [comment]
@silverstripe/core-team this change has the potential the have quite an impact on the way dependency injection works in SilverStripe - worth reviewing when you have time

**Comment by ScopeyNZ** [comment]
Would be good if the tests were left passing @ScopeyNZ

**Comment by maxime-rainville** [comment]
Could we see a sample use case please?

**Comment by ScopeyNZ** [comment]
https://github.com/silverstripe/silverstripe-framework/pull/8564

**Comment by kinglozzer** [comment]
I like it. I assume this PR complements #8564 rather than replaces it? I’d like to see some docs on `@Inject(Foo,tag)` - I _think_ I’ve picked up what it’s used for from the test, but it’d be good to confirm 😄

Is upper case for the `Injectable` and `Inject` a convention? We currently use lower case for `@config` (which I _think_ is an (unused) custom annotation of ours), should we be consistent one way or the other?

**Comment by emteknetnz** [comment]
This pull request hasn't had any activity for a while. Are you going to be doing further work on it, or would you prefer to close it now?

**Comment by robbieaverill** [comment]
It's really waiting on the core team's input. Let's chase that up cc @silverstripe/core-team

**Comment by ScopeyNZ** [comment]
Yeah if this gets some positive feedback, I'll get the tests green. Right now I'm not sure the concept has the support yet.

**Comment by ScopeyNZ** [comment]
FYI this is a requirement for https://github.com/silverstripe/silverstripe-framework/pull/8564 which has a more specific use.

**Comment by GuySartorelli** [comment]
It's looking like this is unlikely to get the support it needs, short of scheduling a live discussion or a vote or something of that nature. In the interest of not having things like this just sit around forever can we either call it dead or define some criteria under which it can either be considered accepted or rejected?

**Comment by GuySartorelli** [comment]
As this hasn't had any comments since my last one I'm going to close this.

**Pull request closed without merging**
