### PR TITLE
ENH Add Nice to DBField

### PR DESCRIPTION
**Pull request by lekoala**
## Description
Adding a Nice method on the base DBField class simplify code down the line and avoid extra method_exists checks and make static analysis tool happy

## Manual testing steps
Classes types against DBField do not complain anymore about Nice not being present

## Issues

- https://github.com/silverstripe/silverstripe-framework/issues/11169

## Pull request checklist

- [x] The target branch is correct
    - See [picking the right version](https://docs.silverstripe.org/en/contributing/code/#picking-the-right-version)
- [x] All commits are relevant to the purpose of the PR (e.g. no debug statements, unrelated refactoring, or arbitrary linting)
    - Small amounts of additional linting are usually okay, but if it makes it hard to concentrate on the relevant changes, ask for the unrelated changes to be reverted, and submitted as a separate PR.
- [x] The commit messages follow our [commit message guidelines](https://docs.silverstripe.org/en/contributing/code/#commit-messages)
- [x] The PR follows our [contribution guidelines](https://docs.silverstripe.org/en/contributing/code/)
- [x] Code changes follow our [coding conventions](https://docs.silverstripe.org/en/contributing/coding_conventions/)
- [x] This change is covered with tests (or tests aren't necessary for this change)
- [x] Any relevant User Help/Developer documentation is updated; for impactful changes, information is added to the changelog for the intended release
- [x] CI is green

### CODE REVIEW

**Comment by GuySartorelli** [comment]
Please target the `5` branch (new methods should be included in minor releases, not patches) and tick all the boxes that apply in the PR description.

The actual code looks good to me. Nice and simple.

**Comment by GuySartorelli** [comment]
It looks like you've inadvertently pulled in some commits that aren't related to this PR, and have additional commits to cancel them out - can you please instead make sure this PR only has the commits that are relevant to the change being made?
The high-level overview of how I recommend doing that is:
1. Delete your local (not remote!) branch
1. Switch to the `5` branch
2. Create a new local branch with the same name as the original PR branch (i.e. `patch-54` in this case)
3. Cherry-pick the relevant commits
4. Force-push the branch (it'll override the remote branch with the same name, thereby updating the PR)

More detailed instructions are in [this gist](https://gist.github.com/GuySartorelli/74627843aeb75e12b777b1f44cb22d2f)

Please also tick the relevant boxes as per https://github.com/silverstripe/silverstripe-framework/pull/11184#issuecomment-2014512792

**Comment by lekoala** [comment]
@GuySartorelli done, i'm getting better at this whole git branch management thing ;)

**Comment by GuySartorelli** [comment]
That's perfect, thank you!

**Pull request merged**
