### PR TITLE
API Add CSRF to Campaign delete

### PR DESCRIPTION
**Pull request by tractorcow**
Fixes https://github.com/silverstripe/silverstripe-framework/issues/5328

### CODE REVIEW

**Comment by tractorcow** [comment]
Rebased.

**Comment by chillu** [comment]
I probably would've done this via parsing the HTTP body of the `DELETE` statement instead in the new `SecurityToken-> getRequestToken()` method: HTTP headers are a bit more likely than HTTP body to be sanitised by overzealous proxies and firewalls. Unlikely to be an issue in practice though.

@dhensby You've literally pressed the merge button five seconds before me :D

**Comment by dhensby** [comment]
:)

**Comment by tractorcow** [comment]
I believe I was following the best practices of joomla when implementing this. I think they use the same process.

**Pull request merged**
