### PR TITLE
API Standardise SS_List::map() implementation

### LINKED ISSUE #1593: [2012-09-17] DataList::map() and ArrayList::map() return different types
created by: @frankmullenger (frankmullenger)
created at: 2012-09-17
original ticket: http://open.silverstripe.org/ticket/7869

---

DataList::map() returns an SS_Map object:
https://github.com/silverstripe/sapphire/blob/3.0/model/DataList.php#L605

ArrayList::map() returns an array:
https://github.com/silverstripe/sapphire/blob/3.0/model/ArrayList.php#L245

Ideally both methods would have the same return type for consistency.

### PR DESCRIPTION
**Pull request by tractorcow**
Fixes #1593

### CODE REVIEW

**Comment by dhensby** [comment]
@tractorcow you need to fix the test in `MemberTest::testMap_in_groupsReturnsAdmins` that relies on old behaviour

**Comment by tractorcow** [comment]
That's why I should run all tests before pushing... :)

**Comment by tractorcow** [comment]
Pushed up again.

**Comment by dhensby** [comment]
thank goodness, at last we have this crappy inconsistent API fixed!!! :)

**Comment by tractorcow** [comment]
`$fristItems`

**Pull request merged**
