### PR TITLE
Refactor datefield to use proper fallbacks for HTML5

### PR DESCRIPTION
**Pull request by unclecheese**
Resolves: https://github.com/silverstripe/silverstripe-admin/issues/631

### CODE REVIEW

**Comment by unclecheese** [comment]
Actually on second look, this should be falling back to `i18n::get_locale()`, which is set in `LeftAndMain::init()`. This could be an issue isolated to our behat test.

**Comment by robbieaverill** [comment]
Related; https://github.com/silverstripe/silverstripe-framework/issues/8339

**Comment by chillu** [comment]
@bergice Could you check if that's been fixed by your recent work on date fields? Or how it overlaps with yours?

**Comment by bergice** [comment]
@chillu this is already a part of https://github.com/silverstripe/silverstripe-admin/issues/723 - we need to get this merged along with my changes as `DateField` and `DatetimeField` are separate.

**Comment by maxime-rainville** [comment]
Did we miss this one? Is it meant to be merged with the DateField PR?

**Comment by bergice** [comment]
> Did we miss this one? Is it meant to be merged with the DateField PR?

Looks like it.

It specifically fixes `DateField`, while my changes were focused on `DateTimeField`.
The `DateTimeField` component extends `DateField`, however the PHP classes are entirely separate.

**Comment by maxime-rainville** [comment]
I assigned my self to it and moved it to review.

**Comment by bergice** [comment]
Tested without these changes and everything is working fine.

**Pull request closed without merging**
