### PR TITLE
Fix broken inline buttons

### PR DESCRIPTION
**Pull request by scott1702**
To fix Share Draft button and any future buttons not being inline.

https://github.com/silverstripe-labs/silverstripe-sharedraftcontent/issues/31

### CODE REVIEW

**Comment by flashbackzoo** [comment]
Fixes https://github.com/silverstripe-labs/silverstripe-sharedraftcontent/issues/31

@uniun Can you remember when you made this `display: block`?

**Comment by uniun** [comment]
Because `display: inline-block;` adds empty space below dropdown field.
I've played with CSS a bit more and found out that it is possible to replace `display: inline-block;` with `vertical-align: bottom;`. It shoud work with *sharedraftcontent* module too.

**Comment by scott1702** [comment]
@uniun Could you please provide a picture of what you mean by `display: inline-block;` adding extra space below the dropdown field? It seems to work better for me using `display: inline-block` (On Chrome).

`display: block;`
image

`display: inline-block`
image

**Comment by uniun** [comment]
Opera 29 / Chrome 43
dropdowns

**Comment by scott1702** [comment]
Ah thanks @uniun, I didn't realise we were talking about different things. Updated and rebased.

**Pull request merged**
