### PR TITLE
add async and defer attributes to js requirements, replaces #4555

### PR DESCRIPTION
**Pull request by xini**
ok. rebased and reworked.. @sminnee @chillu @dhensby

### CODE REVIEW

**Comment by dhensby** [comment]
Test failure related, I'm afraid :(

**Comment by xini** [comment]
I have fixed the PHP issue, but behat is still failing. Any ideas? Forked from a failing master? Cheers.

**Comment by sminnee** [comment]
@xini the issues seem to relate to the `/admin/security/EditForm/field/Members/item/2/edit` URL in the test. Maybe check that the group section is still functioning for you?

**Comment by dhensby** [comment]
Try rebasing against master?

**Comment by xini** [comment]
hm.. now the npm test fails. any ideas?

**Comment by dhensby** [comment]
Seems npm is having some issues: https://github.com/npm/npm/issues/13284

**Comment by dhensby** [comment]
Looks like the codeclimate issues need to be sorted out now

**Comment by xini** [comment]
the codeclimate issue is not something I can fix. it's a +/-2 of the same issue in hoverintent.js. nothing to do with this PR.

**Comment by dhensby** [comment]
@xini can you try rebasing, please, as that PR you referenced has now passed all tests

**Comment by xini** [comment]
here we go. finally. ;) Thanks.

**Pull request merged**
