### PR TITLE
NEW: CMS site tree status icons

### PR DESCRIPTION
**Pull request by jonom**
Added coloured status 'dots' to overlay page icons and improved visibility of status labels. As discussed in https://github.com/silverstripe/silverstripe-framework/pull/2794

img

### CODE REVIEW

**Comment by chillu** [comment]
Thanks Jono, no worries on the jstree update, that's a tough one. I've recorded a little video to demonstrate the effect to others like @clarkepaul (who's on leave until the 12th): http://screencast.com/t/BQUUkub35dpz. You'll notice that the slide animation only works when performed on the currently opened page - is that on purpose? Seems inconsistent.

**Comment by jonom** [comment]
It was partly on purpose and partly due to limitations with CSS transitions. When an element is changed to or from `display:none` transitions aren't applied, so I'd have to do some experimenting to see if I could accomplish the same effect at all times.

The 'partly intentional' component is that if the status label is hidden and only shown on rollover, I wouldn't want the animation to start straight away on rollover as it does for the active node - I would want to introduce a delay so that you have some time to read the start of the text before it is animated out.

I'm happy to play around with this some more but unfortunately I probably couldn't get to it for a few weeks. Moving to Canada next month so not a lot of spare time at the moment :)

**Comment by clarkepaul** [comment]
Great work - as @chillu has said it would be good to get that transition consistent. 
@chillu is this something we could accept knowing there is a fix still to be made?
As a result of the recent usability testing we will likely be recommending a change to that text "Removed from draft" to something shorter like "Archived", but that could be a while and needs to be implemented and consistent in several places. 

Good luck with the move @jonom

**Comment by jonom** [comment]
Thanks @clarkepaul preparation is going well so far.

Paul I just wanted to flag in case you hadn't encountered it that this change essentially places a max-width on each label in the site tree when in compact mode. For me it's acceptable to have some text clipped off long labels (these should ideally be short anyway) but I don't know if everyone will agree?

**Comment by clarkepaul** [comment]
For me it is also acceptable to have longer labels clipped, we need to make the labels a bit more snappy and they should have the opportunity to view the larger site tree or click on the page for more details.

**Comment by jonom** [comment]
6 weeks later I've made a very simple change to the badge animation that hopefully seals the deal - the animation will only happen when you hover over the badge now, and it will happen for any node, not just the active one.

Should I squash these commits and open a new PR against SS 3.2? Is there anything else that needs to be tweaked here?

**Comment by clarkepaul** [comment]
Nice one. Can't wait to see this puppy go out, its been a while since any UI/UX improvements have been made.

**Comment by dhensby** [comment]
@jonom yep, I think if you can squash, that'd be good. as for going against 3 branch... not sure. I'd let it in 3.1 but the recent improvements to the overlay went into 3, so let's stick with that convention for now.

Thanks for the hard work!!

**Comment by jonom** [comment]
@clarkepaul @dhensby I've squashed the commits on this PR but having trouble creating a pull request for the 3 branch - it seems like the admin/css/screen.css file there is out of date compared to the scss files (hasn't been compiled?). Or maybe my system is compiling things differently... but I didn't have trouble on the 3.1 branch. Here is the work in progress - notice the extra commit for compiling scss at the start: https://github.com/silverstripe/silverstripe-framework/pull/3936

**Comment by jonom** [comment]
Howdy ho core devs - Would love to see this rolled in (to 3.1 if you think appropriate) please let me know if there's anything else you need me to do.

**Comment by dhensby** [comment]
I think it'd be better for this to make a 3.2 release than a 3.1 as this kind of graphical change probably shouldn't come in patches otherwise users could see changes with every upgrade rather than with a more significant one

**Comment by jonom** [comment]
Yes that makes sense. Closing in favour of #3936

**Pull request closed without merging**
