### PR TITLE
Update spaces in syntax, single quotes, early returns where possible

### PR DESCRIPTION
**Pull request by robbieaverill**
* Adding spaces in syntax like `['foo'=>'bar']`
* Use single quotes over double
* Early returns where possible
* Some phpdoc fixes
* Some minor logic tidy ups

It's a reasonably small PR because I don't want it to be overwhelming to review.

### CODE REVIEW

**Comment by sminnee** [comment]
The style changes makes sense to me! Are there phpcs rules that we could activate as part of this PR to enforce them going forward?

**Comment by robbieaverill** [comment]
Yep, and some of these types of things would be covered with PHPStan too - once we get that in!

**Comment by sminnee** [comment]
What I meant was: can we update framework's phpcs.xml to include some of these rules, as part of this PR?

**Comment by robbieaverill** [comment]
Yes. It will make the PR harder to review though, I'd rather do that separately so I can say it's fully automated

**Comment by sminnee** [comment]
Ok fair call 👍🏻

**Review by sminnee — APPROVED** [review]

**Comment by sminnee** [comment]
The build failure appears to be erroneous and the PR build passing is sufficient to validate this.

**Comment by robbieaverill** [comment]
Oh, that was from me accidentally pushing this branch to origin - my bad.

**Pull request merged**
