### PR TITLE
Fix batch action permissions not applied to new nodes loaded

### PR DESCRIPTION
**Pull request by flamerohr**
When new nodes were loaded, checkboxes weren't disabled as was needed.

### CODE REVIEW

**Comment by dhensby** [comment]
Is this only a problem in v4?

**Comment by flamerohr** [comment]
I think it goes down to 3, I'll investigate a bit later on.
It may be a separate pull request to the 3 branch?

(note: just added an unbind for `onunmatch` for this pull request)

**Comment by tractorcow** [comment]
This needs a rebase and maybe tests will pass. :)

**Comment by flamerohr** [comment]
I've rebased, hopefully that's all good

**Comment by dhensby** [comment]
thanks!

**Pull request merged**
