### PR TITLE
BUG Setting $tmpFile property in Upload class. Attempt 2.

### PR DESCRIPTION
**Pull request by flamytwista**
Attempt 2.

There is a protected $tmpFile property.
If it is defined in this place (see my commit)
I would be able to create an extension for upload class like this (example is simplified):
```
class CustomUploadExtension extends Extension {
    public function onAfterLoad($file){
        $originalName = $this->owner->getField('tmpFile')['name'];
        $file->setField('Title', $originalName);
        $file->write();
        return;
    }
}
```
------------------------------------
```
Upload::add_extension('CustomUploadExtension');
Config::inst()->update('FileNameFilter', 'default_replacements', array(
    '/\s/' => '-', // remove whitespace
    '/_/' => '-', // underscores to dashes

    '/а/u'=>"a",'/б/u'=>"b",'/в/u'=>"v",
        /*......*/
    '/Я/u'=>"YA",

    '/[^A-Za-z0-9+.\-]+/' => '', // remove non-ASCII chars, only allow alphanumeric plus dash and dot
    '/[\-]{2,}/' => '-', // remove duplicate dashes
    '/^[\.\-_]+/' => '', // Remove all leading dots, dashes or underscores
));
```
It is useful for uploading cyrrilic-named file and leaving title as original filename.

### CODE REVIEW

**Comment by tractorcow** [comment]
I would prefer to minimise the size of the state of the current upload. Otherwise you need to maintain this value to prevent it getting stage (e.g. over multiple file uploads).

Why not add `$tmpFile` to the extension?

```php
$this->extend('onAfterLoad', $this->file, $tmpFile);
```

**Comment by tractorcow** [comment]
Upload::$tmpFile is protected and neither set or referenced anywhere. Maybe it should just be removed. :D

**Comment by flamytwista** [comment]
@tractorcow
Your offer 
`$this->extend('onAfterLoad', $this->file, $tmpFile);`
is appropriate too:
before I've created pull-request I was selecting between this two decisions.

I guess I need to create new pull-request with this code, isn't it?
`$this->extend('onAfterLoad', $this->file, $tmpFile);`

**Comment by tractorcow** [comment]
You can make a new PR, or you could just overwrite this one with your change. :)

**Comment by flamytwista** [comment]
@tractorcow 
I've created new PR.
https://github.com/silverstripe/silverstripe-framework/pull/5076
Look please.

**Comment by tractorcow** [comment]
Closed with #5076

**Pull request closed without merging**
