### PR TITLE
API Remove SQLQuery

### PR DESCRIPTION
**Pull request by tractorcow**
As SQLQuery was deprecated since 3.2 we can remove it in 4.0

### CODE REVIEW

**Comment by tractorcow** [comment]
Rebased.

**Comment by kinglozzer** [comment]
Shouldn’t we also rename `SQLQueryTest` to `SQLSelectTest` for everything in the tests/fixtures etc?

**Comment by tractorcow** [comment]
It's probably not necessary, and would make merging harder. The name doesn't need to match the class exactly. ;) Especially because it makes merging harder...

**Comment by dhensby** [comment]
@tractorcow it should really be renamed; it's a merge pain BUT people need to be able to find tests by the <ClassName>Test(.php) convention

**Comment by tractorcow** [comment]
Rename inc. :D

**Comment by tractorcow** [comment]
Renamed

**Comment by tractorcow** [comment]
test pass, @dhensby :D

**Pull request merged**
