### PR TITLE
ActionTabSet, Change position absolute to bottom instead of top

### PR DESCRIPTION
**Pull request by flamerohr**
We have scenarios where the position of the actiontabset is hidden because it overflows behind the edge of the bottom of the window.

http://i.imgur.com/n00vWJa.png

### CODE REVIEW

**Comment by sminnee** [comment]
Seems fine - can we see a screenshot of the fixed styling?

**Comment by flamerohr** [comment]
Sure, a screenshot of before opening the tabset: http://i.imgur.com/93Glntl.png
and after opening the tabset http://i.imgur.com/RNLHdqV.png

**Comment by kinglozzer** [comment]
Doesn’t that mean that the “More options” button is then hidden behind the menu? Would `bottom: 100%` make more sense?

**Comment by flamerohr** [comment]
Fair point, it'll still be below the margin/padding at the top, but More options won't be hidden anymore.

I'll commit the change later on.

**Comment by kinglozzer** [comment]
Thanks @flamerohr!

**Pull request merged**
