### PR TITLE
Check array keys existence prior to their usage when removing methods

### PR DESCRIPTION
**Pull request by michalkleiner**
The updated piece of code throws a Notice when trying to use the failover mechanism with a custom object other than the standard SiteTree via a ContentController.

### CODE REVIEW

**Comment by kinglozzer** [comment]
This looks very similar to https://github.com/silverstripe/silverstripe-framework/pull/8703

**Comment by michalkleiner** [comment]
I think in our case it would get past that added condition and still fail on checking unset array keys.
Also, our problem is with 4.2.1, perhaps I should retarget the PR to 4.2?

**Comment by robbieaverill** [comment]
`SilverStripe\View\Tests\ViewableDataTest::testSetFailover` is failing, looks relevant. Thoughts @michalkleiner?

**Comment by lhalaa** [comment]
Any updates on this? We had a similar issue when using failover. 
```
// CustomMethods
$methodInfo = self::$extra_methods[$class][$method];
if ($methodInfo['property'] === $property && $methodInfo['index'] === $index) {
    unset(self::$extra_methods[$class][$method]);
}
```
throws a notice
`[Notice] Undefined index: property`
where the returned `$methodInfo` is 
```
array (
  'callback' => 
  Closure::__set_state(array(
  )),
)
```

Basically, what we're trying to do is render a UDF page which has a unique generated URL like shared draft, but for forms; and set the dataRecord as if creating a new controller instance, and setting failover for the that particular record.
Either we're using the `setFailover` incorrectly or that this code just needs some checking for the existence of an array key. Appreciate to hear some suggestions.

**Comment by michalkleiner** [comment]
I'll need to get my head around it once again and see what the failure means and what the test is testing to assess what needs changing where.

**Comment by robbieaverill** [comment]
I think this PR needs a rebase

**Comment by michalkleiner** [comment]
Will look into it

**Comment by michalkleiner** [comment]
For a couple minutes I was super confused why there are no changes, but a newer PR #9271 has already been merged.

**Pull request closed without merging**
