### PR TITLE
ENHANCEMENT Prevent test DBs persisting after testing

### PR DESCRIPTION
**Pull request by tractorcow**

### CODE REVIEW

**Comment by dhensby** [comment]
Hmm - keeping test DBs on failure can be a useful debugging tool - would it be better to introduce a task one could run manually - or maybe only kill the DB if there's no failure?

**Comment by tractorcow** [comment]
We have a task, but then you have to manually run it yourself. A good testing environment leaves no additional artifacts to clean up; Scouts rule.

**Comment by dhensby** [comment]
Can we pass any additional flags to phpunit like `--keep-db` ?

**Comment by tractorcow** [comment]
Possibly! it might be a bit more architecture to build in cli args -> environment args.

**Comment by sminnee** [comment]
> Hmm - keeping test DBs on failure can be a useful debugging tool - would it be better to introduce a task one could run manually - or maybe only kill the DB if there's no failure?

This was never the intended use-case, this PR just fixes a bug. 👍  to thies patch from me, assuming that the tests pass.

`--keep-db` could be an extra feature but given that this patch fixes a bug in the current system I'm inclined to merge this one first.

**Comment by tractorcow** [comment]
Tests are green so . :D

**Pull request merged**
