### PR TITLE
DOC Update SilverStripe to Silverstripe

### PR DESCRIPTION
**Pull request by Michael-HEIW**
- Only Lessons this PR
- Apply consistent formatting (120 chars etc)

### CODE REVIEW

**Review by emteknetnz — APPROVED** [review]

**Comment by michalkleiner** [comment]
Should it have been 'Silverstripe CMS' in some of those places?

**Comment by emteknetnz** [comment]
Possibly, though it's a step in the right direction =)

**Comment by michalkleiner** [comment]
Yeah, not a huge deal. My view was that it may make finding the places where it should be Silverstripe CMS and it's not SilverStripe anymore a bit harder, so we ideally get it right when we change it from SilverStripe to what it should be.
Updating the 3 instances here is not a dealbreaker, compared to the other PR where it was tens of changes.

**Comment by Michael-HEIW** [comment]
Thanks for accepting this PR.

I will take a look at #9993, which has merge conflicts, I noticed it also needs to be updated to Silverstripe CMS too I'll add this file to that PR and squash. Hopefully I will got it right 😉

**Pull request merged**
