### PR TITLE
MINOR: be more specific with background class for menu

### PR DESCRIPTION
**Pull request by stevie-mayhew**
See https://github.com/Rhym/silverstripe-cms-theme/pull/6

### CODE REVIEW

**Comment by sminnee** [comment]
This seems reasonable but I'm curious about what problems this is fixing, exactly?

**Comment by adrexia** [comment]
It means that if you are trying to override other background settings later with css (size, position, repeat etc), and not trying to override the entire background image, you can do so without using an !important. Looks like it's a direct response to the cms theming modules some folk are building.

**Comment by sminnee** [comment]
Cool - thanks for the context, as well as the change! :-)

**Comment by stevie-mayhew** [comment]
Thanks for putting that more concisely than I could have @adrexia - and thanks for the merge @sminnee :smile:

**Pull request merged**
