### PR TITLE
Features/4.0/gridfield styles

### PR DESCRIPTION
**Pull request by clarkepaul**
CSS classes have been changed so that the Grid-field works with Bootstrap table, also so BEM standards can be followed.

Converting the Grid-field to BEM isn't quite complete, the remainder should be a lot easier when JqueryUI has been removed or once all the actions have been converted to Bootstrap buttons. I think it might be best to wait until then but for now the new styles should be merge-able.

Requires "features/4.0/gridfield-styles" branches from Reports, CMS & AssetAdmin
https://github.com/silverstripe/silverstripe-cms/pull/1541
https://github.com/silverstripe/silverstripe-asset-admin/pull/203
https://github.com/silverstripe-labs/silverstripe-reports/pull/36

This pull request should is also awaiting a fix for IE10 routing which should be merged prior (will add link once it has been created).

### CODE REVIEW

**Comment by tractorcow** [comment]
Rebase please. :)

**Comment by sminnee** [comment]
@clarkepaul this can be rebased now! :-)

**Comment by clarkepaul** [comment]
I've rebased @tractorcow but I think I need to hand this over to you now, it seems the classes are duplicating on the divs surrounding the inputs and buttons, which means duplicate actions and misplaced clear button.
pasted_image_26_07_16__1_11_pm

If you can deal to the duplication of classes then I can make sure the rest of the styles are good.

**Comment by tractorcow** [comment]
I've pulled out some bugs I've found in gridfield into https://github.com/silverstripe/silverstripe-framework/pull/5851.

**Comment by dhensby** [comment]
those commits need popping off, then

**Comment by tractorcow** [comment]
They will disappear once they are merged and this PR in rebased.

**Comment by tractorcow** [comment]
I've made an attempt to resolve the double-button in gridfield search issue, but the layout is a bit weird still.

image


I suggest we create custom search field templates, and use setTemplate / setFieldHolderTemplates in `GridFieldFilterHeader` to customise the layout for these.

**Comment by tractorcow** [comment]
We also need to do something about the padding in edit page.

image

**Comment by clarkepaul** [comment]
Styling I can deal to @tractorcow

**Comment by tractorcow** [comment]
Thanks!

It looks like the search fields are trying to show a "clear" button beside each field. A bit of hacking got them to show up.

image

Maybe you'd like to incorporate / remove these in the new layout?

**Comment by clarkepaul** [comment]
Yeah I'll leave them there, they are useful to clear the fields. I did have all of this area styled perfectly but that was before all the recent form updates. The styles should all be there and hopefully it will be a matter of reconnecting them? I'll see soon.

**Comment by tractorcow** [comment]
Need to merge https://github.com/silverstripe-labs/silverstripe-behat-extension/pull/120 to get behat tests passing.

**Pull request merged**
