### PR TITLE
FIX make class loader classExists check interface_exists as per docs

### PR DESCRIPTION
**Pull request by dhensby**
The PHP comment says that it checks for classes and interfaces.

If that's the case, we should use the built in `interface_exists` function with the `class_exists` one for speed.

Should this method be renamed?

Should this method even use the php functions at all? Currently it doesn't depend on the manifest being used - though removing those checks would miss PHP classes/interfaces. Though the PHPDoc says "... in the manifest"

Should we have functions to check existence of classes/interfaces separately?

### CODE REVIEW

**Comment by wilr** [comment]
> Should we have functions to check existence of classes/interfaces separately?

Yep appears it's only used for ClassLoader::exists() so creating an interfaceExists() method would make the most sense.

**Comment by dhensby** [comment]
@wilr if there's currently no use for them outside the internal exists() then maybe it isn't needed?

**Comment by dhensby** [comment]
@wilr that phpdoc is now wrong as it does return if an interface exists... The class manifest check makes no distinction, I believe.

**Comment by dhensby** [comment]
Now reverts ddec797 too

**Comment by dhensby** [comment]
@wilr either this change needs to go in, or (to fix it so it only checks classes) the manifest needs a big refactor!

**Pull request merged**
