### PR TITLE
FIX Reset nonce style to prevent affecting other unit tests

### PR DESCRIPTION
**Pull request by emteknetnz**
[Recent merged PR](https://github.com/silverstripe/silverstripe-framework/pull/9509) caused breakage on cwp-recipe-kitchen-sink travis integration test
https://travis-ci.org/github/creative-commoners/cwp-recipe-kitchen-sink/jobs/686362008

Travis cwp-recipe-kitchen-sink with code patch **(make sure this is green before merging)**:
https://travis-ci.org/github/creative-commoners/cwp-recipe-kitchen-sink/jobs/686414264

### CODE REVIEW

**Comment by emteknetnz** [comment]
Hmm, not sure about that approach.  It doesn't change the bit where the new tests created as part of the PR that was merged have unintentional spillover into others these.

`SilverStripe\View\Tests\RequirementsTest::testArgsInUrls` is one of the affected tests and it has nothing to do with `SimpleResourceURLGenerator`

I'd prefer to keep this as is

**Comment by robbieaverill** [comment]
That test also has assertions on mtime in it

**Comment by emteknetnz** [comment]
Yes that test does expect mtime.  The default and expected behaviour is to use mtime.  `ResourceURLGenerator` unfortunately does not reset the nonce style back to the default between tests, so we do need to manually reset it ourselves

This approach seems quite a bit simpler and more robust then relying on individual tests to set the config value themselves and allowing that config value to spillover into other tests

**Comment by robbieaverill** [comment]
I have to disagree. Those failing tests literally expect something configuration based, so you’d be improving those tests rather than monkey patching correct tests. I think that’s generally a good thing to do when you have the chance.

**Comment by robbieaverill** [comment]
I would agree with you if the tests didn’t have explicit assertions for mtime in them

**Comment by emteknetnz** [comment]
I'll update based on your recommendations. I'll also reset on each of those tests as well to prevent spillover

**Comment by robbieaverill** [comment]
You don’t need to reset them, that’s my point

**Pull request merged**
