### PR TITLE
PHP Fatal // member function called on boolean // added is_object()

### PR DESCRIPTION
**Pull request by steiha**
PHP Fatal error: Call to a member function dbObject() on boolean in /var/www/ [...] /public/framework/model/DataObject.php on line 3016

Not quite sure if I just messed up the relation definitions on my DataObject or this is a real bug.
Anyway it might be an improvement to check if $component is an object.

### CODE REVIEW

**Comment by tractorcow** [comment]
Can you explain how $component ended up as a boolean? I see that this changes the outcome of the error, but it doesn't really explain what's causing it (or more importantly, how to avoid it in the future).

Do you have sample code, or a stacktrace?

**Comment by steiha** [comment]
I'll look into it but probably after the holidays.

**Comment by dhensby** [comment]
Any update?

**Comment by tractorcow** [comment]
No response in a few months; Will close for the time being. :)

**Pull request closed without merging**
