### PR TITLE
Using PHP 5.x for coverage (segfaults on PHP 7.x)

### PR DESCRIPTION
**Pull request by chillu**
See https://github.com/silverstripe/silverstripe-cms/pull/1761

### CODE REVIEW

**Comment by tractorcow** [comment]
I'm going to merge a few more framework fixes, then rebase this.

**Comment by dhensby** [comment]
Still getting the seg fault on 7.1...

**Comment by sminnee** [comment]
@chillu can you rebase this please? it's got errors, I wonder if they're still relevant..

**Comment by sminnee** [comment]
I think the coverage test needs to be on MYSQL not PGSQL, so that we can get coverage reporting on the MySQL adapter.

**Comment by sminnee** [comment]
If it works on 7.1.2 we can probably just pin the coverage build to that.

**Comment by tractorcow** [comment]
I'm superceding this work with https://github.com/silverstripe/silverstripe-framework/pull/6774. 

7.1.2 fixes this issue https://bugs.php.net/bug.php?id=73969

**Comment by tractorcow** [comment]
Closed with https://github.com/silverstripe/silverstripe-framework/pull/6774

**Pull request closed without merging**
