### PR TITLE
BUGFIX: don't try and switch out of context of the tab system

### PR DESCRIPTION
**Pull request by stevie-mayhew**
Fixes https://github.com/silverstripe/silverstripe-cms/issues/1430

### CODE REVIEW

**Comment by tractorcow** [comment]
Is this a bug in 3.1 / 3.2 as well? We might need to back-port it.

**Comment by dhensby** [comment]
Dupe of #3494?

**Comment by stevie-mayhew** [comment]
@dhensby no I am pretty sure this is a different thing. If not, this is broken in 3.3 anyway :wink: 

To reproduce in an empty install go to Files > Click "search/filter" button so it drops down > Hit "Reset"

It actually throws the same error when you hit search as well but the form submission continues.

**Comment by stevie-mayhew** [comment]
The PR linked above doesn't seem to solve it in 3.1 either :)

**Comment by dhensby** [comment]
@stevie-mayhew it was merged 17 hours ago, are you testing the branches or the releases?

**Comment by stevie-mayhew** [comment]
@dhensby the branches - pulled down 3.1 this morning

**Comment by dhensby** [comment]
This was auto-closed when deleting the 3.4 branch. This PR had approval so we should look to get it in

**Comment by robbieaverill** [comment]
I believe the behat failure have been fixed now, but they're unrelated anyway

**Pull request merged**
