### PR TITLE
Added loading and disabled user feedback on batch actions button for cms...

### PR DESCRIPTION
**Pull request by LukePercy**
https://github.com/silverstripe/silverstripe-cms/issues/441

Added images to "Go" .Action:submit button for ui-state-disabled -focus, -active and -default.

Added existing "Throbber.gif" for ui-state-focus and -active to show the batch actions as "working".

Also used existing icons for disabled and active states for better user feedback.

IE wouldn't clear ui-state-focus so had to force this in JavaScript LeftAndMain.BatchActions.js.

Safari and Firefox replace ui-state-focus with ui-state-active - so added additional CSS to account for this.

Before fix:

oldbatchactionsactive
oldbatchactionsdisabled

After Fix:

batchactionsthrobber
batchactionsactive
batchactionsdisabled

### CODE REVIEW

**Comment by sminnee** [comment]
@chillu @clarkepaul @lukereative - is this worth sorting out or has SS4 work made this obsolete?

**Comment by clarkepaul** [comment]
Having the loading indicator replace the text would still be good, in fact we're replacing the the text with the loading indicator for the main actions when loading. I think this is the indicator for the bigger actions .btn__loading-icon but it might be too big for the smaller area of the "Go" button.

**Comment by clarkepaul** [comment]
This is what it looks like at the moment.
pasted_image_20_04_16__10_48_am

**Comment by chillu** [comment]
@lukereative (aka @LukePercy) are you keen to port this to 4.0 (the `master` branch)? We can't merge it into stable releases, and it doesn't merge cleanly in 4.0 at the moment. Closing for now, since this particular pull request against 3.1 won't be merged as-is.

**Pull request closed without merging**
