### PR TITLE
Update 01_Extensions.md

### PR DESCRIPTION
**Pull request by spekulatius**
adding missing space

### CODE REVIEW

**Comment by tractorcow** [comment]
I can merge this one, but would prefer that we focus minor documentation alterations in the 3 branch. 3.1 is not going to receive much attention once 3.2 is out.

**Comment by spekulatius** [comment]
The branch 3 won't be merged back into 3.2 before release/regular @tractorcow ?

**Comment by tractorcow** [comment]
No, but once 3.2 is out (and soon) our attention will be focused on 3.3.

**Comment by spekulatius** [comment]
okay, I'll add make changes for 3.2 or later branches then.

**Pull request merged**
