### PR TITLE
Add a GitHub action to lint phpdocs

### PR DESCRIPTION
**Pull request by williamdes**
Add a GitHub action to lint phpdocs

### CODE REVIEW

**Comment by williamdes** [comment]
It works !
https://github.com/williamdes/silverstripe-framework/runs/1591161577?check_suite_focus=true#step:5:1301

**Comment by sminnee** [comment]
Nice work!

A few comments:

 * the action is nice & quick, the core "build" step is only 6 seconds, so this seems a good price to pay for keeping the code compliant with api doc generation - especially if we were to introduce other things like phpstan lining that might inadvertently break it

 * why, however, are using the "ignore parse errors" option? Surely that's exactly what we would want to pick up?

 * more a question for the core team - is there anything we need to do to make this more efficiently shared across the various modules that have their docs on api.SS.org?

**Comment by williamdes** [comment]
Thank you !

> why, however, are using the "ignore parse errors" option? Surely that's exactly what we would want to pick up?

There is errors I can not fix, this is to make the action pass but still output errors, for example on pull-requests
More a warning more until all errors are removed

**Comment by williamdes** [comment]
cc @chillu

**Comment by chillu** [comment]
Thank you William! I would rather have this in the Travis config, since it'll be far easier to roll out across our large number of modules - see https://github.com/silverstripe/silverstripe-framework/issues/9174. But then again, this is a great starting point - and we're only running a handful of modules where PHPDoc linting is important (those going on api.ss.org)

@steve-silverstripe @dnsl48 Since you worked on the shared Travis config stuff, keen on your thoughts.

**Comment by dnsl48** [comment]
The guts of it is the beautiful github action [sudo-bot/action-doctum](https://github.com/sudo-bot/action-doctum), which uses the docker container underneath:
```yml
runs:
    using: "docker"
    image: "docker://botsudo/action-doctum:latest"
    args:
        - latest
        - "${{ inputs.config-file }}"
        - "${{ inputs.method }}"
        - "${{ inputs.cli-args }}"
```

I guess we could run that container in our Travis shared configs. That would allow us to easily scale that lint to the hundred modules. With GitHub actions that would require us to copy-paste this PR and make a hundred others - separately for each repository. 

Another potential problem is - GitHub Actions are out of sight for the maintainers. E.g. we won't remember to update the doctum action version. Now it's `sudo-bot/action-doctum@v5`, but when `v6` gets released - we may have to do a hundred PRs to update it everywhere and wouldn't remember to actually do that.

**Comment by emteknetnz** [comment]
+10 for try to get this into travis shared config rather than github actions

**Comment by williamdes** [comment]
> +10 for try to get this into travis shared config rather than github actions
> https://github.com/silverstripe/silverstripe-travis-shared

I will keep that in mind, but this will have some delay before I fix that :)

**Comment by williamdes** [comment]
I can assist to create the script but I am too far away from this organization to understand well how the shared repo works.
But ping me on the PR that will add it

**Pull request closed without merging**
