### PR TITLE
FIX: Redirect loop with multiple confirmation tokens present (fixes #8607)

### LINKED ISSUE #8607: devbuildtoken causes 'too many redirects'
## Affected Version
silverstripe/recipe-cms                                4.3.x-dev 1577d63 

## Description
`devbuildtoken` param prevents subsequent `/dev/build`s

## Steps to Reproduce

1. run `/dev/build?flush=1` get back a url like: `/dev/build?devbuildtoken=3611a0929afbab1b7a541209d534f72c&flushtoken=cc710207e05cd6dcf54b83c8a0c3b7af&flush=1`
2. Refresh to run dev build again with the param
3. browser will error with a notification about too many redirections (message vary per browser but in chrome it is `ERR_TOO_MANY_REDIRECTS`)
4. removing the token from the url allows dev build to work eg `/dev/build?flushtoken=cc710207e05cd6dcf54b83c8a0c3b7af&flush=1`

### PR DESCRIPTION
**Pull request by kinglozzer**
Fixes #8607

### CODE REVIEW

**Comment by robbieaverill** [comment]
Looks like a couple of the unit tests need adjusting - expecting `?devbuildtoken=` in the URL, could just look for `devbuildtoken=` in the URL instead

**Comment by robbieaverill** [comment]
Tested:

* `/?flush`
* `/dev/build?flush`
* `/dev/build`

LGTM

**Comment by kinglozzer** [comment]
> Looks like a couple of the unit tests need adjusting - expecting ?devbuildtoken= in the URL, could just look for devbuildtoken= in the URL instead

Ah yep, I’ve pushed up fixes for those

**Comment by robbieaverill** [comment]
Merged up to 4.3

**Pull request merged**
