### PR TITLE
do not assume enum has default

### PR DESCRIPTION
**Pull request by lekoala**
I tried to override default enum behaviour and run into this issue where "default" might not be set
Adding a simple check on spec_orig fixes that

### CODE REVIEW

**Comment by maxime-rainville** [comment]
Thanks for submitting a PR @lekoala. Is this fixing a specific issue? If not, could you open one and explain what the desired behavior is and how it differs from the existing behavior.

Also, could you write some unit test?

**Comment by lekoala** [comment]
if you have an enum without default, the current code will fail because exploding on "default " will result on an array with only 1 element and therefore looking for the element 1 will result in a undefined offset error.

The current code always assume that the array will have 2 elements, which is not safe to do.

It could be solved also by checking if the array has indeed 2 elements before doing $default = $default[1];

maybe something like, if (isset($default[1]) or something similar, but that adds an extra if.

I'm not planning on writing unit tests because it's not so easy to run the test suite locally. However, by reading the code, I believe it's quite obvious that a check should be mode on the existence of $default[1] before using it.

**Comment by maxime-rainville** [comment]
I think I understand what you are gunning for. Would the following code sample be a good illustration of what you are trying to achieve?

```php

<?php
use SilverStripe\ORM\DataObject;
use SilverStripe\ORM\FieldType\DBEnum;

class Dummy extends DataObject {
    private static $db = [
        'MagicEnum' => "NullableEnum(array('Active', 'Injured', 'Retired'))"
        // 'MagicEnum' => "NullableEnum(array('Active', 'Injured'))"
    ];
}

class NullableEnum extends DBEnum {

    public function getDefault()
    {
        return null;
    }

    public function scaffoldFormField($title = null, $params = null) {
        return parent::scaffoldFormField($title, $params)->setEmptyString('(null)');
    }
}
```

Basically, if you remove `Retired` from the list of available values and run a `dev/build`, you'll get an `Undefined offset` notice using our current production logic. Your fix addresses this edge case.

**Comment by lekoala** [comment]
Yes exactly :)

**Comment by lekoala** [comment]
so what do you think about merging this? (just bumping that again because I had the issue once again on one of my project). The build failure does not seem related to the patch.

**Comment by maxime-rainville** [comment]
Sorry, it dropped off my radar. I still would like to see a unit test for it, however.

**Comment by maxime-rainville** [comment]
I'll double check with some folks internally to see if there's an easy way to write test for something that only occurs after a multiple DB build.

**Comment by lekoala** [comment]
any update on this?

**Comment by lekoala** [comment]
the last test is a welcome addition ! 

looks good to me

**Comment by maxime-rainville** [comment]
Raised a related SQLite issue https://github.com/silverstripe/silverstripe-sqlite3/issues/54

**Comment by maxime-rainville** [comment]
Looks like PostgreSQL has the same issue as SQLite :frowning_face:

Probably need to move the bits of logic that decide whatever to update invalidated enum values to a separate method to a separate method so other DBSchemaManagers can override it.

@lekoala I can have a look at this later if you don't feel like patching every single one of our supported DB imlementations.

**Comment by lekoala** [comment]
Well, I'm not sure there is a need to be able to change the value to default if you remove it, although it's nice to have, but if drivers don't support it, it probably don't make a lot of sense anyway.

However, having enums with null as a default should work out of the box on all drivers no?

**Comment by maxime-rainville** [comment]
I got a PR for PostgreSQL https://github.com/silverstripe/silverstripe-postgresql/pull/92

**Comment by maxime-rainville** [comment]
I think this is related to https://github.com/silverstripe/silverstripe-framework/pull/8118

**Comment by maxime-rainville** [comment]
:man_facepalming: https://github.com/silverstripe/silverstripe-framework/issues/1387

**Pull request closed without merging**
