### PR TITLE
Removed unused use BadMethodCallException statement.

### PR DESCRIPTION
**Pull request by taoceanz**
Removed unused use BadMethodCallException statement.

### CODE REVIEW

**Comment by robbieaverill** [comment]
I've noticed that you've created this pull request from one of the "core branches" rather than a branch specifically intended for this pull request. This can cause problems if we ask you to target this PR at a different branch. No action is needed at the moment, this is for your information.

In the future please create a new branch for each individual pull request. See our [guide about contributing PRs](https://docs.silverstripe.org/en/4/contributing/code/#step-by-step-from-forking-to-sending-the-pull-request)

**Comment by taoceanz** [comment]
Thanks for the note @robbieaverill . I'll make sure to follow that guide for future PRs.

**Comment by robbieaverill** [comment]
The Travis build is unrelated, I've fixed it in 3e2fc6aa0bf21892f3944e56c2819b0601cc41dc

**Comment by taoceanz** [comment]
Thanks for confirming @robbieaverill Was hoping that wasn't due to my small PR 😆

**Pull request merged**
