### PR TITLE
ENHANCEMENT Don't infer trace if explicitly provided

### PR DESCRIPTION
**Pull request by tractorcow**
Requires (blocked by) https://github.com/Seldaek/monolog/pull/1080

### CODE REVIEW

**Comment by flamerohr** [comment]
This looks like it could be updated before the Required upstream changes

Did you want to hold that off until upstream is merged first?

**Comment by tractorcow** [comment]
Yes because we may need to change the upstream PR before this is merged.

**Comment by tractorcow** [comment]
I've left another comment on https://github.com/Seldaek/monolog/pull/1080#issuecomment-369088929. We may just close this PR if it's not possible to implement upstream.

**Comment by chillu** [comment]
@tractorcow Can you please merge this and once upstream PR is merged we'll get the benfit.

**Comment by tractorcow** [comment]
Good news, my monolog pr was accepted. Silverstripe can now generate traces on fatal errors now.

**Pull request merged**
