### PR TITLE
BUG Disabled the UpgradeBootstrap upgrader doctor task

### PR DESCRIPTION
**Pull request by maxime-rainville**
This task is useless. The upgrader already handles these changes in a non-destructive way.

# Parent issue
* https://github.com/silverstripe/silverstripe-upgrader/issues/117

### CODE REVIEW

**Comment by chillu** [comment]
@maxime-rainville Can you point to where the upgrader handles the copying of htaccess and index.php into the public webroot? If we disable this, we shouldn't keep dead code around. So we should also remove the source of this at https://github.com/silverstripe/silverstripe-framework/blob/4/src/Dev/Upgrade/UpgradeBootstrap.php?

Also, tests are broken on this PR.

**Comment by emteknetnz** [comment]
@maxime-rainville 
- Broken travis tests are just PHPCS, probably fixed by rebasing
- We should probably also remove the dead code as Ingo noted eariler

Where do you see this PR going? Are you going to be doing further work on this one?

**Comment by maxime-rainville** [comment]
Retargeted the PR to 4.5 to since 4.3 is out of support and this will probably not be fixed in time for the final 4.4 patch release.

The webroot command on the upgrader now handles the creation of the .htaccess and index.php file.

**Comment by emteknetnz** [comment]
OK cool, tests pass now.  So nothing further needs to be done here right? (no more code that needs to be deleted?) If I click the pretty green merge button at this point nothing bad will happen right?

**Comment by maxime-rainville** [comment]
Click the pretty green merge button. Do it! Do it NOW!!!

**Pull request merged**
