### PR TITLE
BUG Fix issue with Requirements mangling custom scripts

### PR DESCRIPTION
**Pull request by tractorcow**
API Remove deprecated $template parameter from Requirements::includeInHTML

Also includes various PHP style warnings in Requirements.php

### CODE REVIEW

**Comment by sminnee** [comment]
I thought I had posted a fix a while back that dealt with all the whitespace errors?

**Comment by tractorcow** [comment]
Maybe it was re-introduced from a merge up from 3 branch? It happens regularly.

**Comment by tractorcow** [comment]
:shipit:

**Comment by tractorcow** [comment]
Thank you.

**Comment by dhensby** [comment]
when I merge up I tend to use the `-X ignore-all-space` option as it makes merging significantly easier - though I'm not sure who's white-space it keeps :/

**Pull request merged**
