### PR TITLE
extends temp folder versioning for local cache

### PR DESCRIPTION
**Pull request by pine3ree**
Allow php versioning for local cache folder
/path/to/public/silverstripe-cache/user-php-PHP_VERISION

### CODE REVIEW

**Comment by dhensby** [comment]
This is already in? see #3882

**Comment by kinglozzer** [comment]
Hmm, so this change would result in putting the PHP version in the _user_ directory name, rather than the _site_ directory name? What’s the benefit of this over the current behaviour?

Test failures look related.

**Comment by pine3ree** [comment]
Hi@kinglozzer 

this let you have local cache directories like the following:

/path/to/project/silverstripe-cache/user-php-5-4.42
/path/to/project/silverstripe-cache/user-php-5-5.26

under the same standard

/path/to/project/silverstripe-cache

when this directory is found, whil the original PR is adding versioning to the cache directory under system tmp only

It also keeps all the versioned cache directories under a unique common cache folder for the project

I haven't updated the tests, wanted to know if this could be useful to other ppl first. I believe they are just checking the original versioning PR name generations.

**Comment by kinglozzer** [comment]
Are there any obvious benefits besides the slightly tidier directory structure? The only other benefit I can think of is if the user has created a `docroot/silverstripe-cache` directory and then upgraded their PHP version, they won’t get a unique directory name so will experience the crash that this was intended to resolve. Moving the PHP version to the user (i.e. `docroot/silverstripe-cache/www-data-php-5-5-26`) would solve this

**Comment by pine3ree** [comment]
@kinglozzer 
The benefit you recognized is the main purpose of this PR. :-)

**Comment by dhensby** [comment]
Ah-ha, I see.

Ok, then I think the current version just needs to be moved onto the username rather than having it twice.

**Comment by tractorcow** [comment]
I think this needs moving to 3 branch, squashing, and fix tests please, then it can be merged.

It might be a bit late for 3.2 sorry.

**Comment by sminnee** [comment]
Anyone want to reapply this to the `3` branch?

**Comment by dhensby** [comment]
> Anyone want to reapply this to the 3 branch?

and fix the tests

**Comment by tractorcow** [comment]
Closing, since we can't merge it into 3.2.

**Pull request closed without merging**
