### PR TITLE
Show icon if image preview is missing

### PR DESCRIPTION
**Pull request by flamerohr**
Rather than a blank empty space, looks like a regular file instead now

### CODE REVIEW

**Comment by tractorcow** [comment]
@flamerohr I've reviewed and added a suggested tweak at https://github.com/open-sausages/silverstripe-framework/pull/18 (PR to your PR, if that's ok).

Sorry I didn't catch this issue earlier. :)

**Comment by tractorcow** [comment]
I've merged https://github.com/silverstripe/silverstripe-asset-admin/pull/255, by the way. :D

**Comment by flamerohr** [comment]
I'd be happy with your Pull Request rather than this one!

**Comment by clarkepaul** [comment]
So can this be closed now @flamerohr ?

**Comment by flamerohr** [comment]
actually yes, lets close this and have the other one @tractorcow did merged :)

**Pull request closed without merging**
