### PR TITLE
Moved spinner to right so it does not overlap text

### PR DESCRIPTION
**Pull request by suhongyang**
This pull request supersedes #5622. It has rebased most recent framework changes.

To summarise again: CSS is tweaked to move the spinner to the right so it doesn't overlap the text.
893a40c8-27e7-11e6-8666-e30d615a7f4e

### CODE REVIEW

**Comment by suhongyang** [comment]
Hi @clarkepaul @tractorcow just a really small + quick CSS pull request if you guys have time, thanks :)

**Comment by clarkepaul** [comment]
Looks good to me

**Comment by dhensby** [comment]
Needs rebasing, I'm afraid...

**Comment by flamerohr** [comment]
@dhensby rebased ;)

**Pull request merged**
