### PR TITLE
Add new committers

### PR DESCRIPTION
**Pull request by sminnee**
Welcome, Aaron and Stevie!

(3rd time lucky)

### CODE REVIEW

**Comment by dhensby** [comment]
@sminnee need to remove @willmorgan

**Comment by sminnee** [comment]
Done.

**Comment by dhensby** [comment]
<3

**Comment by willmorgan** [comment]
👋

**Comment by mspacemedia** [comment]
What no Zauberfisch! or Kinglozzer! ;)

**Comment by dhensby** [comment]
@mspacemedia @kinglozzer is already in (https://github.com/silverstripe/silverstripe-framework/pull/5344/files#diff-beab28d7f73d73c1e323ce4edc5262a6L10)

@Zauberfisch not at the moment it seems

**Comment by mspacemedia** [comment]
How did I miss Loz! lol... I must be getting old!

**Pull request merged**
