### PR TITLE
Remove recursive write until its fixed

### PR DESCRIPTION
**Pull request by adrhumphreys**
As seen in the issue: https://github.com/silverstripe/silverstripe-assets/issues/365

This will mean we need to reopen: https://github.com/silverstripe/silverstripe-framework/issues/9162 as it would no longer be fixed

I feel like this could be targeted at the next release of 4.5 even

### CODE REVIEW

**Comment by sminnee** [comment]
Yeah let's retarget this at 4.5. I'll do a separate patch to introduce it as a config when I'm ready.

@silverstripe/core-team should my patch to reintroduce the config flag be 4.5 or 4.6?

**Comment by adrhumphreys** [comment]
I feel like I'm missing something, it's already based off 4.5?

**Comment by ScopeyNZ** [comment]
@sminnee switched the branch for you. It's only showing one commit still but the builds will run against your branch, which is based off `4`. You need to rebase onto `4.5` with Git and let the builds run.

**Comment by sminnee** [comment]
@adrhumphreys can you rebase onto 13b4d60d4ae8e371b20ea5ec9dbb01cb4b0e36ab thanks

**Comment by sminnee** [comment]
@maxime-rainville do you think we should tidy this up before 4.6 gets to RC1?

**Comment by adrhumphreys** [comment]
Sorry for the delay have made a new pr with it rebased here: https://github.com/silverstripe/silverstripe-framework/pull/9528

Didn't want to rebase this branch as we've got a project using it currently ✌️

**Comment by sminnee** [comment]
Cool yeah hopefully you can get https://github.com/cweagans/composer-patches in place for fast-tracking PRs into projects in the future, it's a bit less brittle and less prone to leaving projects stuck on fork.s

**Pull request closed without merging**
