### PR TITLE
Bump phpunit version

### PR DESCRIPTION
**Pull request by dhensby**
Moving PHPUnit to v8 as v7 is no longer supported and we need to fix some of our test failures by upgrading

Related:
- https://github.com/silverstripe/silverstripe-admin/pull/1023
- https://github.com/silverstripe/silverstripe-cms/pull/2532
- https://github.com/silverstripe/silverstripe-assets/pull/382
- https://github.com/silverstripe/silverstripe-testsession/pull/71
- https://github.com/silverstripe/silverstripe-versioned/pull/267
- https://github.com/silverstripe/silverstripe-graphql/pull/255

### CODE REVIEW

**Comment by robbieaverill** [comment]
Ha, #9166 #9376

**Comment by dhensby** [comment]
The number of dependencies there are to run the framework test suite is quite surprising! 😱

**Comment by dhensby** [comment]
Ok, I think we are there (we appear to be in the same state as the current master)

**Comment by dhensby** [comment]
> We should probably add some info to the SS5 upgrade guide about this too

I've just pushed some minor amends. I'm not sure what more there is to say other than "our changes are in line with the upstream changes in PHPUnit - go upgrade your tests"

**Comment by dhensby** [comment]
Tests are green except for the CMS suite, which won't go green until there's a lot more work in other modules merged.

**Pull request merged**
