### PR TITLE
API Add DataObject::getTableName to retrieve static $table_name

### PR DESCRIPTION
**Pull request by robbieaverill**

### CODE REVIEW

**Comment by tractorcow** [comment]
table_name is a config, not a protected static. Please use DataObjectSchema for getting the table name.

**Comment by robbieaverill** [comment]
Thanks @tractorcow - equivalent should be `DataObject::getSchema()->tableName(MyDataObject::class)` ?

**Comment by tractorcow** [comment]
Yep that's it.

**Comment by tractorcow** [comment]
In the future I was thinking of adding something like DataObjectSchema_ForClass, similar to how we have Config_ForClass. That might simplify the syntax a bit.

**Pull request closed without merging**
