### PR TITLE
MNT Remove scrutinizer config.

### PR DESCRIPTION
**Pull request by GuySartorelli**
The scrutinizer builds are failing because they don't have `allowed_plugins` config set in composer.
We've discussed this internally and decided that we're not using this anyway, so the easiest solution is just to remove it.

### CODE REVIEW

**Comment by GuySartorelli** [comment]
Note that I don't have the necessary permissions to tell scrutinizer to actually stop running on PRs - someone in @silverstripe/core-team will need to tackle that part.

**Review by emteknetnz — APPROVED** [review]

**Comment by emteknetnz** [comment]
I'm assuming that just removing the config is enough? There's not setting in github to 'turn off' scrutinezer as far as I'm aware

**Comment by emteknetnz** [comment]
Ah right, it's in as a webhook on a per repo basis.  I'll remove the one in framework. I have no idea what repos it's enabled on, so if you see any others let me know

**Comment by GuySartorelli** [comment]
Yeah I haven't had a look around - I'll create PRs removing config when and as I notice scrutinized on PRs. Doesn't seem too wide spread.

**Pull request merged**
