### PR TITLE
FIX extraClass() method to match parent method

### PR DESCRIPTION
**Pull request by xini**
the method name is wrong and doesn't work.

### CODE REVIEW

**Comment by xini** [comment]
this will also have to be applied to 3.2 and master.

**Comment by willmorgan** [comment]
This is an API change and therefore will have to be submitted against 3, I'm afraid.

**Comment by xini** [comment]
really? that fixes a bug that's been there since 2011... which branch do you want it to be rebased to? master?

**Comment by dhensby** [comment]
That function definitely can't just be removed in 3.1 - people can easily be using it (isn't it being used in templates already?!)

I'd agree it's a bug and should be added in, you'd need to deprecate the old method though (not just remove it).

**Comment by tractorcow** [comment]
@xini if you want to rebase against 3 branch we can merge it there, but you'll need to add a stub to prevent regressions.


```php
/**
 * @deprecated
 */
public function extraClasses() {
	Deprecation::notice('4.0', 'Use extraClass() instead');
	return $this->extraClass();
}
```

**Comment by xini** [comment]
rebased against 3, see #4873

**Pull request closed without merging**
