### PR TITLE
Add page styles based on new bootstrap forms

### PR DESCRIPTION
**Pull request by clarkepaul**
Supersedes https://github.com/silverstripe/silverstripe-framework/pull/5728 
Requires https://github.com/silverstripe/silverstripe-framework/pull/5826 and https://github.com/silverstripe/silverstripe-cms/pull/1554

### CODE REVIEW

**Comment by tractorcow** [comment]
Rebase please. :D

**Comment by sminnee** [comment]
@clarkepaul this can be rebased now! :-)

**Comment by tractorcow** [comment]
Please rebase this... it's a bit tough for me to crack @clarkepaul !

**Comment by clarkepaul** [comment]
@tractorcow I've manually merged in your code in from https://github.com/open-sausages/silverstripe-framework/tree/pulls/4.0/bootify-forms-addpage-damo but two issues are still there.
1) Step 1 is rendering as text and not code:
image

2) The selection group used to hide and show the page select field. Not a biggy but couldn't see where the JS is included to make this happen again.

**Comment by clarkepaul** [comment]
And I didn't manage to rebase with master, don't know why there are so many conflicts, or know what is the best approach now to resolving them. @tractorcow

**Comment by clarkepaul** [comment]
Every should be now rebased (to the max) :)

**Comment by clarkepaul** [comment]
All rebased and I've done IE and visual testing which is all good.

**Comment by sminnee** [comment]
`CompositeFieldTest::testLegend` is failing at the moment.

The CMS tests are also failing but it looks like these are already failing on master so I don't think that blocks merge.

**Comment by tractorcow** [comment]
Fixed the test.

**Pull request merged**
