### PR TITLE
FIX: allow separate strings for periods dative

### PR DESCRIPTION
**Pull request by mertenhanisch**
See issue #3456 

New strings for the lang/*.yml:
Date:
  SECAGO
  SECSAGO
  MINAGO
  MINSAGO
  HOURAGO
  HOURSAGO
  DAYAGO
  DAYSAGO
  MONTHAGO
  MONTHSAGO
  YEARAGO
  YEARSAGO

### CODE REVIEW

**Comment by sminnee** [comment]
Hey, @mertenhanisch, @chillu,

This issue has sat idle for a while now. Do we want to get it merged in or cancel it?

Thanks,
Sam

**Comment by chillu** [comment]
If merged as-is, it'll make things slightly better in German, but worse in all other languages - since they'll fall back to the `en` strings for lack of specific translations. So we need to create those fallbacks as documented in the `es.yml` example above.

Once that's in place, I'd be happy to merge. Count-specific and context-specific translations as suggested by @sminnee (`DAYS_IN_1` and `DAYS_AGO_1`) would be nice, but not essential for this PR.

@mertenhanisch I'm going to keep this open for a week to give you time to express interest to implement the suggestions - afterwards I'll close the PR. You're always welcome to reopen it at any time with new work of course - thanks for your contribution so far!

**Comment by mertenhanisch** [comment]
@chillu This is so far back and I am sad to say, that I hardly work with SilverStripe anymore. At the moment I will not be able to work on this. I appreciate you asking and thank you for your consideration.

**Comment by chillu** [comment]
Thank you for getting back to us so quickly, and Dankeschön for making trying to make it a better experience for German authors!

**Pull request closed without merging**
