### PR TITLE
ENH Make all GridField components injectable.

### PR DESCRIPTION
**Pull request by GuySartorelli**
Some components were already injectable, but all GridField components shipped in silverstripe should be injectable.
This makes it a LOT easier to make global project-specific changes to a given component.

Separate pull requests will need to be made to other silverstripe core modules to replace use of the `new` keyword to take advantage of this - I'll work on that as time permits if this PR gets approved.

### CODE REVIEW

**Comment by GuySartorelli** [comment]
Another way to do this, now that I've gone and done it this naïve way, would be to make an `AbstractGridFieldComponent` class that implements `GridFieldComponent` and uses `Injectable`, and have all of the built-in components extend the new abstract class.
If maintainers prefer the abstract class way of doing this I'm happy to refactor the PR, just let me know.

**Comment by michalkleiner** [comment]
Thanks @GuySartorelli. I think I'd prefer the `AbstractGridFieldComponent` approach, but can you please open it as a separate PR and keep this until we make the final call?

**Comment by GuySartorelli** [comment]
@michalkleiner Done - see #10204

**Comment by michalkleiner** [comment]
Thanks @GuySartorelli!

Is the addition of the `Injectable` trait the only thing to live in the abstract class? Nothing else can be abstracted there?

**Comment by GuySartorelli** [comment]
@michalkleiner That's all I was intentionally doing for the purposes of this pull request. I didn't really look further than that as to what might be common between all components - but given that the interface is literally empty I would hesitate to put anything into the abstract class without a fairly thorough analysis of not only the built-in components but also some common third-party components to be sure there won't be any unintended side-effects.

I definitely won't have time to have a proper look at the similarities between components any time soon in any case but would be happy to make changes/add stuff to the abstract class if there is something specific that someone can point out. But that might be best left for a future follow-up pull request IMO.

**Comment by emteknetnz** [comment]
Alternative PR using an abstract class was merged, closing this one

**Pull request closed without merging**
