### PR TITLE
NEW ViewableData_Debugger implements __toString

### PR DESCRIPTION
**Pull request by dhensby**
This fixes an issue were ViewableData can be 'debugged' and no information is output - related #4030

### CODE REVIEW

**Comment by willmorgan** [comment]
Are there any precautions that we can take to prevent exceptions/errors being thrown?

IIRC, if an error is thrown during `__toString`, then 'Exception thrown without a stack frame' can potentially be shown to the user.

**Comment by dhensby** [comment]
What kind of exceptions are you expecting, @willmorgan ?

**Comment by tractorcow** [comment]
I think this seems fine. If we encounter errors we can probably re-look at this again in the future.

**Comment by willmorgan** [comment]
Template errors for starters. But hey, merged now...

**Comment by tractorcow** [comment]
Sorry @willmorgan . Do you want to have a go at changing this if you feel you'd like more error checking? If you think it's needed, I'll accept another PR with exception handling if you would like to submit one. :)

**Pull request merged**
