### PR TITLE
remove login marker cookie on logout

### PR DESCRIPTION
**Pull request by xini**

### CODE REVIEW

**Review by dhensby — APPROVED** [review]
The PHP doc block clearly states that the intention is that this cookie is removed on logout, so this is a good fix :)

**Comment by michalkleiner** [comment]
I was disappointed in past when a small fix was dragging for too long because of the release process not being accommodating in this way, so I'd be ok with getting this (and any safe minor bugfix for the matter) in, either as soon as possible, or indicate when such as "next patch right after the release", so that the contributor doesn't feel like we don't appreciate their effort.

**Comment by xini** [comment]
@maxime-rainville any updates on this? I would really like to get this fix into 4.9.

**Review by maxime-rainville — DISMISSED** [review]
Bug fixes are are not affected by the feature freezes ... at first glance this looks like a bug fix.

This won't make it to the `4.9.0` release which we sent to the auditors yesterday. But it could make it to a 4.9.1 patch release of framework soon after.

I would like to see some unit test for this before approving it. Also, providing an explanation of what you are trying to fix helps. If it wasn't for @dhensby's comment I would have no idea this PR is meant to achieve.

**Comment by xini** [comment]
@maxime-rainville this is trying to restore the functionality that was once working in SS3, see https://github.com/silverstripe/silverstripe-framework/blob/3/security/Member.php#L679

How would I write a test for this? `login_marker_cookie` has never had a test before, not in SS3 nor SS4. Thank for your help.

**Comment by maxime-rainville** [comment]
You can find more information about how to write unit test in the Silverstripe Doc:
- Read [Write test](https://docs.silverstripe.org/en/4/developer_guides/testing/#writing-tests) for an overview
- Read [How to write a SapphireTest](https://docs.silverstripe.org/en/4/developer_guides/testing/how_tos/write_a_sapphiretest/) for a detailed example.
- Read [How to Write a FunctionalTest](https://docs.silverstripe.org/en/4/developer_guides/testing/how_tos/write_a_functionaltest/) for a detailed example on writing a functional

While I fully appreciate that this is a lot to take in, those are useful skills to learn that you can apply to our own projects.

There's already some test coverage for this class in [SessionAuthenticationHandlerTest.phph](https://github.com/silverstripe/silverstripe-framework/blob/4/tests/php/Security/MemberAuthenticator/SessionAuthenticationHandlerTest.php). If you look at the existing tests, you should have a good starting point for your own tests.

You can run those test locally with executing this command from your project root: `vendor/bin/phpunit vendor/silverstripe/framework/tests/php/Security/MemberAuthenticator/SessionAuthenticationHandlerTest.php  "" flush=all`

**Comment by xini** [comment]
Thanks, @maxime-rainville. I have added a test to make sure the cookie is set and removed correctly. But the build fails for I believe an unrelated issue? not sure?

**Comment by xini** [comment]
@maxime-rainville, I have fixed the tests, squashed the commits and rebased the PR onto 4.9. But the travis build for some reason picked branch 4.8 as a base and failed?

**Comment by maxime-rainville** [comment]
I think travis is not smart enough to realise when your PR targeted branch has changed. If you force push another commit on your branch, that should unstuck it.

**Comment by xini** [comment]
@maxime-rainville thanks, this worked.

**Review by michalkleiner — APPROVED** [review]

**Comment by xini** [comment]
@maxime-rainville any updates on this? Cheers

**Comment by xini** [comment]
@maxime-rainville as this is a bugfix, could this still go into 4.10?

**Pull request merged**
