### PR TITLE
Docs updated injector docs to reflect inject() changes

### PR DESCRIPTION
**Pull request by flamerohr**
added example for the change

changes can be found here: https://github.com/silverstripe/silverstripe-admin/pull/394

original story found here https://github.com/silverstripe/silverstripe-asset-admin/issues/718

### CODE REVIEW

**Comment by unclecheese** [comment]
Minor readability changes, rebase. Merge on green.

**Comment by tractorcow** [comment]
Restarted build; I think the issue in admin was fixed.

**Comment by flamerohr** [comment]
Would be good to get https://github.com/silverstripe/silverstripe-admin/pull/407 in for the docs to hold true

**Comment by dhensby** [comment]
is this good to merge?

**Pull request merged**
