### PR TITLE
FIX: Render html (eg. links) in security messages

### PR DESCRIPTION
**Pull request by mikeyc7m**
ContentController.DRAFT_SITE_ACCESS_RESTRICTION includes a link that gets rendered as plaintext. Need to render as HTML.

### CODE REVIEW

**Comment by dhensby** [comment]
Is there not a better way to do this, ie: change the castiing config for the LoginForm?

**Comment by sminnee** [comment]
This seems okay but will need rebasing and conflict resolution.

**Comment by tractorcow** [comment]
A couple of things, DRAFT_SITE_ACCESS_RESTRICTION is no longer used (since 3 branch) as permissions for versioned viewing were simplified a bit.

I would rather that, instead of catering to the lowest common denominator (treating everything as html, which is a huge risk) that we leave the default as plain text, and allow messages to be passed in as cast text values.

E.g. 

```php
if($message instanceof DBField) {
	$escapeHtml = $message->config()->escape_type === 'raw';
	$message = $message->Value();
} else {
	$escapeHtml = true;
}
$form->sessionMessage($message, 'warning', $escapeHtml);
```

**Comment by tractorcow** [comment]
Someone just needs to replace this PR with my code lol. ;)

**Comment by mikeyc7m** [comment]
Hey, new update on this. I've been advised of a security risk - DRAFT_SITE_ACCESS_RESTRICTION provides a link to the published version using the original link. So if someone crafts a malicious URL and appends ?stage=Stage the login form will regurgitate a nasty link.
http://yoursite.com/nasty-link/%22%3E%3Cscript%3Ealert(%22naughty%22)%3C/script%3Eg18d6/?stage=Stage

**Comment by kinglozzer** [comment]
Hi @mikeyc7m, the issue you’re describing was fixed in `3.3.3` and `3.4.1` (SS-2016-007 - https://www.silverstripe.org/download/security-releases/). If you think you’ve found a security issue, please email security@silverstripe.com instead of posting it here. Thanks! 😄

**Comment by tractorcow** [comment]
@mikeyc7m please use our security issues disclosure list for security issues. security@silverstripe.com

If you post security risks directly to our public issue tracker then it puts lots of websites at risk. Please see https://docs.silverstripe.org/en/4/contributing/release_process/#reporting-an-issue for more information.

**Comment by tractorcow** [comment]
Ah, I replied without hitting refresh. :D

**Comment by tractorcow** [comment]
Since this PR is stale, I'm replacing with a story to re-implement the suggested fix at https://github.com/silverstripe/silverstripe-framework/issues/7577

**Pull request closed without merging**
