### PR TITLE
FIX OptionsetField returns valid HTML #4901

### PR DESCRIPTION
**Pull request by torleif**

### CODE REVIEW

**Comment by tractorcow** [comment]
Dupe of https://github.com/silverstripe/silverstripe-framework/pull/4912?

**Comment by torleif** [comment]
appologies, it's a new pull request to reflect the comment you made here: 4912#discussion_r49387032

**Comment by tractorcow** [comment]
Shall we leave out the unset on aria-required for now? It's not strictly invalid html to include it on a UL is it?

We will definitely need to allow users to apply this property to formfields where it's necessary, especially sites that have strict accessibility requirements.

**Comment by torleif** [comment]
@tractorcow sweet, I've popped back in the aria-required

**Comment by tractorcow** [comment]
Thanks @torleif

**Comment by dhensby** [comment]
Without the correct markup an aria-required in the wrong place is invalid html

**Comment by tractorcow** [comment]
Yeah, that's right... I probably need to find out exactly what is valid and do this across fields.

**Comment by dhensby** [comment]
Yes, I had to make a lot of changes to mark-up for an accessible site I built - I should try to go back and look at it all.

the short of it is: our forms are all wrong.

**Comment by tractorcow** [comment]
The problem is that setAttribute() doesn't let you say WHERE the attribute goes. For each field, the target element is different.

**Comment by dhensby** [comment]
Erm, set attribute always works on the form input, I think... Its the extra classes that goes all over the place.

**Comment by tractorcow** [comment]
Except in optionsetfield, which doesn't have one `<input>` element. Or grouped fields, etc.

**Pull request merged**
