### PR TITLE
Fix add schema to the "auto" parts request

### PR DESCRIPTION
**Pull request by flamerohr**
A part of fixing https://github.com/silverstripe/silverstripe-asset-admin/issues/163

### CODE REVIEW

**Comment by tractorcow** [comment]
On submission, are you sure you want to re-request the schema? Success state should be included in the state not the schema.

**Comment by flamerohr** [comment]
Yes, this is because the form schema could change after submission... e.g. if a file is published, we want to start showing the unpublish button, and vice versa.

Unfortunately, I wasn't able to find another way to provide such an information change

**Comment by tractorcow** [comment]
We may as well just get rid of auto then. Do you agree?

**Comment by flamerohr** [comment]
That might be an idea... however getting rid of it seems like a bigger architectural decision which I'll need more time to think about :)

Currently, I think including the schema in "auto" is fine.

**Pull request merged**
