### PR TITLE
Update SapphireTestReporter.php

### PR DESCRIPTION
**Pull request by azt3k**
- Updates code to be compatible with PHP 5.0.2
- Allows the autoloader to be called so as composer can be used (PHPUnit PEAR install is now deprecated)

http://php.net/manual/en/function.interface-exists.php
http://php.net/manual/en/function.class-exists.php
https://github.com/sebastianbergmann/phpunit/wiki/End-of-Life-for-PEAR-Installation-Method

### CODE REVIEW

**Comment by dhensby** [comment]
Makes sense, what wasn't working before this and how would I go about replicating the issue?

**Comment by azt3k** [comment]
I'm on a system where PHPUnit is not in the php include path, i.e. it's been installed with composer as dev dependency of a project.  If you have a dev dependency of PHPUnit in your composer JSON and run a dev install you would end up with PHPUnit classes being unpacked to something like:

`$BUILD_ROOT/vendor/phpunit/phpunit/src/Framework/`

So when you run

`$BUILD_ROOT/framework/sake dev/tests/$TEST_PATH`

You get something like

PHP Fatal error:  require_once(): Failed opening required 'PHPUnit/Framework/TestResult.php'

Because:

- The class and interface don't exist at that point and even if they did, require_once would be called  when class_exists is used to test the existence of the interface so the error can't be avoided by manually loading the classes
- PHPUnit isn't installed globally via PEAR.  If the vendor folder or the PHPUnit dir was in the include path then `require_once` wouldn't work  due to the fact that it's unpacked to `$VENDOR_DIR/phpunit/phpunit/src/Framework/` rather than `$VENDOR_DIR/PHPUnit/Framework/` or `$VENDOR_DIR/phpunit/PHPUnit/Framework/`
- The autoloader won't get triggered if passing false to param 2 of  `class_exists` or `interface_exists`

So as far as replication:

1. You need a system without PHPUnit in the include path
2. You need PHPUnit installed as a composer dependency (although this will never be loaded so it's not a prerequisite, but it is required for the tests to run)
3. Run any tests that have been extended from `SapphireTest`
4. You should get `require` fatal errors

**Comment by dhensby** [comment]
Thanks for the detailed response and for finding the fix.

At the moment we run all our tests like so `vendor/bin/phpunit framework` - directly using the phpunit binary.

I've just run `framework/sake dev/tests/DataObjectTest` and that has worked for me as expected (though this was against master).

**Comment by azt3k** [comment]
Sounds like PHPUnit exists in your include path somewhere.

This script should reproduce the issue on a system that doesn't:

````bash
composer create-project silverstripe/installer ./test
cd test
mkdir silverstripe-cache
composer require "silverstripe/sqlite3:*"
composer require "phpunit/phpunit:*@stable"
echo "<?php
define('SS_ENVIRONMENT_TYPE', 'dev');
define('SS_DATABASE_CLASS', 'SQLitePDODatabase');
define('SS_DATABASE_USERNAME', 'root');
define('SS_DATABASE_PASSWORD', '');
define('SS_SQLITE_DATABASE_PATH', ':memory:');
define('SS_DATABASE_SERVER', 'localhost');
define('SS_DATABASE_CHOOSE_NAME', true);
define('SS_DEFAULT_ADMIN_USERNAME', 'username');
define('SS_DEFAULT_ADMIN_PASSWORD', 'password');
$_FILE_TO_URL_MAPPING[dirname(__FILE__)] = 'http://localhost:8000';
" >> _ss_environment.php
framework/sake dev/build
framework/sake dev/tests/DataObjectTest
````

This is the result i get:

````bash
azt3k@azt3k-v:~/dev/tmp/test$ framework/sake dev/tests/DataObjectTest
DATAOBJECTTEST

--------------


PHP Warning:  require_once(PHPUnit/Framework/TestResult.php): failed to open stream: No such file or directory in /home/azt3k/dev/tmp/test/framework/dev/SapphireTestReporter.php on line 2
PHP Fatal error:  require_once(): Failed opening required 'PHPUnit/Framework/TestResult.php' (include_path='/home/azt3k/dev/tmp/test/vendor/phpunit/php-text-template:/home/azt3k/dev/tmp/test/vendor/phpunit/php-timer:/home/azt3k/dev/tmp/test/vendor/phpunit/php-file-iterator:.:/home/azt3k/dev/tmp/test/framework:/home/azt3k/dev/tmp/test/framework/parsers:/home/azt3k/dev/tmp/test/framework/thirdparty:.:/usr/share/php:/usr/share/pear') in /home/azt3k/dev/tmp/test/framework/dev/SapphireTestReporter.php on line 2
````
If I run this script to patch the files:

````bash
sed -i "s/if(\!class_exists('PHPUnit_Framework_TestResult', false)) require_once 'PHPUnit\/Framework\/TestResult.php';/if (\!class_exists('PHPUnit_Framework_TestResult')) require_once 'PHPUnit\/Framework\/TestResult.php';/g" framework/dev/SapphireTestReporter.php
sed -i "s/if(\!class_exists('PHPUnit_Framework_TestListener', false)) require_once 'PHPUnit\/Framework\/TestListener.php';/if (\!interface_exists('PHPUnit_Framework_TestListener')) require_once 'PHPUnit\/Framework\/TestListener.php';/g" framework/dev/SapphireTestReporter.php
````

I get this

````bash
azt3k@azt3k-v:~/dev/tmp/test$ framework/sake dev/tests/DataObjectTest
DATAOBJECTTEST

--------------


..................................................

 ALL TESTS PASS 

50 tests run: 50 passes, 0 failures, and 0 incomplete
Maximum memory usage: 66.5M




Total time: 18.474 seconds
````

**Comment by azt3k** [comment]
As an additional comment the test system is Ubuntu 14.10 so the sed command wont work on OSX.

This bug also exists in master.

**Comment by dhensby** [comment]
The first thing I notice is `composer require "phpunit/phpunit:*@stable"`. SS runs on 3.7@stable.

I can replicate the problem on 4.5@stable however your fix doesn't resolve the problem for me once that's done.

**Comment by azt3k** [comment]
Re: `3.7@stable` 
The test does run in that situation.  However because `class_exists` will fail on `PHPUnit_Framework_TestListener` because it's an interface you at the very least will have an unnecessary `require_once` call.

Re: `4.5@stable` 
Are you sure you applied the patch correctly? 
I ran through a couple of times just to verify - works wonderfully on my end.  Can you please verify that you do infact have the updated code at the top of `framework/dev/SapphireTestReporter.php`

````php
<?php
if (!class_exists('PHPUnit_Framework_TestResult')) require_once 'PHPUnit/Framework/TestResult.php';
if (!interface_exists('PHPUnit_Framework_TestListener')) require_once 'PHPUnit/Framework/TestListener.php';
````

I just did a sanity check to see that the autoloader will get used in the `class_exists` / `interface_exists` scenario and Core.php includes composers autoloader so in theory if you allow PHP to autoload when querying if a class exists then PHP unit classes should get autoloaded so the only logical explaination I can think of is the updated code never made it into your test install:

````php
// Fall back to Composer's autoloader (e.g. for PHPUnit), if composer is used
if(file_exists(BASE_PATH . '/vendor/autoload.php')) {
	require_once BASE_PATH . '/vendor/autoload.php';
}
````

What system are you testing on?

**Comment by dhensby** [comment]
I'll give it another go. I'm testing on centos 7.

Using https://github.com/BetterBrief/vagrant-skeleton - master branch - though for the last test (to ensure composer wasn't in my $PATH) or PHP's include path I used a from scratch chef/centos-7.0 box

**Comment by azt3k** [comment]
The issue is reproducible on this image: https://github.com/gezpage/vagrant-lamp-ubuntu-trusty

**Comment by azt3k** [comment]
I tried using https://github.com/BetterBrief/vagrant-skeleton - master branch this was the result

````bash
[vagrant@localhost test]$ bash framework/sake dev/tests/DataObjectTest
DATAOBJECTTEST

--------------


PHP Warning:  require_once(PHPUnit/Framework/TestResult.php): failed to open stream: No such file or directory in /home/vagrant/test/framework/dev/SapphireTestReporter.php on line 2

Warning: require_once(PHPUnit/Framework/TestResult.php): failed to open stream: No such file or directory in /home/vagrant/test/framework/dev/SapphireTestReporter.php on line 2
PHP Fatal error:  require_once(): Failed opening required 'PHPUnit/Framework/TestResult.php' (include_path='/home/vagrant/test/vendor/phpunit/php-text-template:/home/vagrant/test/vendor/phpunit/php-timer:/home/vagrant/test/vendor/phpunit/php-file-iterator:.:/home/vagrant/test/framework:/home/vagrant/test/framework/parsers:/home/vagrant/test/framework/thirdparty:.:/usr/share/pear:/usr/share/php') in /home/vagrant/test/framework/dev/SapphireTestReporter.php on line 2

Fatal error: require_once(): Failed opening required 'PHPUnit/Framework/TestResult.php' (include_path='/home/vagrant/test/vendor/phpunit/php-text-template:/home/vagrant/test/vendor/phpunit/php-timer:/home/vagrant/test/vendor/phpunit/php-file-iterator:.:/home/vagrant/test/framework:/home/vagrant/test/framework/parsers:/home/vagrant/test/framework/thirdparty:.:/usr/share/pear:/usr/share/php') in /home/vagrant/test/framework/dev/SapphireTestReporter.php on line 2
PHP Warning:  Cookie 'alternativeDatabaseName' can't be set. The site started outputting content at line 64 in /home/vagrant/test/framework/dev/CliDebugView.php in /home/vagrant/test/framework/control/Cookie.php on line 117

Warning: Cookie 'alternativeDatabaseName' can't be set. The site started outputting content at line 64 in /home/vagrant/test/framework/dev/CliDebugView.php in /home/vagrant/test/framework/control/Cookie.php on line 117
PHP Warning:  Cookie 'alternativeDatabaseNameIv' can't be set. The site started outputting content at line 64 in /home/vagrant/test/framework/dev/CliDebugView.php in /home/vagrant/test/framework/control/Cookie.php on line 117

Warning: Cookie 'alternativeDatabaseNameIv' can't be set. The site started outputting content at line 64 in /home/vagrant/test/framework/dev/CliDebugView.php in /home/vagrant/test/framework/control/Cookie.php on line 117
[vagrant@localhost test]$ sed -i "s/if(\!class_exists('PHPUnit_Framework_TestResult', false)) require_once 'PHPUnit\/Framework\/TestResult.php';/if (\!class_exists('PHPUnit_Framework_TestResult')) require_once 'PHPUnit\/Framework\/TestResult.php';/g" framework/dev/SapphireTestReporter.php
[vagrant@localhost test]$ sed -i "s/if(\!class_exists('PHPUnit_Framework_TestListener', false)) require_once 'PHPUnit\/Framework\/TestListener.php';/if (\!interface_exists('PHPUnit_Framework_TestListener')) require_once 'PHPUnit\/Framework\/TestListener.php';/g" framework/dev/SapphireTestReporter.php
[vagrant@localhost test]$ bash framework/sake dev/tests/DataObjectTest
DATAOBJECTTEST

--------------


..................................................

 ALL TESTS PASS

50 tests run: 50 passes, 0 failures, and 0 incomplete
Maximum memory usage: 61.2M




Total time: 5.54 seconds
[vagrant@localhost test]$
````

**Comment by dhensby** [comment]
How bizarre, I'll run again

**Comment by dhensby** [comment]
Really can't replicate this...

My steps (after downloading latest vagrant-skeleton):

```shell
$ vagrant up
$ vagrant ssh
$ sudo su
$ cd /var/www/html
$ composer require --dev phpunit/phpunit:~3.7@stable
$ bash framework/sake dev/build/DataObjectTest
```

**Comment by azt3k** [comment]
To be fair, although there is an erroneous call to `class_exists` and hard coding the path is not a great approach for a number of reasons, it does work with `phpunit/phpunit:~3.7@stable`, just not with  `phpunit/phpunit:*@stable`.

So while the code in 3.1 is functioning, it's not really functioning as intended - i.e. `framework/core/Core.php` implies that phpunit should be auto-loaded if possible - which it wont be due to the way the code is structured and calling `class_exists` on an interface wont work on any supported version of PHP.  So there are problems, just not breaking problems if you limit the version of phpunit to 3.5.

As such I understand the reluctance to merge a patch on code that appears to be working, however this issue will come up in future, so perhaps 3.1 is not the place to merge the code??

Thoughts?

**Comment by dhensby** [comment]
@azt3k I agree that this is a sensible change.

It looks like it affects phpunit 4, but we rely on phpunit 3 (not 4).

Now, if this is all that we need to change to be using phpunit 4 then maybe we should do that?

What are the advantages to phpunit 4? From looking at the [requirements](https://phpunit.de/manual/current/en/installation.html#installation.requirements) it supports php 5.3.3 so seems safe to use for our 3 branch - so I don't see a technical limitation in adopting it

**Comment by azt3k** [comment]
The error itself is thrown primarily because version 4+ of PHPUnit changes the directory structure so the call to `require_once(PHPUnit/Framework/TestResult.php)` fails.

Compare branches here to see the differences: 
https://github.com/sebastianbergmann/phpunit/tree/4.0
vs
https://github.com/sebastianbergmann/phpunit/tree/3.7

However the actual reasons it fails to load the required classes/interfaces are due to some other things that I feel are unintended (and also covered in the thread above).

I tried running all the tests on `phpunit/phpunit:4.5@stable` after applying the patch and the output is below - there is one issue in that as of 4.2 PHPUnit_Framework_Assert::assertTag is deprecated ( https://github.com/sebastianbergmann/phpunit/blob/4.5/ChangeLog-4.2.md#phpunit-420 ).  So some additional work would need to be done to make it compliant with >=4.2

````bash
azt3k@azt3k-v:~/dev/tmp/test$ framework/sake dev/tests/all
ALL TESTS
Running test cases: 
--------------------
AggregateTest, AopProxyTest, ArrayDataTest, ArrayLibTest, ArrayListTest, AssetAdminTest,
BacktraceTest, BasicAuthTest, CacheTest, CheckboxFieldTest, CheckboxSetFieldTest, ClassInfoTest,
ClassLoaderTest, ClassManifestTest, CMSFormTest, CMSMainSearchFormTest, CMSMainTest,
CMSMenuItemTest, CMSMenuTest, CMSPageHistoryControllerTest, CMSProfileControllerTest,
CMSSiteTreeFilterTest, ComponentSetTest, CompositeDBFieldTest, CompositeFieldTest,
ConfigManifestTest, ConfigStaticManifestTest, ConfigTest, ConfirmedPasswordFieldTest,
ContentControllerPermissionsTest, ContentControllerSearchExtensionTest, ContentControllerTest,
ContentNegotiatorTest, ControllerTest, ConvertTest, CoreTest, CSSContentParserTest,
CsvBulkLoaderTest, CSVParserTest, CurrencyFieldTest, CurrencyTest, DatabaseTest,
DataDifferencerTest, DataExtensionTest, DataListTest, DataObjectDuplicationTest,
DataObjectLazyLoadingTest, DataObjectSchemaGenerationTest, DataObjectTest, DataQueryTest,
DateFieldTest, DateFieldViewJQueryTest, DateTest, DatetimeFieldTest, DbDatetimeTest, DBFieldTest,
DBLocaleTest, DBTest, DecimalTest, DeprecationTest, DevAdminControllerTest, DiffTest, DirectorTest,
DropdownFieldTest, EmailFieldTest, EmailTest, EncryptAllPasswordsTaskTest, ErrorControlChainTest,
ErrorPageTest, FieldListTest, FileFieldTest, FileFinderTest, FileLinkTrackingTest,
FileNameFilterTest, FileTest, FixtureBlueprintTest, FixtureFactoryTest, FlushRequestFilterTest,
FolderTest, FormActionTest, FormFieldTest, FormScaffolderTest, FormTest, FulltextSearchableTest,
GDImageTest, GDTest, GridFieldAddExistingAutocompleterTest, GridFieldConfigTest,
GridFieldDataColumnsTest, GridFieldDeleteActionTest, GridFieldDetailFormTest,
GridFieldEditButtonTest, GridFieldExportButtonTest, GridFieldPaginatorTest,
GridFieldSortableHeaderTest, GridFieldTest, GridField_URLHandlerTest, GroupCsvBulkLoaderTest,
GroupedListTest, GroupTest, HasManyListTest, HierarchyTest, HTMLCleanerTest, HtmlEditorConfigTest,
HtmlEditorFieldTest, HtmlEditorSanitiserTest, HTMLTextTest, HTTPRequestTest, HTTPResponseTest,
HTTPTest, i18nSSLegacyAdapterTest, i18nTest, i18nTextCollectorTest, ImageTest, ImagickImageTest,
InjectorTest, LabelFieldTest, LeftAndMainTest, ListboxFieldTest, LookupFieldTest,
ManifestFileFinderTest, ManyManyListTest, MemberAuthenticatorTest, MemberCsvBulkLoaderTest,
MemberDatetimeOptionsetFieldTest, MemberTest, MemoryLimitTest, MigrateSiteTreeLinkingTaskTest,
ModelAdminTest, ModelAsControllerTest, MoneyFieldTest, MoneyTest, MySQLDatabaseTest,
NamespacedClassManifestTest, NullableFieldTests, NullHTTPRequestTest, NumericFieldTest, ObjectTest,
OembedTest, OptionsetFieldTest, PaginatedListTest, ParameterConfirmationTokenTest,
PasswordEncryptorTest, PasswordValidatorTest, PercentageTest, PermissionCheckboxSetFieldTest,
PermissionRoleTest, PermissionTest, PjaxResponseNegotiatorTest, RandomGeneratorTest,
RedirectorPageTest, RemoveOrphanedPagesTaskTest, ReportTest, RequestHandlingTest,
RequiredFieldsTest, RequirementsTest, RestfulServiceTest, RootURLControllerTest, RSSFeedTest,
SearchContextTest, SearchFilterApplyRelationTest, SecurityAdminTest, SecurityDefaultAdminTest,
SecurityTest, SecurityTokenTest, SelectionGroupTest, SessionTest, ShortcodeParserTest,
SideReportTest, SilverStripeNavigatorTest, SiteConfigTest, SiteTreeActionsTest,
SiteTreeBacklinksTest, SiteTreeBrokenLinksTest, SiteTreeHtmlEditorFieldTest,
SiteTreePermissionsTest, SiteTreeTest, SQLFormatterTest, SQLQueryTest, SSViewerCacheBlockTest,
SSViewerTest, SS_DatetimeTest, SS_HTML4ValueTest, SS_LogTest, SS_MapTest, StringFieldTest,
TemplateLoaderTest, TemplateManifestTest, TextareaFieldTest, TextTest, TimeFieldTest,
TokenisedRegularExpressionTest, TransactionTest, UnsavedRelationListTest, UploadFieldTest,
UploadTest, URLSegmentFilterTest, ValidationExceptionTest, VersionedTest, ViewableDataTest,
VirtualPageTest, XMLDataFormatterTest, YamlFixtureTest, YearTest, ZZZSearchFormTest

....I
AggregateTest::testCache

PHPUnit_Framework_Assert::markTestIncomplete()
AggregateTest.php:151

ReflectionMethod->invokeArgs(AggregateTest,Array)
TestCase.php:860

PHPUnit_Framework_TestCase->runTest()
TestCase.php:737

PHPUnit_Framework_TestCase->runBare()
TestResult.php:609

PHPUnit_Framework_TestResult->run(AggregateTest)
TestCase.php:693

PHPUnit_Framework_TestCase->run(PHPUnit_Framework_TestResult)
TestSuite.php:716

PHPUnit_Framework_TestSuite->run(PHPUnit_Framework_TestResult)
TestSuite.php:716

--------------------
........................................................................... - 80
......................................I
CMSMainTest::testPublishOneOfEachKindOfPage

PHPUnit_Framework_Assert::markTestIncomplete()
CMSMainTest.php:117

ReflectionMethod->invokeArgs(CMSMainTest,Array)
TestCase.php:860

PHPUnit_Framework_TestCase->runTest()
TestCase.php:737

PHPUnit_Framework_TestCase->runBare()
TestResult.php:609

PHPUnit_Framework_TestResult->run(CMSMainTest)
TestCase.php:693

PHPUnit_Framework_TestCase->run(PHPUnit_Framework_TestResult)
TestSuite.php:716

PHPUnit_Framework_TestSuite->run(PHPUnit_Framework_TestResult)
TestSuite.php:716

--------------------
......................................... - 160
........................I
ConfigTest::testFragmentOrder

PHPUnit_Framework_Assert::markTestIncomplete()
ConfigTest.php:254

ReflectionMethod->invokeArgs(ConfigTest,Array)
TestCase.php:860

PHPUnit_Framework_TestCase->runTest()
TestCase.php:737

PHPUnit_Framework_TestCase->runBare()
TestResult.php:609

PHPUnit_Framework_TestResult->run(ConfigTest)
TestCase.php:693

PHPUnit_Framework_TestCase->run(PHPUnit_Framework_TestResult)
TestSuite.php:716

PHPUnit_Framework_TestSuite->run(PHPUnit_Framework_TestResult)
TestSuite.php:716

--------------------
....................................................... - 240
................................................................................ - 320
................................................................................ - 400
................................................................................ - 480
................................................................................ - 560
................................................................................ - 640
................................................................................ - 720
.........................................................................I
GridFieldTest::testGridFieldAlterAction

PHPUnit_Framework_Assert::markTestIncomplete()
GridFieldTest.php:276

ReflectionMethod->invokeArgs(GridFieldTest,Array)
TestCase.php:860

PHPUnit_Framework_TestCase->runTest()
TestCase.php:737

PHPUnit_Framework_TestCase->runBare()
TestResult.php:609

PHPUnit_Framework_TestResult->run(GridFieldTest)
TestCase.php:693

PHPUnit_Framework_TestCase->run(PHPUnit_Framework_TestResult)
TestSuite.php:716

PHPUnit_Framework_TestSuite->run(PHPUnit_Framework_TestResult)
TestSuite.php:716

--------------------
...... - 800
................................................................................ - 880
................................................................................ - 960
................................................................................ - 1040
..........................................................E
NullableFieldTests::testWithContent
PHPUnit_Framework_Assert::assertTag is deprecated
trigger_error(PHPUnit_Framework_Assert::assertTag is deprecated,16384)
Assert.php:2167

PHPUnit_Framework_Assert::assertTag(Array,<input type="text" name="Field1" value="abc" class="text" id="Field1" /> <input type="checkbox" name="Field1_IsNull" value="1" class="checkbox" id="Field1_IsNull" />&nbsp;<span>Is Null</span>)
NullableFieldTests.php:25

ReflectionMethod->invokeArgs(NullableFieldTests,Array)
TestCase.php:860

PHPUnit_Framework_TestCase->runTest()
TestCase.php:737

PHPUnit_Framework_TestCase->runBare()
TestResult.php:609

PHPUnit_Framework_TestResult->run(NullableFieldTests)
TestCase.php:693

PHPUnit_Framework_TestCase->run(PHPUnit_Framework_TestResult)
TestSuite.php:716

PHPUnit_Framework_TestSuite->run(PHPUnit_Framework_TestResult)
TestSuite.php:716

--------------------
E
NullableFieldTests::testWithEmpty
PHPUnit_Framework_Assert::assertTag is deprecated
trigger_error(PHPUnit_Framework_Assert::assertTag is deprecated,16384)
Assert.php:2167

PHPUnit_Framework_Assert::assertTag(Array,<input type="text" name="Field1" class="text" id="Field1" /> <input type="checkbox" name="Field1_IsNull" value="1" class="checkbox" id="Field1_IsNull" />&nbsp;<span>Is Null</span>)
NullableFieldTests.php:46

ReflectionMethod->invokeArgs(NullableFieldTests,Array)
TestCase.php:860

PHPUnit_Framework_TestCase->runTest()
TestCase.php:737

PHPUnit_Framework_TestCase->runBare()
TestResult.php:609

PHPUnit_Framework_TestResult->run(NullableFieldTests)
TestCase.php:693

PHPUnit_Framework_TestCase->run(PHPUnit_Framework_TestResult)
TestSuite.php:716

PHPUnit_Framework_TestSuite->run(PHPUnit_Framework_TestResult)
TestSuite.php:716

--------------------
E
NullableFieldTests::testWithNull
PHPUnit_Framework_Assert::assertTag is deprecated
trigger_error(PHPUnit_Framework_Assert::assertTag is deprecated,16384)
Assert.php:2167

PHPUnit_Framework_Assert::assertTag(Array,<input type="text" name="Field1" class="text" id="Field1" /> <input type="checkbox" name="Field1_IsNull" value="1" class="checkbox" id="Field1_IsNull" checked="checked" />&nbsp;<span>Is Null</span>)
NullableFieldTests.php:67

ReflectionMethod->invokeArgs(NullableFieldTests,Array)
TestCase.php:860

PHPUnit_Framework_TestCase->runTest()
TestCase.php:737

PHPUnit_Framework_TestCase->runBare()
TestResult.php:609

PHPUnit_Framework_TestResult->run(NullableFieldTests)
TestCase.php:693

PHPUnit_Framework_TestCase->run(PHPUnit_Framework_TestResult)
TestSuite.php:716

PHPUnit_Framework_TestSuite->run(PHPUnit_Framework_TestResult)
TestSuite.php:716

--------------------
................... - 1120
......I
ObjectTest::testCacheToFile

PHPUnit_Framework_Assert::markTestIncomplete()
ObjectTest.php:341

ReflectionMethod->invokeArgs(ObjectTest,Array)
TestCase.php:860

PHPUnit_Framework_TestCase->runTest()
TestCase.php:737

PHPUnit_Framework_TestCase->runBare()
TestResult.php:609

PHPUnit_Framework_TestResult->run(ObjectTest)
TestCase.php:693

PHPUnit_Framework_TestCase->run(PHPUnit_Framework_TestResult)
TestSuite.php:716

PHPUnit_Framework_TestSuite->run(PHPUnit_Framework_TestResult)
TestSuite.php:716

--------------------
........................................I
PasswordValidatorTest::testHistoricalPasswordCount

PHPUnit_Framework_Assert::markTestIncomplete()
PasswordValidatorTest.php:42

ReflectionMethod->invokeArgs(PasswordValidatorTest,Array)
TestCase.php:860

PHPUnit_Framework_TestCase->runTest()
TestCase.php:737

PHPUnit_Framework_TestCase->runBare()
TestResult.php:609

PHPUnit_Framework_TestResult->run(PasswordValidatorTest)
TestCase.php:693

PHPUnit_Framework_TestCase->run(PHPUnit_Framework_TestResult)
TestSuite.php:716

PHPUnit_Framework_TestSuite->run(PHPUnit_Framework_TestResult)
TestSuite.php:716

--------------------
...............................I - 1200

RequestHandlingTest::testRequestHandlerChainingAllParams

PHPUnit_Framework_Assert::markTestIncomplete()
RequestHandlingTest.php:29

ReflectionMethod->invokeArgs(RequestHandlingTest,Array)
TestCase.php:860

PHPUnit_Framework_TestCase->runTest()
TestCase.php:737

PHPUnit_Framework_TestCase->runBare()
TestResult.php:609

PHPUnit_Framework_TestResult->run(RequestHandlingTest)
TestCase.php:693

PHPUnit_Framework_TestCase->run(PHPUnit_Framework_TestResult)
TestSuite.php:716

PHPUnit_Framework_TestSuite->run(PHPUnit_Framework_TestResult)
TestSuite.php:716

--------------------
................................................................................ - 1280
................................................................................ - 1360
................................................................................ - 1440
................................................................................ - 1520
................................................................................ - 1600
................................................................................ - 1680
.............................

 AT LEAST ONE FAILURE 

1709 tests run: 1699 passes, 3 failures, and 7 incomplete
Maximum memory usage: 185.1M




Total time: 856.25 seconds

````

**Comment by sminnee** [comment]
I believe that we are now using PHPUnit 4. Is this PR still necessary, @tractorcow @dhensby ?

**Comment by tractorcow** [comment]
Yep, in phpunit 4 we don't need the include anymore. Also we don't care about php 5.0 support. :)

**Pull request closed without merging**
