### PR TITLE
FIX include related fields on filter/sort check

### PR DESCRIPTION
**Pull request by jonom**
Fix for #5576. Assume this is too late for 3.4.1 but I can target that branch instead if suitable.

### CODE REVIEW

**Comment by dhensby** [comment]
We'd have to make an rc2 if this went into 3.4.1, if we do a rc2 we'll it'd only be for bugs in rc1 so this will have to miss the 3.4.1 release, I'm afraid

**Comment by dhensby** [comment]
Can we get a test for this, please?

**Comment by jonom** [comment]
Yes, I jumped the gun there. Now that I'm adding tests though I'm getting lost... I though the ORM automatically handled joins etc. so you could just do e.g. `->sort('Member.FirstName ASC')` but doesn't look like that's the case :( It looks like you can do this with filters but not sorting? That seems inconsistent.

**Comment by jonom** [comment]
Because of the lack of support for sorting on implicit joins, I've removed any sorting changes here and focused on filtering only. Think that `sort()` should be updated to support implicit joins though (for consistency and convenience), not sure if that should be a 3.x or 4 thing though? And probably outside of my capabilities.

**Comment by dhensby** [comment]
> I though the ORM automatically handled joins etc

It does, but you need to call `applyRelation` on the data query for it to do the magic. I guess filter calls that method on `DataQuery` but `sort` doesn't?! It'll need to. Though I think the `DataQuery` is meant to ensure the sort is all joined up.

**Comment by dhensby** [comment]
just *thinking* this through I can only imagine that it's going to be fairly complex to do a sort on dot notation (which is probably why it's not supported) becaues the dot notation needs to be interpretted and then converted to the actual table/column name that is joined. this is made extra complicated when taking into account the changes I'm hoping to make to fix bad joins...

**Comment by jonom** [comment]
I'm getting out of my depth but I can open an issue about the lack of sorting on relations with dot notation if that will help :D

I would have imagined that join complexity would be similar between filtering and sorting... but that's too complex for me!

Thanks for the merge!

**Comment by dhensby** [comment]
I think generally this aspect is very complex and that's why some features are missing / bugs are present.

For example, the issue of relations with a common parent table not working is because the work involved to get that to happen is complex and in-depth. The same will be true of sorting.

These really shouldn't be excuses for not having them, but someone does need to find the time to do it and implement it in a bug-free way. that's what I'm trying to do :P

**Comment by kinglozzer** [comment]
Sorting on relations via dot notation exists in master: #4812 :)

**Comment by jonom** [comment]
Hot dog!

**Comment by dhensby** [comment]
I merged it and didn't even know!

**Comment by tractorcow** [comment]
Nice job!

**Pull request merged**
