### PR TITLE
Add Convert::fqcn2htmlname()

### PR DESCRIPTION
**Pull request by nedmas**
Create helper function for converting namespaced class names to html safe strings for use in `LeftAndMain.php` and `CMSMenu.php` see PR #4167

### CODE REVIEW

**Comment by chillu** [comment]
I think this is scope creep for the framework, there's little benefit in increasing the core API (rarely used feature), and its easy to replicate in custom code. Also, no tests. Unless another core member objects within the next day or so, I'm closing this pull request.

**Comment by chillu** [comment]
I should clarify "custom code" here: For the two places where this is used in the CMS (e.g. menu), I'd inline it there and document its intent.

**Comment by tractorcow** [comment]
It's a very narrow use-case scope; I would recommend that this problem is `solved` rather by a comment on the `Convert::raw2htmlname` that if characters such as slashes have meaning, they should be escaped to one of the safe characters prior to being passed into this method.

**Comment by nedmas** [comment]
I agree that scope creep should be minimised and am happy for the core members to decide on that. However with 4.0 and the potential for namespacing framework I would suggest that the need for such a conversion will increase beyond the initial two instances (potentially FormFields and Db tables).

**Comment by chillu** [comment]
Agree with Damian on that one, so closing. In general, we want to decrease the amount of global and static dependencies in our code - and that's one way to do it :)

**Comment by robbieaverill** [comment]
For reference, [`TaskRunner` does this](https://github.com/silverstripe/silverstripe-framework/blob/master/src/Dev/TaskRunner.php#L137) - as an example of a one off use case

**Pull request closed without merging**
