### PR TITLE
NEW Allow GridFieldConfig::addComponents to accept an array

### PR DESCRIPTION
**Pull request by robbieaverill**
When I tried to use this method I expected that it would accept an array.
This pull request allows an array as well as an arbitrary number of arguments to be passed.

### CODE REVIEW

**Comment by dhensby** [comment]
To be honest, now we can use array expansion as a way of passing an array of arguments, these kinds of changes/core support are less and less needed.

You can call `$gridField->addComponents(...$arrayOfComponents)` instead of us having to support a somewhat outdated approach

Although I won't make a big fuss of it, I'd support reverting this

**Comment by tractorcow** [comment]
Yeah I'm already in trouble for messing with method signatures... it's not strictly semver ;)

**Comment by robbieaverill** [comment]
I'm not opposed to a revert, but this is backwards compatible

**Comment by tractorcow** [comment]
Yes this is... but using variadic signature may not be.

**Comment by dhensby** [comment]
> Yes this is... but using variadic signature may not be.

I'm talking about when the method is called, rather than the method definition

**Comment by tractorcow** [comment]
Oh, sure. Is that ok to do in php 5.6?

**Comment by dhensby** [comment]
> I'm not opposed to a revert, but this is backwards compatible

I accept there's not BC break - but there is an extra feature to maintain here. For devs who want to pass an array to the method they can use `...$array` instead of just `$array` and it reduces our maintenance burden, tests, etc :)

**Comment by dhensby** [comment]
> Oh, sure. Is that ok to do in php 5.6?

Yes, was added in 5.6 src: http://php.net/manual/en/migration56.new-features.php#migration56.new-features.splat

**Comment by dhensby** [comment]
I think, in summary, in 5.x I'd rather be removing the ability to pass an array and deprecating it from 4.x than adding more places where passing arrays is acceptable

**Pull request merged**
