### PR TITLE
Remove redundant force_resample logic

### PR DESCRIPTION
**Pull request by jonom**
Sorry guys, missed some cleanup that was supposed to be included in https://github.com/silverstripe/silverstripe-framework/commit/40cc567c368cc8bc633c2486ca2c420bb1256924

### CODE REVIEW

**Comment by tractorcow** [comment]
Soon as @dhensby finishes merging up we can get tests passing again. :)

**Comment by tractorcow** [comment]
Only code removal? I approve.

**Comment by jonom** [comment]
Cheers :+1:

**Comment by tractorcow** [comment]
@jonom you're still missing a few; ctrl + f for 'force_resample' in Image.php

**Comment by jonom** [comment]
@tractorcow I'm seeing two instances remaining but they need to be there for the new way of handling the force resampling

**Comment by tractorcow** [comment]
Really? I'm seeing it in a lot more than 2 places.

**Comment by jonom** [comment]
Are you looking at the right branch? You might have to give me line numbers otherwise :smile: this went in to master https://github.com/jonom/silverstripe-framework/blob/90b96e1fc419a9c7fdb661909747cd9b92d43fd0/model/Image.php

**Comment by tractorcow** [comment]
No wonder, I was looking at 3.2 sorry!

**Comment by jonom** [comment]
No worries :)

**Pull request merged**
