### PR TITLE
BUG Fix GridFieldAddExistingAutocompleter and GridFieldExportButton

### LINKED ISSUE #5267: BUG Can't link existing member to group
GridFieldAddExistingAutocompleter seems to show "Object" instead of the actual item.

Currently affecting master branch.

image

Jira: https://silverstripe.atlassian.net/browse/OSS-1728

### PR DESCRIPTION
**Pull request by tractorcow**
Based on https://github.com/silverstripe/silverstripe-framework/pull/5426
Fixes #5267

### CODE REVIEW

**Comment by hafriedlander** [comment]
I don't think it's necessary to replace ID usage with class usage unless we're also changing to BEM. However I'm not going to block merge because of it.

**Comment by tractorcow** [comment]
Annoyingly, this broke master AFTER merge. Investigating.

**Comment by dhensby** [comment]
How did the investigation go?

**Comment by tractorcow** [comment]
We are leaving PHP7 as "allowed_failure" at the moment.

The fix is to properly implement "__isset" for viewable data. See https://github.com/silverstripe/silverstripe-framework/issues/5450

**Pull request merged**
