### PR TITLE
fix to grid field loading wrong current page id when using multiple tabs

### PR DESCRIPTION
**Pull request by pitchandtone**
See https://github.com/silverstripe/silverstripe-framework/pull/3782 for previous comments

### CODE REVIEW

**Comment by tractorcow** [comment]
From #3782 can you please open this on the 3 branch? This is a fix but it also introduces new API.

**Comment by dhensby** [comment]
Bump

**Comment by tractorcow** [comment]
Bump, please re-open on 3. :)

Also, I've opened https://github.com/silverstripe/silverstripe-cms/issues/1510 as a better solution to the "page id isn't always available" issue.

**Comment by dhensby** [comment]
@tractorcow why against 3? It looks "bug fix" to me?

**Comment by tractorcow** [comment]
Fine, I guess it can be merged.

**Comment by tractorcow** [comment]
I'll kick start the tests to see if they pass.

**Comment by dhensby** [comment]
passes

**Pull request merged**
