### PR TITLE
FIX Incorrect env setting in 3.1.13

### PR DESCRIPTION
**Pull request by tractorcow**
Re-opened PR for https://github.com/silverstripe/silverstripe-framework/pull/4238 against 3.1

### CODE REVIEW

**Comment by tractorcow** [comment]
See https://github.com/silverstripe/silverstripe-installer/pull/92 for installer PR

**Comment by sminnee** [comment]
Cool, so this leaves the setting open-ended in the implementation but updates the docs to match 3.1.13. I think that's the right move.

**Comment by tractorcow** [comment]
Thanks, should we merge this one now then?

**Comment by tractorcow** [comment]
Thanks :D

**Pull request merged**
