### PR TITLE
Fix: #4342 - larger checkbox regions

### PR DESCRIPTION
**Pull request by torleif**

### CODE REVIEW

**Comment by jonom** [comment]
Hey @torleif glad to see someone taking looking at this problem! You would need to make a change to the underlying SCSS file though, then compile that to generate the CSS file. Think you might have to change the border colour for hover and selected state too? Also in 3.2 there are a few extra hover colours so would need to account for that if you submit a separate patch for that version.

An easier option instead of adding a border might be to just increase the size of the checkbox element and add some empty space around the checkbox graphic(s) so that the other sprites don't bleed in to the space. Then you won't have to account for any different hover/selected background colours.

**Comment by torleif** [comment]
@jonom ah, didn't even think that this file came from a scss file. I'll change that now.

I wanted to simply increase the padding on the element, but the graphic looks like it was provided by a third party so I avoided editing it. There's also some CSS3 features that would fix this issue. Another option is having an extra div/span inside the ins element.

**Comment by dhensby** [comment]
Yes, I think there's a better solution than a border.

Can't we wrap the element containing the checkbox and add padding to the wrapping el (but make it clickable)? (hope that makes sense...)

**Comment by jonom** [comment]
Oh I just thought of a really easy solution for this. Instead of putting the background image on the `ins` directly, we can apply it to a `:before` pseudo element. Style the `:before` element to be `display:block` abd the same size as the ins currently, add some padding and a negative margin on the `ins`. Boom.

**Comment by torleif** [comment]
@jonom sadly in that case the hit area is still applied to the parent a area. I also tried adding a parent/containing element using jquery, though there's too many hard coded css & js references in the jquery ui (and it doesn't allow for easy extending)

There's also the CSS 3.0 feature for using an image mask, though that does not have MSIE support.

So I did the next best thing: I moved the checkbox out of the

**Comment by jonom** [comment]
Hey @torleif I gave my idea a try and it seems to work well, think it's a nice simple solution: https://github.com/silverstripe/silverstripe-framework/pull/4366

**Comment by torleif** [comment]
ah brilliant, your solution is much better. I'll close off my pull request

**Pull request closed without merging**
