### PR TITLE
Fix loading indicator position (fixes #6153)

### LINKED ISSUE #6153: Tab loading mask not centred (wrong place in markup)
When navigating between tabs within the pages section the overlay mask and loading icon is not centred.
image

### PR DESCRIPTION
**Pull request by zacps**
Fix through a different element target in js.
This is untested
because `node_modules` is hopelessly broken on my machine.
Can someone else build this for client/dist?

Fixes #6153

### CODE REVIEW

**Comment by dhensby** [comment]
the bundle needs building

**Comment by dhensby** [comment]
`npm run build`

**Comment by zacps** [comment]
I couldn't get npm to build, I tried a few times including `rm -rf ./node_modules && npm install && npm rebuild && npm build` but was still getting errors.

**Comment by dhensby** [comment]
What errors? the command is `npm run build` not `npm rebuild` or `npm build`

**Comment by zacps** [comment]
Whoops, I meant `npm run build` for the last one. Rebuild builds binaries
for the current environment if it's changed since `npm install` so it
shouldn't have done anything there, I just added it to see whether it would
help.

I can't remember specific errors, it was to do with webpack's dependencies
rather than anything in SilverStripe.

**Comment by dhensby** [comment]
OK - I've built it locally for you.

**Pull request merged**
