### PR TITLE
DOCS: upgrade project duplicated in index

### PR DESCRIPTION
**Pull request by unclecheese**
We should stick to one source of truth for this.

### CODE REVIEW

**Comment by chillu** [comment]
I've had a look at the git history for both files, and doesn't look like we're losing any newer edits by removing that index:

https://github.com/silverstripe/silverstripe-framework/commits/4/docs/en/03_Upgrading/01_Upgrading_project.md
https://github.com/silverstripe/silverstripe-framework/commits/4/docs/en/03_Upgrading/index.md

This issue seems to have been introduced by accident via https://github.com/silverstripe/silverstripe-framework/commit/c1047fac3262c381c24f8bdc3b28a3c54fa82750#diff-3db669543525354abe334af3f98e3e9e

**Comment by Sommereder** [comment]
Where are the removed lines now? I was a bit stuck in how to upgrade Silverstripe from 4.4.x to 4.5.x. I saw the file last week and saved it for my upgrade today and I was pretty confused that they've been removed.

**Comment by unclecheese** [comment]
Hi, @Sommereder .. the content was duplicated across two documents, so just use the first document in the index: https://docs.silverstripe.org/en/4/upgrading/upgrading_project/

**Comment by Sommereder** [comment]
Ok, thanks, @unclecheese. But shouldn't there be a description also for upgrading minor versions and patches?

**Pull request merged**
