### PR TITLE
MINOR: clearer distinction between class names and actual names

### PR DESCRIPTION
**Pull request by sunnysideup**

### CODE REVIEW

**Comment by michalkleiner** [comment]
Even though it's docs (thanks for the helpful update!), do/should the code examples meet coding standards as well?

**Comment by sunnysideup** [comment]
I think this is confusing:

```php

   private static $has_many = [
       'Person' => 'Person',
   ];
```

and should be:
```php
   private static $has_many = [
       'Person' => Person::class,
   ];
```

That is all I was trying to fix.

**Comment by michalkleiner** [comment]
Yep, I got the change itself and fully support that.

With the coding standards (though not sure this is an actual CS rule for SS projects)
I was referring to spaces around the dot in strings concatenation,
i.e. `Fan::class.".FanOf",` would be `Fan::class . ".FanOf",`.

It was also more a general question for the maintainers. Generally not a big deal :-D

**Comment by kinglozzer** [comment]
Meh, I assume PSR-2 has rules for this but I certainly don’t think that should block a docs improvement :D

**Comment by kinglozzer** [comment]
Thanks @sunnysideup

**Pull request merged**
