### PR TITLE
API Apply psr-2 coding conventions to framework with linting CI check

### PR DESCRIPTION
**Pull request by tractorcow**
Initial commit of https://github.com/silverstripe/silverstripe-framework/issues/6096

Note that all non-automatic fixes have been excluded from this initial build; Manual resolution of all outstanding linting issues are outside of the scope of this introductory pull request.

As requested by @sminnee I've split into two commits, one is an automatic cleanup and the other a linting check.

I have also excluded tests from the current linting, but the plan is to eventually fix and add this folder too.

PHPCS_TEST is run in PHP7 build to ensure optimal coverage of all language constructs.

### CODE REVIEW

**Comment by tractorcow** [comment]
PHPCS_TEST is green. :) At least, once I muted all the known broken rules :P

**Comment by sminnee** [comment]
My preference would have been for the whitespace changes to have been applied in their own commit, but it's not a merge blocker if that would be more than an hour's rework.

**Comment by tractorcow** [comment]
All of the automatic fixes are essentially whitespace-only changes. I ran the upgrade again last night with your suggested commands and there was very little difference in output.

I don't think phpcbf can easily fix non-whitespace changes without manual input. I may need to double check though.

**Comment by sminnee** [comment]
The other thing I suggest is setting up a custom script in composer.json so that you can lint by running `composer run-script lint`.

This will make it easier to lint locally without having to copy/paste a command out of .travis.yml.

**Comment by tractorcow** [comment]
Done, and CI uses the composer script to run linting.

**Pull request merged**
