### PR TITLE
Revert #3425 #3396 to restore deprecated functionality

### LINKED ISSUE #4514: Don't remove stuff from 3.x
We need to revert 404478b07feb0f8efc8b19b1371d6f3b0398ff02 from the 3.2 and 3 branches, but not master.

These things shouldn't have been removed between 3.1 and 3.2.

The original PR #3396 was merged to master before be agreed semver and branched 3. :-(

I believe this blocks 3.2.0-rc1

### PR DESCRIPTION
**Pull request by tractorcow**
Fixes #4514

This should ensure 3.2 is properly semver.

There's one exception in Member where LastVisited and NumVisit has been removed, but documentation is included on how to restore it, and having it enabled by default has performance concerns.

### CODE REVIEW

**Comment by tractorcow** [comment]
@silverstripe/core-team can you please review to make sure this PR is appropriate?

**Comment by dhensby** [comment]
It's my view that `LastVisted` and `NumVisits` behaviour needs to be restored.

It's conceivable that this behaviour is required by devs doing a 3.1 -> 3.2 upgrade and I don't see how it could be deemed as low risk or compliant with SemVer to remove this behaviour.

I don't expect that having it in the docs to be particularly safe way to avoid regressions. If the view is "putting it in the docs is good enough" then I'd put in the docs how to disable it.

**Comment by tractorcow** [comment]
Ok, let's do this. Put the behaviour in, deprecate it, have it disabled by default with a single config change to turn on.

**Comment by tractorcow** [comment]
See original discussion at https://github.com/silverstripe/silverstripe-framework/pull/2509

**Comment by tractorcow** [comment]
Ok, LastVisited and NumVisit are back.

**Comment by sminnee** [comment]
@tractorcow could you handle master now?

 * Do any planned merge forwards
 * Revert or exclude d0f94b5 from master, as appropriate

**Comment by tractorcow** [comment]
Sure thanks :D

**Comment by tractorcow** [comment]
I've merged up, excluding this commit from the merge to master.

**Pull request merged**
