### PR TITLE
update the filtered tree styling

### PR DESCRIPTION
**Pull request by scott1702**
To be merged with https://github.com/silverstripe/silverstripe-cms/pull/1264
Before
image
After
image
image

### CODE REVIEW

**Comment by tractorcow** [comment]
Is there a before screen that helps show the difference?

**Comment by dhensby** [comment]
@tractorcow looks like the original comment has been updated

**Comment by tractorcow** [comment]
Did you test updates to the listview template as well? `CMSMain_ListView.ss`?

**Comment by scott1702** [comment]
Yep, still needs work in list view, changing it now

**Pull request merged**
