### PR TITLE
[Feedback, Sweet Feedback, Please] DB filter by NULL

### PR DESCRIPTION
**Pull request by assertchris**
This adds the ability to filter fields by `IS NULL` / `IS NOT NULL`. 

Further discussion at: https://github.com/silverstripe/silverstripe-framework/issues/3621

### CODE REVIEW

**Comment by tractorcow** [comment]
I don't think we can introduce a new filter behaviour in 3.1, especially one that's not backwards compatible (null could have been used in the past to filter for empty strings).

Perhaps you should look at 3.2 for this fix, since that's the original milestone for #3621?

If you move it to 3.2 it still doesn't change the problem that you're altering current behaviour instead of simply adding a new feature.

What you could do is add another modifier to turn the new behaviour on.

`->filter('Field', null)` // if the field is empty (current behaviour)
`->filter('Field:not', null)` // if field isn't empty string (current behaviour)
`->filter('Field:nullable', null)` // If field is null
`->filter('Field:nullable:not', null)` // if the field is not null

I would argue that in 4.0 it would be fine to drop the `nullable` filter, but for anything 3.x it would be necessary to turn on the new function.

The other (and perhaps better) solution is to simply fix this in 4.0 and not touch 3.x at all?

**Comment by assertchris** [comment]
All good ideas. Whaddya think, @sminnee?

**Comment by tractorcow** [comment]
Have you tested that `filter('Field',  array(null, '', 'value')` correctly evaluates to `"Field" IS NULL OR "Field" in ('', 'value')` or `"Field" IS NULL OR Field = '' OR FIELD = 'value'` depending on the :case :nocase modifiers?

**Comment by tractorcow** [comment]
I can help you with unit tests too later. :)

**Comment by assertchris** [comment]
@tractorcow as I mentioned in the issue (linked above) this filter is only applied to `applyOne` and `excludeOne`. This is an exploratory PR, not a complete solution. We haven't even decided if it's supposed to go in 3.2 or 4.0 yet. :)

**Comment by tractorcow** [comment]
Ah, well we probably shouldn't raise PR then at this stage. :) We wouldn't want someone to come along and merge this if it's not ready? I'll close this for now then, and we can continue to discuss here.

**Comment by dhensby** [comment]
Did we get IS NULL support in?

**Comment by tractorcow** [comment]
Yes, at https://github.com/silverstripe/silverstripe-framework/pull/4196.

**Pull request closed without merging**
