### PR TITLE
Ensure DataObject->dbObject returns a DBField

### PR DESCRIPTION
**Pull request by guttmann**
This is a potential fix for #8883

### CODE REVIEW

**Comment by kinglozzer** [comment]
An alternative fix was proposed in https://github.com/silverstripe/silverstripe-framework/pull/8833 (fixing this on the `setField` side). I’m not sure which approach is best, or if we should implement both, just noting they both attempt to fix the same issue 😄

**Comment by guttmann** [comment]
> An alternative fix was proposed in #8833 (fixing this on the `setField` side). I’m not sure which approach is best, or if we should implement both, just noting they both attempt to fix the same issue

I did think about a fix in `setField` - but the core issue seems to be `DataObject->dbObject` returning something that is not either `null` or a `DBField` so I went with the fix there instead.

**Comment by guttmann** [comment]
> I'd want to see a test as some proof this actually resolves the issue

@dhensby is the test that I've written not enough? It fails without my fix and passes with it?

I have had some ideas for how I can rewrite it so it is more clear what is being tested so I will do that now

**Comment by dhensby** [comment]
> I have had some ideas for how I can rewrite it so it is more clear what is being tested so I will do that now

You're making a check against `instanceof CompositeField` and it's not clear to me why that is. There are no assertions around that in the test...

**Comment by guttmann** [comment]
> > I have had some ideas for how I can rewrite it so it is more clear what is being tested so I will do that now
> 
> You're making a check against `instanceof CompositeField` and it's not clear to me why that is. There are no assertions around that in the test...

It's checking for `CompositeDBField` but I understand your point.

I saw the comment on [line 3028](https://github.com/silverstripe/silverstripe-framework/blob/500aa7ca72f00d8d2c1a232905f8d4b04beebae2/model/DataObject.php#L3028) and assumed the intent of that if statement was to only return `$this->record[$fieldName]` if it was actually a `CompositeDBField` so implemented that to fix the issue I was seeing.

**Comment by kinglozzer** [comment]
I’ve had another look at this and I think the fix proposed in https://github.com/silverstripe/silverstripe-framework/pull/8833 may be a better approach. We’re proposing continuing to allow `setField()` to set `$this->record['SomeNonDBField'] = $object;` as it currently does, but will now be changing `$record->dbObject('SomeNonDBField')` from returning the object to returning `null`.

One example would be:
```php
$dataObject->SomeNonDBField = DBField::create_field('HTMLText', '<p>some html</p>');

// Currently returns an HTMLText object, after this change would return null
$value = $dataObject->dbObject('SomeNonDBField');
```

That is the more correct behaviour (people shouldn’t be using `dbObject` with non-database fields), but I believe it’s more likely to cause breakages for people updating.

**Comment by emteknetnz** [comment]
This pull request hasn't had any activity for a while. Are you going to be doing further work on it, or would you prefer to close it now?

**Pull request closed without merging**
