### PR TITLE
API Added extension points to ShortcodeParser

### PR DESCRIPTION
**Pull request by jonom**
Allows us to solve problems like https://github.com/sheadawson/silverstripe-shortcodable/issues/8

### CODE REVIEW

**Comment by jonom** [comment]
To complement this change, might be good to change a lot of the protected stuff to public so that extensions can make use of it. In particular there's no way at the moment to get info on registered shortcodes, data is stored in `protected $shortcodes = array()` with no getter. You can see if a shortcode is registered with `registered($shortcode)` but can't look up the class and method responsible for rendering it.

Would there be any drawback to opening this stuff up?

**Comment by dhensby** [comment]
https://github.com/silverstripe/silverstripe-framework/issues/5535 and https://github.com/silverstripe/silverstripe-framework/issues/5987 are related.

I think adding some public getters makes sense and can go into the 3 branch too

**Comment by jonom** [comment]
@dhensby have added a getter for registered shortcodes which seems like the most useful thing to expose for now and doesn't mess with visibility of existing methods.

**Comment by jonom** [comment]
Thanks Dan

**Pull request merged**
