### PR TITLE
Attempting to call Fields() on instance of SS_HTTPResponse

### LINKED ISSUE #4592: Attempting to call Fields() on instance of SS_HTTPResponse
On a subclass of `AssetAdmin` in its `getEditForm()` method, I can call `parent::getEditForm($id, $fields);` and find it's possible for the framework to return an instance of `SS_HTTPResponse` rather than the expected `Form` if a `canView()` check up the chain in `LeftAndMain` fails.

Looking in `LeftAndMain::getEditForm()` checks are failing on line 1174 and I'm being returned an instance of `SS_HTTPResponse` rather than `Form`. This means I get the error:

`Fatal error: Call to undefined method SS_HTTPResponse::Fields() in /var/www/htdocs/my-project/cms/code/controllers/AssetAdmin.php on line 158`

### PR DESCRIPTION
**Pull request by phptek**
- "Moves" the error down to the view, from a header

https://github.com/silverstripe/silverstripe-framework/issues/4592

### CODE REVIEW

**Comment by sminnee** [comment]
This seems good, but will need a rebase and test. Can we put together a test-case for this feature?

**Comment by dhensby** [comment]
Bump?

**Comment by maxime-rainville** [comment]
Unfortunately we're only doing security updates to SilverStripe 3 from now on, so I'll have to close this one.

If you feel this is still a worthwhile feature, please refactor it so it works with SilverStripe 4.

**Comment by maxime-rainville** [comment]
I've double checked to see if it could be rebased into SilverStripe 4. LeftAndMain and AssetAdmin have changed too much since the issue was raised.

**Pull request closed without merging**
