### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by nickbyfleet**
Fixing broken link.

### CODE REVIEW

**Comment by dhensby** [comment]
ping @robbieaverill

**Comment by dhensby** [comment]
@nickbyfleet this isn't the right way to fix this. it looks like our API parser might be broken if this link isn't working

**Comment by robbieaverill** [comment]
Yeah, these should be automatically determined by the shortcode syntax rather than direct links

**Comment by SpiritLevel** [comment]
The parsing of [api:Director] style short codes seems to be generating the correct query:

api.silverstripe.org/search/lookup/?q=Director&version=3&module=framework

The problem is that the api site no longer processes such queries. These queries used to work :(

**Comment by sminnee** [comment]
Have created https://github.com/silverstripe/api.silverstripe.org/issues/33 to cover that

**Pull request closed without merging**
