### PR TITLE
FIX text/json is not a valid mimetype

### PR DESCRIPTION
**Pull request by dhensby**
Partial fix of https://github.com/silverstripe/silverstripe-framework/issues/5594

### CODE REVIEW

**Comment by robbieaverill** [comment]
Do you want to target a patch release?

**Comment by lerni** [comment]
targeting a patch release... I wonder when "text/json" is replaced with "application/json" on php side, will the new mime-type be mainstream enough on production servers or does it need to be added to .htaccess & equivalent like 'AddType 'application/json; charset=UTF-8' json' or just mentioned in release notes?

**Comment by kinglozzer** [comment]
@lerni I’d hope that people don’t have `text/json` in their `.htaccess` as it’s not a valid mime type. If they _do_ have that, but don’t have `application/json`, then in theory this could result in some caching changes - but it will also fix things in the opposite case!

**Comment by dhensby** [comment]
> Do you want to target a patch release?

personally I don't think it should go in a patch release; I intended it at the minor release

**Comment by dhensby** [comment]
@lerni `text/json` was never a valid mime-type so there shouldn't be any webserver support for it ever...

There was a draft `text/x-json` but that was never official

**Comment by lerni** [comment]
@dhensby I've seen it on a server and I think it was used quite a bit. Since it was never official and application/json and is more with spread nowadays, sure this fixes more than it breaks.

**Pull request merged**
