### PR TITLE
Fix up travis master build

### PR DESCRIPTION
**Pull request by tractorcow**
I had mistakenly pushed a 2.0.x-dev constraint, which didn't match the master alias 2.x-dev

### CODE REVIEW

**Comment by tractorcow** [comment]
I've updated branches and tags on the postgres / sqlite repos so hope this fixes this build. :)

**Comment by tractorcow** [comment]
Added more branch and alias changes on behat-extension and testsession now.

**Comment by tractorcow** [comment]
Missed a merge of assets module branches up to master... done now and restarted build.

Almost there!

**Comment by robbieaverill** [comment]
Still looking good. Merge on green

**Comment by kinglozzer** [comment]
So close! The PHPCS issues raised in `Director` are real :(

**Comment by dhensby** [comment]
Merged by hand to fix the code style issues

**Pull request merged**
