### PR TITLE
BUGFIX: DataQuery overwriting _SortColumn selects

### PR DESCRIPTION
**Pull request by unclecheese**
Due to `$i` not being augmented properly, the `ensureSelectContainsOrderByColumns` function was overwriting previous indexes

Resolves: https://github.com/silverstripe/silverstripe-framework/issues/8926

### CODE REVIEW

**Comment by dnsl48** [comment]
This `$i` looks like a booby trap. Maybe we should redo it so it's controlled by the loop construction rather than manually increment it?

Something like
```php
$i = 0;
foreach ($orderby as $k => $dir) {
    $newOrderby[$k] = $dir;
```
would become
```php
foreach (array_keys($orderby) as $i => $k) {
    $dir = $orderby[$k];
    $newOrderby[$k] = $dir;
```

**Comment by dnsl48** [comment]
@unclecheese why? :)

**Comment by unclecheese** [comment]
Whoa, ZenHub error. Sorry about that.

**Comment by unclecheese** [comment]
As a recap, I think where we were stuck on this was:

If `$i` is just the iteration of the loop, then it will only work if `_SortColumn{$i}` is named as its index in the entire `sort()` array. But I think `_SortColumn{$i}` is derived from the index of *only non-field expressions* (like surrogates), in which case you don't want to augment the $i on those `continue` blocks.

For instance

```php
->sort([
  'MyField',
//  If this is _SortColumn0, then incrementing in each iteration of the loop will break. If it's _SortColumn1, then we're sweet.
  '(SELECT ID From AnotherTable)' 
])
```

**Comment by dnsl48** [comment]
Sorry, but it looks like the problem goes deeper and not gonna be that easy :)
I've updated the [test](https://github.com/silverstripe/silverstripe-framework/pull/8927) (added another surrogate there).
Basically, `_SortColumn` indexes are already allocated at the point we `::ensureSelectContainsOrderbyColumns`, so if we simply increment `$i`, we're going to overwrite non-surrogate fields which position in the ordering list equals to the surrogate index slot.

**Comment by dnsl48** [comment]
@unclecheese I've added a possible solution as a new commit on top of the PR. Please have a look.

**Comment by unclecheese** [comment]
Good stuff, thanks.

**Pull request merged**
