### PR TITLE
BUG Prevent password validator min score producing false negatives

### PR DESCRIPTION
**Pull request by tractorcow**
Replaces #7995

Fixes min score failing if no tests are set
Fixes min score failing if there are no failing tests
Adds unit tests to cover the above
Fix up bad phpdoc, code style, linting, and upgrade deprecated API usage

### CODE REVIEW

**Comment by dhensby** [comment]
OK - I assume this is a bug in 4.0 as well as 4.1, can we target 4.0 whilst it's still a supported version?

**Comment by tractorcow** [comment]
Actually 4.0 is safe; We'd refactored PasswordValidator in 4.1, introducing the bug there.

**Comment by chillu** [comment]
@dhensby Are you                        happy to merge this?

**Comment by dhensby** [comment]
I am, but does it fully address the initial bug?

**Pull request merged**
