### PR TITLE
FIX: Saving null values to the _versions table.

### PR DESCRIPTION
**Pull request by frankmullenger**
The isset() check does not return true when a value is set to null, so instead use array_key_exists().

### CODE REVIEW

**Comment by frankmullenger** [comment]
@tractorcow implemented your array_key_exists() fix :-)

**Comment by tractorcow** [comment]
It's possible the test that failed was relying on the incorrect behaviour... I'll have a look into it.

**Comment by dhensby** [comment]
bump @tractorcow

**Comment by tractorcow** [comment]
Pushed up a fix. :D

**Comment by dhensby** [comment]
behat brokened :(

**Comment by tractorcow** [comment]
Behat is fixed in another PR.

**Pull request merged**
