### PR TITLE
BUG Prevent session hijackers from resetting a user password

### PR DESCRIPTION
**Pull request by tractorcow**
BUG Member::checkPassword incorrect for default admin

Jira reference: https://silverstripe.atlassian.net/browse/CWP-877

### CODE REVIEW

**Comment by dhensby** [comment]
Behat test failing...

**Comment by tractorcow** [comment]
Doh, Misbehatving...

**Comment by tractorcow** [comment]
Pushed up a fix to behat tests. Tested locally this time. :)

**Comment by tractorcow** [comment]
Thank you. ;D

**Pull request merged**
