### PR TITLE
FIX Allow only one file when scaffolding has_one File relationship

### LINKED ISSUE #8862: Form scaffolding for has_one File allows multiple files
## Affected Version

4.3.2 (and all others I think)

## Description

If a DataObject has a has_one relationship to a File or Image, only one file should be allowed to be uploaded / selected. However, the CMS user can select and/or upload multiple files, only the first of which will be saved to the relationship.

## Steps to Reproduce

Create a has_one relationship to a File or Image on any DataObject and allow the field to be automatically scaffolded by `getCMSFields()`.

## Suggested fix

The form scaffolder should call `->setAllowedMaxFileNumber(1)` on the scaffolded UploadField.

### PR DESCRIPTION
**Pull request by jonom**
Fixes #8862

### CODE REVIEW

**Comment by jonom** [comment]
What does the `2` in `The command "if [[ $PHPCS_TEST ]]; then composer run-script lint; fi" exited with 2.` mean? 🤔

**Comment by robbieaverill** [comment]
CodeSniffer has a bug at the moment, so we can ignore phpcs failures. See https://github.com/squizlabs/PHP_CodeSniffer/issues/2450

**Comment by michalkleiner** [comment]
Should it be `method_exists` or `has_method` check?

**Comment by jonom** [comment]
> Should it be method_exists or hasMethod check?

You tell me 🤷‍♂️ what's the difference?

**Comment by robbieaverill** [comment]
The latter includes added methods from extensions

**Comment by jonom** [comment]
Good to know. Have changed it to `hasMethod`.

**Pull request merged**
