### PR TITLE
BUG Ensure GridState_Component is added to GridField config

### PR DESCRIPTION
**Pull request by tractorcow**
Replaces https://github.com/silverstripe/silverstripe-framework/pull/6896

Fixes https://github.com/silverstripe/silverstripe-framework/issues/6886

### CODE REVIEW

**Comment by dhensby** [comment]
ok, looking good

**Comment by tractorcow** [comment]
Yeah it was looking good, why was it closed without merge?

**Comment by tractorcow** [comment]
that's why :D

**Comment by tractorcow** [comment]
@dhensby rebased.

**Comment by dhensby** [comment]
sorry this dropped off my radar - I've been struggling to keep up with notifications. I've merged this up into master now too :)

**Pull request merged**
