### PR TITLE
FIX: Fix PHPUnit operation on PHP 7.4

### LINKED ISSUE #9062: PHPUnit 5.7 doesn't support PHP 7.4
[Recent build breakages](https://travis-ci.org/silverstripe/silverstripe-framework/jobs/545057773) have highlighted that the mocking system of PHPUnit 5.7 (well, phpunit-mock-objects 3.4) uses an API that was documented as deprecated in PHP 7.1 and started throwing deprecation errors in PHP 7.1

PHPUnit 8 solves that, but we're not using that in SilverStripe 4, and although we might be able to get away with using it in SS 4.5+, now that we've dropped php 5.6 / 7.10, it likely has breaking API changes that would force SS4 test suites to be rewritten, which wouldn't be okay.

Possible solutions:

 1. Patch phpunit-mock-objects, hopefully via a PR to the upstream project, or by creating a fork of our own
 2. Drop support for php 7.4, meaning that SS4 has an externally driven end-date of 6 Dec 2021

I'm not happy about the 2nd as this caused us a lot of pain with SS3. So I think we need to patch php-mock-objects. Ideally we can bump up to php-mock-objects 4, 5, or 6 breaking the APIs we use and Sebastian will accept a PR to those more recent versions and produce a stable tag. But failing that we will probably want to publish a fork.

# Pull Requests
* [x] https://github.com/silverstripe/silverstripe-framework/pull/9063

### PR DESCRIPTION
**Pull request by sminnee**
Fixes #9062. Note that this may not be the best way to fix this (see discussion on the original ticket)

### CODE REVIEW

**Comment by sminnee** [comment]
@robbieaverill if you want a hacky shim that minimises the need for project/module devs to make changes, then we could change this form require-dev to require.

**Comment by robbieaverill** [comment]
True but then it would be installed in production sites, which is also not ideal. I’ll tinker a little and get back to you.

**Comment by sminnee** [comment]
The crux of the issue for me is: if you provide some monkey patches, then your monkey patches are also going to end up in production sites. In addition, you have the confusion of monkeypatching. So.. why is that better?

The ideal would be if we have a metapackage that we recommend that project/module developers add to their `require-dev`. If we had that in place, we could solve this by adding it to the metapackage. Perhaps we want to adopt that now, and this can be its first addition?

**Comment by robbieaverill** [comment]
We can add workarounds into the tests folder, which is excluded from distributable packages (i.e. production)

**Comment by sminnee** [comment]
...but won't those also be excluded when you pull a distributable package into a module's travis run?

PS: 7.4 tests pass; i've pulled it out of allowed_failures on this PR.

**Comment by sminnee** [comment]
I've raised #9067 as an RFC for what I think might be helpful for this.

**Comment by sminnee** [comment]
@silverstripe/core-team right now the shifting of php 7.4 to "allowed failures" means that non-PDO MySQL isn't being tested.

Can we merge this patch or should we be adding a new non-PDO MySQL test?

**Comment by robbieaverill** [comment]
I'll spend some time today looking at this, I still think we can do a shim in framework

**Comment by sminnee** [comment]
PS: I'm of the view that my current fix is cleaner than a shim; although it depends a bit on seeing the actual shim code.

**Comment by robbieaverill** [comment]
Yeah it is a cleaner fix for sure, but it's going to break everybody's projects when they start testing on PHP 7.4, until they've worked out they need to install this

**Comment by sminnee** [comment]
Well, no, it's not going to break anyone's projects, it's just not going to magically fix them. :P

**Comment by sminnee** [comment]
Keen to get other views, in any case.

**Comment by robbieaverill** [comment]
Yep, @silverstripe/core-team please review when you have a chance.

**Comment by kinglozzer** [comment]
> Well, no, it's not going to break anyone's projects, it's just not going to magically fix them.

Given that, I think this is fine. We did something arguably similar (albeit not related to composer) with the opt-in `SS_Object` changes for 3.x + PHP 7.2.

**Comment by robbieaverill** [comment]
Yeah OK fair enough. In lieu of getting time to test an alternative approach, let's merge this now anyway. It's definitely an improvement.

**Comment by sminnee** [comment]
@robbieaverill is it cool if I cherry-pick this into https://github.com/silverstripe/silverstripe-framework/pull/9098 targeted at 4.4? It's important that I test all database backends for that.

**Comment by sminnee** [comment]
Nevermind that won't work.

**Pull request merged**
