### PR TITLE
Ensure tmpData exists

### PR DESCRIPTION
**Pull request by lekoala**
Otherwise you might get illegal string offset

### CODE REVIEW

**Comment by tractorcow** [comment]
@lekoala can you give an example which would produce the array offset error?

**Comment by tractorcow** [comment]
Seems ok logically. The whole code block is a bit hard to read but that's an existing issue. ;)

**Comment by lekoala** [comment]
I'm not quite sure, I'm having some fields with lots of nesting like Data[Items][1][MyField] (that is serialized to json) and sometimes it happens. the changes has no side effects except preventing a php error so that cannot hurt :-)

**Comment by tractorcow** [comment]
Yes I think so.

**Pull request merged**
