### PR TITLE
API Remove ViewableData::ThemeDir, update changelog to reflect suggested replacement

### LINKED ISSUE #6578: [4.0] ViewableData::ThemeDir doesn't support cascading themes
`ViewableData::ThemeDir` hasn't been updated to support a `SilverStripe\View\SSViewer.themes` property - is still looking for the string value of `.theme`

### PR DESCRIPTION
**Pull request by robbieaverill**
* Remove `ThemeDir` from `ViewableData`
* Add note to changelog regarding removal, and suggest using `ThemeResourceLoader::findThemedResource` in conjunction with `SSViewer::get_themes` instead.

Resolves #6578

### CODE REVIEW

**Comment by robbieaverill** [comment]
Since it can't be done in a single call from templates without a controller method to wrap, should we add a similar method to `requireCSS` somewhere?

**Comment by tractorcow** [comment]
Do you mean adding a themedImage function? Probably just best to hard-code it for that theme, to be honest.

**Comment by robbieaverill** [comment]
True- it's probably a unique file to that theme

**Comment by robbieaverill** [comment]
@tractorcow both points updated

**Pull request merged**
