### PR TITLE
WIP: NEW Use toArray() instead of $this->items where appropriate

### PR DESCRIPTION
**Pull request by robbieaverill**
Allows for toArray() to be modified in child classes and have it be respected in getIterator()

At the moment child classes must overload getIterator() as well to make it use `$this->toArray()` over `$this->items`.

### CODE REVIEW

**Comment by unclecheese** [comment]
Have retargeted to `4.3`.

**Comment by robbieaverill** [comment]
Rebased

**Comment by robbieaverill** [comment]
>Add a note to the toArray() docblock, "This method can be overridden in subclasses to change the contents of the list".

I would've thought that was inherent in the way we design our APIs, e.g. by making things protected rather than private

**Comment by unclecheese** [comment]
I think it's more a question of the naming of that method. It's not very self-documenting. It isn't obvious that a method named `toArray` on a class that is basically an array is the place I would do filtering.

Another approach might be the addition of a protected method `getIteratorItems()` defaulting to `$this->items`.

**Comment by robbieaverill** [comment]
I see what you're saying - yeah, `getItems()` or something would be clearer about its intent. How about I mark this as WIP and add a new method to do this instead of overloading `toArray()`?

**Comment by sminnee** [comment]
> I would've thought that was inherent in the way we design our APIs, e.g. by making things protected rather than private

This is a historic bad habit that makes it very difficult to provide sem-ver. We need to get better about clarifying, documenting, and testing our public API more than "anything technically possible within the bounds of PHP"

**Comment by robbieaverill** [comment]
I'll re-open another one later if I get around to it =)

**Pull request closed without merging**
