### PR TITLE
Do not default to locale if hasEmptyDefault is true

### PR DESCRIPTION
**Pull request by hailwood**
Currently there is no per-instance way to say "don't default to the current locale".
If you've explicitly said "This field right here, it has an empty default value" then we should probably respect that.

### CODE REVIEW

**Comment by dhensby** [comment]
It looks like the `$source = $this->getSource()` can be inside the condition block too

**Comment by dhensby** [comment]
Also, can we add a test case for this, please?

**Comment by hailwood** [comment]
@dhensby You're right it can, also, do we have any tests at all for the country dropdown field? Wen't to modify them but couldn't find them?

**Comment by dhensby** [comment]
There may well be no tests - don't feel like you need to add coverage for everything just this, please 👼

**Pull request merged**
