### PR TITLE
DOCS Explicitly noting lack of PHP 7 support

### PR DESCRIPTION
**Pull request by dhensby**
Coz you know... apparently 5.3.2 is ambiguous about not supporting PHP 7

### CODE REVIEW

**Comment by sminnee** [comment]
I think it would be more helpful to include a section such as this, to answer the inevitable question.

    ## Why doesn't SilverStripe 3 work with PHP 7?
    Unfortunately, SilverStripe has classes named the same as PHP reserved words, such as "Int" and "Float". This means that we are unable to make SilverStripe 3 support PHP 7 without breaking backward compatibility. SilverStripe 4 will work with PHP 7 and will be released in 2016. Until then, we recommend that you use PHP 5.6.

**Comment by dhensby** [comment]
Sure. I'll add it

**Comment by chillu** [comment]
@dhensby ping

**Comment by dhensby** [comment]
@chillu done.

**Pull request merged**
