### PR TITLE
DEP Remove unused league/flysystem requirement

### PR DESCRIPTION
**Pull request by Cheddam**
A bug in Flysystem was breaking the prefer-lowest build of silverstripe/assets, which led us to discover that the package isn't even used in framework. I've introduced a direct dependency on it in https://github.com/silverstripe/silverstripe-assets/pull/424.

### CODE REVIEW

**Comment by sminnee** [comment]
Why is it a dependency of this repo and not assets?

**Review by sminnee — CHANGES_REQUESTED** [review]
Let's do this in assets instead.

**Comment by Cheddam** [comment]
I can only find one reference to Flysystem in the source for Framework, and it's an unused `use` statement 😂 

That said, would shifting the dependency be considered a breaking change? For 99.999% of projects it's probably a non-issue, so maybe it's not even worth debating (since any Framework-only project should be defining the Flysystem requirement directly anyway.)

**Comment by Cheddam** [comment]
I've changed this PR to instead drop Flysystem from Framework. The only risk I can see is that a project could update to silverstripe/framework 4.7.0 without also updating to silverstripe/assets 1.7.0, leaving them without Flysystem. Two options:

1. Introduce a conflict with silverstripe/assets <1.7
2. Add a note about it to the 4.7 release notes, and assume developers will be able to get themselves out of the situation very easily

**Comment by michalkleiner** [comment]
I think we used the library once in a project code to handle something project-specific since it came with the framework, but a note in the release notes would make us re-test it and include the dependency separately as a solution, so "_2. add a note to 4.7 changelog_" would suffice from our perspective.

**Comment by sminnee** [comment]
An upgrade note is probably since very few people will upgrade framework but not assets. If for some reason this use-case comes up I'd probably be more inclined to release another 1.6.x tag of assets with the composer dependency included there.

**Comment by sminnee** [comment]
One thing to note, @Cheddam - ideally we could include that upgrade note with this PR. As it stands, we don't generate those docs until the next release. In other projects people will sometimes have an "unreleased" document/section where these things can be collated as we go.

Is it worth raising with the people on the tools for releases whether this would be a good idea?

**Comment by Cheddam** [comment]
The 'process' for this at the moment is that the first person wanting to add something to the changelog [creates it by hand](https://github.com/silverstripe/silverstripe-framework/commit/c6b698cb027a14e9b0a2ce3e403ce12d1bc132d3#diff-754a51ef9f041c2adf27a7e0332bc209), (hopefully) copying [the template that Cow would use itself](https://github.com/silverstripe/silverstripe-installer/blob/4/.cow/changelog.md.twig). This could obviously be more consistent, and we run the risk of missing details in the changelog when we leave writing it until release.

So, I've just talked to the team, and we're going to tweak our process to start creating a provisional changelog for the next minor immediately following the stable release of the previous one, so that we can ensure the template is used correctly, and that it's always available for contributors to add to when they land a change.

I've raised [a separate PR](https://github.com/silverstripe/silverstripe-framework/pull/9729) to add one for 4.7.0, and I'll update this PR with notes once that's merged.

**Review by dhensby — APPROVED** [review]
I'm happy to remove deps - there is a risk if assets isn't declaring it (it should have been!) - but we can add it as a dep there and it should be fine.

**Comment by sminnee** [comment]
Yeah it'll be added to 1.7 but if you install framework 1.7 and assets 1.6 it won't pull the dep in. Not impossible but a very strange setup. I'd wait until someone complains before patching assets 1.6 to support that case.

**Comment by michalkleiner** [comment]
If assets can be patched in 1.6 line, adding the deps, why not do it and wait for 1.7? Why wait for a complain?

**Comment by Cheddam** [comment]
@michalkleiner It's overhead we're better off not incurring if possible, and we'd encourage developers to resolve the issue by updating the assets module to `1.7.x` instead. Running inconsistent minors isn't a recommended practice.

@sminnee Changelog notes are up 👍

**Review by sminnee — APPROVED** [review]

**Comment by chillu** [comment]
Weird edge case incoming ;)

```
{
    "name": "test/test",
    "require": {
        "silverstripe/framework": "^4.7"
    },
    "minimum-stability": "dev",
    "prefer-stable": true
}
```

```
composer --version
Composer version 2.0.7 2020-11-13 17:31:06

composer install

composer info | egrep '(assets|framework)'
silverstripe/assets                   1.6.1     SilverStripe Assets component
silverstripe/framework                4.7.0-rc1 The SilverStripe framework

composer why silverstripe/assets
silverstripe/framework  4.7.0-rc1  requires  silverstripe/assets (^1@dev) 
```

**Comment by Cheddam** [comment]
Yep I saw a community member hit the same thing recently. The good news is that it will be resolved when we tag 4.7.0 stable in just a couple of weeks 🙂 Definitely lends some credence to making sure we keep core requirements in lock-step at the minor level, since if we'd bumped the assets requirement to `^1.7@dev` this wouldn't be occurring.

**Pull request merged**
