### PR TITLE
Update Tutorial 1

### PR DESCRIPTION
**Pull request by scott1702**
'?flush=1' changed to '?flush', '=1' is not required.

### CODE REVIEW

**Comment by micmania1** [comment]
The requirement for '=1' has only just been removed so it might be worth keeping this in the docs for now? It won't work for slightly older versions 3.1 - 3.1.6 (or thereabouts) so could trip people up.

**Comment by dhensby** [comment]
> The requirement for '=1' has only just been removed

From what I can see there was no stable release where it didn't work without a `=1`. If you were running the 3.1 branch between 3.1.6 and 3.1.7 then for a month or two it would have been the case that it wouldn't have worked (August - October was the un-patched period).

However, I'm not sure that removing the `=1` is a good idea even if it isn't explicitly required as it may confuse some people and doesn't have any unexpected consequences in doing so.

**Comment by kinglozzer** [comment]
I’d also be inclined to leave it as-is: the `=1` is currently required on the command line, so for the sake of consistency I think we should always recommend `flush=1`.

**Comment by dhensby** [comment]
OK, closing this. Thanks @scott1702 - it's something I thought about myself too, but I think on balance it should be there.

**Pull request closed without merging**
