### PR TITLE
Rename DataObject method name

### PR DESCRIPTION
**Pull request by sabina-talipova**
## Issue
- https://github.com/silverstripe/silverstripe-userforms/pull/1182

### CODE REVIEW

**Review by emteknetnz — CHANGES_REQUESTED** [review]
We should not be renaming this method because of the failure on a totally unrelated module - that won't stop the same issue happening again on a different module

Instead we should be using is_callable() as mentioned [here](https://github.com/silverstripe/silverstripe-userforms/pull/1182#issuecomment-1376553002)

**Comment by sabina-talipova** [comment]
> Instead we should be using is_callable() as mentioned [here](https://github.com/silverstripe/silverstripe-userforms/pull/1182#issuecomment-1376553002)

Using this approach, some "setProperty" methods in another classes fail Unit tests. Initially I implemented this approach, but after testing I think better to rename method and open issue to fix problem with private methods.
Please have a look: https://github.com/silverstripe/silverstripe-framework/commit/31df80e79124764b0a08cd9c13b3a3c871a33079
and
https://github.com/silverstripe/silverstripe-framework/actions/runs/3879244028/jobs/6616354722

**Review by emteknetnz — CHANGES_REQUESTED** [review]
In ViewableData::__set() it should be `is_callable([$this, $method])`, not `is_callable($this, $method)`;

**Comment by sabina-talipova** [comment]
> In ViewableData::__set() it should be `is_callable([$this, $method])`, not `is_callable($this, $method)`;

Just using `is_callable`, probably doesn't solve the problem, even together with `method_exist`. I think problem is more deeper and will appear time to time, especially with some Field names.
How I understood, because we have a `trait CustomMethods` which has magic method `__call` and we use this trait in `trait Extensible` , that we use in `class ViewableData` . 
It means if some class extends `ViewableData` or `DataObject` and we will have in `ViewableData` or `DataObject` classes `setSomething` methods and extending class has `Something` field, even if `setSomething`  is private `method_exist` returns TRUE and `is_callable` returns TRUE, since `CustomMethods` has magic method ` __call` . 
I've done some tests and `is_callable` returns TRUE for `setFieldValue`  in `EditableCustomRule class`.

**Review by maxime-rainville — COMMENTED** [review]
There probably should be a unit test to cover this edge case.

Are we happy with the magic setter accessing protected method?

**Comment by sabina-talipova** [comment]
@emteknetnz said that we should _**check that method is NOT private. Public or protected are fine.**_

**Comment by sabina-talipova** [comment]
> There probably should be a unit test to cover this edge case.

DONE. New test case was added.

**Review by maxime-rainville — APPROVED** [review]
LGTM

**Pull request merged**
