### PR TITLE
BUG Fix deprecated API usage in DataFormatter API and DataObjectTest

### PR DESCRIPTION
**Pull request by tractorcow**
PHPDoc Cleanup
API DataFormatter::convertStringToArray is now abstract

These classes are so messy.

### CODE REVIEW

**Comment by tractorcow** [comment]
THANKS!

**Comment by dhensby** [comment]
The data formatters are broken because they don't use the same priority for using `get` functions, methods and properties as one would expect 

This causes problems in the restfuleserver module

**Comment by tractorcow** [comment]
Do you mean broken now, or broken with this change? More info please! :D

**Comment by dhensby** [comment]
Sorry, were broken - not by this change.

**Pull request merged**
