### PR TITLE
Update 03_Environment_Management.md

### PR DESCRIPTION
**Pull request by DorsetDigital**
Remove reference to DATABASE_SUFFIX - this doesn't appear to be used anywhere in the installer or core kernel.

### CODE REVIEW

**Comment by kinglozzer** [comment]
Related https://github.com/silverstripe/silverstripe-framework/issues/7966

**Comment by DorsetDigital** [comment]
That looks like a fun conversation :-)    I think we should probably make the docs match the current state of the code, even if the functionality is going back in at some point.

**Comment by dhensby** [comment]
ergh :( this is why we should have fixed the bug when it was reported 3 months ago :(

Fixing something not working when it should have been is not a regression!

**Comment by maxime-rainville** [comment]
I think Damian's [original point still stands](https://github.com/silverstripe/silverstripe-framework/issues/7966#issuecomment-378745244). I we fix the original issue, there's a good chance that somebody somewhere will have a terrible day because their live system suddenly expects their DB to be called `SS_something_suffix_suffix`.

In this context, I think it would make more sense to just remove the suffix option from the doc.

**Comment by kinglozzer** [comment]
This _may_ be replaced by https://github.com/silverstripe/silverstripe-framework/pull/8470 if that PR is accepted

**Comment by sminnee** [comment]
Recommend that we cancel this in favour of #8470

**Pull request closed without merging**
