### PR TITLE
Fixes #5086

### LINKED ISSUE #5086: Member_Validator doesn't validate existing Members (identifier field)
There seem to be some issues with [`Member_Validator`](https://github.com/silverstripe/silverstripe-framework/blob/8e4db95f7297f4621413609fd0ff5bbe0385bf37/security/Member.php#L1812):

1.  It doesn't validate when there's no ID present (eg. doesn't work when creating new members)
2.  It seems to use some SilverStripe 2.x request lookup to determine the member-id (`$_REQUEST['ctf']['childID']`)
3.  It has a completely broken way to run validation on extensions (extending the validator basically doesn't work at all)

This isn't too much of an issue, since once validation fails, there is always `Member::onBeforeWrite` that will act as a safety net. The nice thing about a properly working validator is, that custom built Forms won't be completely wiped when trying to create a member.

Here's a [gist](https://gist.github.com/bummzack/95840febd7515198b36a) of what I'm currently using as a replacement. It could be a *complete* replacement, if [this piece of code](https://github.com/silverstripe/silverstripe-framework/blob/8e4db95f7297f4621413609fd0ff5bbe0385bf37/security/Group.php#L118) would be aware of injections :)

I'd gladly provide my implementation of the validator as a replacement for `Member_Validator`, if wanted.

### PR DESCRIPTION
**Pull request by bummzack**
Improve `Member_Validator` to:
- properly check for existing members.
- allow extensions.
- remove old code and replace with new syntax and add config api.

Fix issue in Group code where Member_Validator was instantiated via "new" which didn't allow injector overrides.
Added unit-tests.

### CODE REVIEW

**Comment by bummzack** [comment]
I seem to have butchered some doc-comments. I'm really sorry. Will PR again.

**Comment by dhensby** [comment]
@bummzack ping me with a mention when it's open

**Comment by tractorcow** [comment]
me also :D

**Comment by bummzack** [comment]
@tractorcow It's over here: #5091, sorry I created two PRs for this.

**Pull request closed without merging**
