### PR TITLE
NEW Use splat operator for extensible calls

### PR DESCRIPTION
**Pull request by dhensby**
As we're now php 5.6+ in master we can use the ellipsis operator on the extend calls.

### CODE REVIEW

**Comment by flamerohr** [comment]
There are cases where some hacks check for 8 args to understand if the function was called by an `extend()`
do you think those in core have been addressed?

**Comment by tractorcow** [comment]
Yep, we have this in Versioned.php

```php
public function canPublish($member = null)
    {
        // Skip if invoked by extendedCan()
        if (func_num_args() > 4) {
            return null;
        }
```

I raised this issue over at https://github.com/silverstripe/silverstripe-framework/issues/6210.

**Comment by dhensby** [comment]
> There are cases where some hacks check for 8 args to understand if the function was called by an extend() do you think those in core have been addressed?

🤦‍♂️ 

I'll look into this....

**Comment by tractorcow** [comment]
@sminnee has confirmed he's happy to split canView() into canView and extendsCanView(). (see https://github.com/silverstripe/silverstripe-framework/issues/6210). That will unblock this story, although it'll need to be done at the same time, or earlier.

**Comment by tractorcow** [comment]
Blocked by https://github.com/silverstripe/silverstripe-framework/issues/6210

**Comment by tractorcow** [comment]
Shifting to 5.x milestone as there are no more API breakages to go into 4.x at the moment.

**Comment by dhensby** [comment]
😱 is this going to be an API breakage? is it because we need to change how extensions can avoid self-calling themselves?

**Comment by tractorcow** [comment]
Yes that's right.

**Comment by tractorcow** [comment]
@dhensby replaced with:

 - https://github.com/silverstripe/silverstripe-framework/pull/7752
 - https://github.com/silverstripe/silverstripe-versioned/pull/84

**Pull request closed without merging**
